### ISSUE TITLE
ceterms:TaskProfile

### ISSUE THREAD

**Issue by bobgsheets** [CredentialEngine/vocabularies#121]
I have only seen one use of "tasks" and this is when it is used to address "application" but only in a few of the credentials

Are there others?   If not, what is it intended to capture?

All credentials have an application process and how do we capture that now?   Is it under tasks or something else?

**Comment by siuc-nate** [comment]
If it's something that requires action by the pursuer of the credential, and it's not an assessment or a learning opportunity, then it would fall under task profile. So, if the application process isn't inherent in taking the assessment or the learning opportunity (i.e., you wouldn't have a task profile for "register for classes" or "show up for the assessment") then it would be a task, under the current design.

**Comment by jkitchensSIUC** [comment]
@bobgsheets @stuartasutton @siuc-nate goal.... get past the open list of issues and move on to certification renewals and how task profile is or isn't used for renewals. Also, how it may or may not be pertinent to QA organizations.

**Comment by siuc-nate** [comment]
Given our recent enhancements to ConditionProfile (most notably the "condition", "submissionOf", and "estimatedCost" properties) and surrounding discussions, I think it may be viable to drop TaskProfile, as these should cover its primary use case(s).

**Comment by siuc-nate** [comment]
Can we close this issue?

**Comment by stuartasutton** [comment]
If we have not identified any task at this point that are not otherwise covered, then dropping it would make sense.

**Comment by jkitchensSIUC** [comment]
This is to document some thoughts:
- tasks are relevant in the workplace.   Potential use case is completion of work tasks toward a credential.
- Employers/Industry are stakeholders in the credential ecosystem.
