### ISSUE TITLE
Enable Multiple Languages

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#254]
Enable Multiple Languages

**Comment by stuartasutton** [comment]
Jeanne, I added "Feature Request" label and then realized that I actually don't know what "enable multiple languages" means.

**Comment by siuc-nate** [comment]
This is in regards to getting the spreadsheets or some other similar mechanism to enable multiple languages for the schema (preferably without having to have a "join" section for every kind of literal value)

**Comment by siuc-nate** [comment]
The current plan is to handle this as a part of moving schema management to a neo4j-based system.

**Comment by jkitchensSIUC** [comment]
Revisit this to include solution with the April release.

**Comment by siuc-nate** [comment]
This has been handled here:
https://github.com/CredentialEngine/vocabularies/issues/353#issuecomment-288153409
