### ISSUE TITLE
Documenting "Release History" and term change history

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#262]
As we move forward **STARTING NOW** with changes and additions to the CTDL, I propose the following process. We'll need to follow it diligently if we want easy preparation of release notes and term-level documentation.

First, we have two separate kinds of documenting of change: 

1. Documenting change through a Release History page; and
1. Documenting CTDL term changes so they are available through a `skos:changeNote` property in the affected term's schema.

See also #238 on documenting kind number 2. That issue outlines two distinct mechanisms for handling term change in code: (a) one where the RDF encoding is maintained as part of the term declaration through the addition of changes to the schema/schemes through a set of bnode of the class `cs:ChangeSet`; and (b) where the changes are separate from the term declaration and accessed through a `skos:changeNote` property referencing URI-identified instances of `cs:ChangeSet`.

### How to note issues on-the-fly with 'issue labels' for handling change documentation

I had added a few new labels to the issues in github for tracking changes that need change documentation.  Please review the categories of change as set out in the [CTDL Namespace Policy](http://www.credreg.net/ctdl/namespacepolicy) for the definitions (and any review & comment period processes possibly triggered) for each.  ***Use these labels for no other reason.*** The first, `History` is for any necessary change needing formal documentation that is not covered by the more refined history issue labels.

> History 
> History (Minor Errata)
> History (Substantive Errata)
> History (Substantive Change)
> History (Term Addition) 
> History (Term Deprecation)

**NOTE 1:** These issue labels could possibly be used for History Page sections for each release. 

**NOTE 2:** Once a change has been documented on the Revision History page and in the schema/schemes where necessary, the history label(s) **should be removed** from the pertinent issues so they disappear from the history label filters--i.e., the filters only indicate unfinished stuff for the next scheduled release. At closing of a History issue, the last entry should be of "ACTION TAKEN"--e.g., "Release History updated", "Schema (or scheme) updated".

Nate, we might explore whether there could be a "spreadsheet solution" for this documentation that could generate the necessary documentation for both the Release History page and additions of `cs:ChangeSet` information using one or the other of the mechanisms outlined in related issue #238.

**Comment by stuartasutton** [comment]
Also, to aid on documenting change, we might consider creation of a small controlled vocabulary (`ChangeType`) for the following concepts:

> Minor Errata
> Substantive Errata
> Substantive Change
> Term Addition
> Term Deprecation

This should NOT be in the CTDL namespace but, perhaps, in a 'http://purl.org/ce/vocabs/' (partial) namespace so credential folks don't confuse it with something useful in describing CTDL terms :-)

We could then add the property 'ce:changeType` with domain of `cs:ChangeSet` and a range of `ce:ChangeType`.

**Comment by siuc-nate** [comment]
I have created a temporary history tracking board here:
https://github.com/CredentialTransparencyInitiative/vocabularies/projects/1
So we can note history changes and close issues until a proper system can be developed.

Please only include "Action", "Reason", and "Issue" items using the existing notes as a guide - any and all elaboration belongs in the github issues, not in the history notes at this time.
