### ISSUE TITLE
Adding SSL functionality

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#264]
Should we plan to support SSL on the final endpoint?  That is really the best practice.  E.g., on the final endpoint:

```
https://purl.org/ctdl/schema/context/ = http://credreg.net/ctdl/schema/context/json
```
Increasing numbers of projects are forbidden to use terms from vocabularies that don't use "https". (e.g., DCMI has an ongoing discussion around its terms and supporting "https")

**Comment by jkitchensSIUC** [comment]
@stuartasutton we can purchase an SSL for the credreg domain.

**Comment by stuartasutton** [comment]
Which is not a bad idea regardless; but, the https/http question is a
larger one (I think). There's been discussion in the DCMI IAC
(Infrastructure Architecture Committee) about deploying both with the DCMI
terms namespace and I recall questions regarding whether terms would be
treated as the being the same or considered as from different namespaces.
I'll ask the committee.

**Comment by stuartasutton** [comment]
I have one response so far to my question about https to the DCMI Infratsructure Archiceture Committee (IAC) from Gregg Kellogg but likely get more over the next 4-5 days. 

> "Namespace should remain http, but all requests shout redirect (301, I think) to equivalent https address." --Gregg

**Comment by siuc-nate** [comment]
We will purchase an SSL certificate for the credreg site.

**Comment by stuartasutton** [comment]
There is more discussion on this going on over at schema.org...they are undecided on "how" as well.

**Comment by mparsons1953** [comment]
We have purchased the SSL certificates for credreg.net. We had some conflicts with existing SSL ports on our existing web server. We could resolve this by:
- requesting a new public IP address, and configuring credreg.net to use the latter, and then configure SSL appropriately
- OR, create a new VM for exclusive use by credreg.net. For the latter we will need to consider the option to configure load balancing.

**Comment by mparsons1953** [comment]
The SSL certificates have been configured, so https://credreg.net is now a valid URL, and available when needed. 
We are monitoring discussions on the use of https for vocabulary terms for future actions.

**Comment by siuc-nate** [comment]
Can this issue be closed?

**Comment by stuartasutton** [comment]
No, we should not close it until we've settled the matter.
