### ISSUE TITLE
Distinguishing between 'entry' and 'exit' conditions

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#275]
Jeanne and I briefly discussed the distinctions between what would be considered "entry conditions" (i.e., prerequisites to pursuit of a credential) and "exit conditions" (i.e., required learning opportunities, assessments, and task for earning a credential). I.e.:

> What does it take to get "in"? (entry conditions)
> What does it take to get "out"? (exit conditions)

While the structuring of conditions as discussed and illustrated in https://docs.google.com/document/d/1d85Y1mUhISFxv4rWvuojIJtMFxH_DfmWrBZVLTv0rh0/edit?usp=sharing technically covers the necessary ground, being able to semantically distinguish between these two kinds of conditions is important to end users wanting to know:

> Do I have what it takes to pursue this credential?
> What do I have to do to get this credential?

Solution might be as simple as creating a new property (e.g., `entryConditions`) with domain of `Credential` and range of the current `ConditionProfile` and then using the current properties (`requires`etc.) solely for exit conditions (things to be accomplished during or in renewing etc.)

The examples in https://docs.google.com/document/d/1d85Y1mUhISFxv4rWvuojIJtMFxH_DfmWrBZVLTv0rh0/edit?usp=sharing happen to all be entry conditions.

**Comment by siuc-nate** [comment]
We will include this in the review document for ConditionProfile.

**Comment by stuartasutton** [comment]
Nate, where is the "review document for ConditionProfile"? Can this be expedited. I have an example of use of an `ceterms:entryCondition` property in the Overview:

![fig 2 2b](https://cloud.githubusercontent.com/assets/2939046/22183520/21061f12-e075-11e6-8b09-c2bbda1bb19c.png)

It seems extremely useful to have a simple means of distinguishing those conditions required for entry (i.e., prerequisite conditions) and the general batch (requires, recommends etc.) having to do with conditions to earn and maintain.

**Comment by siuc-nate** [comment]
I believe @jkitchensSIUC intends to have a review document setup to go over our use of ConditionProfile (and possibly a Condition Manifest style extension), but I do not know if such a document exists yet. All I could find was https://docs.google.com/document/d/1d85Y1mUhISFxv4rWvuojIJtMFxH_DfmWrBZVLTv0rh0/edit

**Comment by siuc-nate** [comment]
To wrap up:
- entryCondition is used to define prerequisites
- requires is used to define what would otherwise be considered "exit" conditions

**Comment by stuartasutton** [comment]
@jkitchensSIUC, @siuc-nate & @cwd-mparsons, I've reopened this issue from a year ago because what I thought was happening here with the distinction between [`requires`](purl.org/ctdl/terms/requires) and [`entryCondition`](http://purl.org/ctdl/terms/entryCondition) doesn't appear to be the case in the data or editor.  As noted above (https://github.com/CredentialEngine/vocabularies/issues/275#issuecomment-291546818), The only distinction between `requires` and `entryCondition` is that the former defines what has to be accomplished while earning the credential while the latter is what is required on entry. In fact, `entryCondition` is defined as a subproperty of `requires`; which means that `entryCondition` is a kind of `requires` for all intents and purposes (domains/ranges) but constrained to entry requirements. The goal was for an end user to be able to unambiguously distinguish between what it takes to get in from what it takes to get out. So, the takeaways are:

1. domains and ranges should be declared as coextensive (they currently aren't); and
2. used in the same manner but to distinguish between the two circumstances (entry vs exit).

From what I can tell from the editor and data, this distinction (entry/exit) is not explicitly present. For example, the following editor snippet from Brandman's [Bachelor of Science in Information Technology](https://credentialengine.org/publisher/editor/credential/83):

```
  "ceterms:requires": [
    {
      "@type": "ceterms:ConditionProfile",
      "ceterms:assertedBy": [
        {
          "@id": "https://credentialengineregistry.org/resources/ce-4BF88EC6-FABE-4453-8754-22A2D685252A"
        }
      ],
      "ceterms:condition": [
        "0-11 transferable credits: Official High School transcript with graduation date or an official copy of GED",
        "0-11 transferable credits: High school minimum cumulative GPA of 2.0 or equivalent",
        "0-11 transferable credits: Passing scores on the English and Math admissions tests is required",
        "12 or more transferable credits: 2.0 GPA in all prior college coursework",
        "12 or more transferable credits: Submit official transcripts of all prior academic work completed at all colleges or universities attended"
      ],
      "ceterms:description": "Brandman’s admission process is designed to help determine if the Brandman MyPath Competency-based, online academic model fits your needs.\nOnce admissibility is determined, you will meet with your personal academic coach to discuss, among other items, articulation/transferability of prior coursework. Your qualified transfer credits will then be evaluated for clearance of competencies through the following methodology:\n1. Prior coursework, with a minimum of B- or better from regionally accredited institutions will first be evaluated against Brandman’s credit hour-based courses.\n2. Once prior credit has been determined to be equivalent to Brandman’s credit hour-based program, the university will then determine whether or not you will receive transfer credit for any of the competencies in the Brandman MyPath program.\n3. Transfer credit for competencies will not be granted for prior coursework where the content addresses some, but not all, of the content for a particular competency or block of competencies.",
      "ceterms:name": "Eligibility Requirements",
      "ceterms:targetLearningOpportunity": [
        {
          "@id": "https://credentialengineregistry.org/resources/ce-BC7D4072-E485-422A-837E-6ED890055B6A"
        }
      ]
    }
```

should use `entryCondition` instead of `requires` since the conditions relate to entry and not exit; i.e.:

```
  "ceterms:entryCondition": [
    {
      "@type": "ceterms:ConditionProfile",
      "ceterms:assertedBy": [
        {
          "@id": "https://credentialengineregistry.org/resources/ce-4BF88EC6-FABE-4453-8754-22A2D685252A"
        }
      ],
      "ceterms:condition": [
        "0-11 transferable credits: Official High School transcript with graduation date or an official copy of GED",
        "0-11 transferable credits: High school minimum cumulative GPA of 2.0 or equivalent",
        "0-11 transferable credits: Passing scores on the English and Math admissions tests is required",
        "12 or more transferable credits: 2.0 GPA in all prior college coursework",
        "12 or more transferable credits: Submit official transcripts of all prior academic work completed at all colleges or universities attended"
      ],
      "ceterms:description": "Brandman’s admission process is designed to help determine if the Brandman MyPath Competency-based, online academic model fits your needs.\nOnce admissibility is determined, you will meet with your personal academic coach to discuss, among other items, articulation/transferability of prior coursework. Your qualified transfer credits will then be evaluated for clearance of competencies through the following methodology:\n1. Prior coursework, with a minimum of B- or better from regionally accredited institutions will first be evaluated against Brandman’s credit hour-based courses.\n2. Once prior credit has been determined to be equivalent to Brandman’s credit hour-based program, the university will then determine whether or not you will receive transfer credit for any of the competencies in the Brandman MyPath program.\n3. Transfer credit for competencies will not be granted for prior coursework where the content addresses some, but not all, of the content for a particular competency or block of competencies.",
      "ceterms:name": "Eligibility Requirements",
      "ceterms:targetLearningOpportunity": [
        {
          "@id": "https://credentialengineregistry.org/resources/ce-BC7D4072-E485-422A-837E-6ED890055B6A"
        }
      ]
    }
```

The changes are to (1) bring the domains/ranges of `entryCondition` up to those of `requires` and review what needs to be updated in the editor/data.

See also the CTDL Handbook [example under 2.2](http://credreg.net/ctdl/handbook#subConditions) for the use of `entryCondition`.
