### ISSUE TITLE
'Deprecation' of a CTDL term (consequence)

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#288]
On occasion, we will have the need to "deprecate" a CTDL term.  Deprecation in the CTDL context does not mean **removal** of a term or **forbidding** its use.  (in schema: vs:term_status "deprecated")

>Deprecation is the **discouragement** of use of some CTDL term as a result of it either being superseded or no longer considered best practice. A term is deprecated without completely removing it or **prohibiting** its use.  --Adapted from https://en.wikipedia.org/wiki/Deprecation

Thus, deprecated CTDL terms are clearly marked as such in status and their term URI's continue to resolve into perpetuity. This is akin to the schema.org notion of "the attic": 

>"The attic area is an archive area for terms which are no longer part of the core vocabulary or its extensions. Attic terms are preserved here to satisfy previous links to them."

**Comment by stuartasutton** [comment]
The range of term status you see out there include:

> experimental
proposed
active 
deprecated 
obsolete

...with the distinction between "deprecated" and "obsolete"  going from no longer encouraged to a determination that the term should no longer be used at all.

**Comment by siuc-nate** [comment]
Are there any terms to be deprecated currently, or is this just an informative issue?

**Comment by stuartasutton** [comment]
This is primarily informational since the Overview mentions deprecated as a status. 

However, in cleaning up the ad hoc identifier entity (`IdentifierValue`), I am going to propose two deprecations:

> `ceterms:IdentifierValueSet` (class)
> `ceterms:partofIdentifierValueSet` (property

We don't need the them to define as "aggerage" of the IDs.

However, for adhoc identifiers, we'd still need:

> `IdentifierValue`  (class) 
> `identifierValueCode` (property)

and the addition of

> `identifierType` (property)

See the Overview: 4.3.3. Other Identifiers and accompanying identifier description.
![fig 4 3 3a](https://cloud.githubusercontent.com/assets/2939046/22309001/3480f69e-e2fe-11e6-8895-488f7569497e.png)

**Comment by stuartasutton** [comment]
When a term has been deprecated and replaced, the deprecated terms needs to have a `schema:supersededBy` property to point to the replacement term.

**Comment by siuc-nate** [comment]
Closing this, as there are no actions to be taken and I believe we have a handle on superseding terms.
