### ISSUE TITLE
Property to relate (dependent) dual degrees

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#289]
Dependent dual degrees are two degrees that are tailored to go together--e.g., a Master of Architecture and a Master of Science in Civil Engineering. They are two degrees that are available in their specific forms **when coupled**. So, they are described in CTDL as two separate degrees related through some variant/subproperty of  `ceterms:requires` --perhaps `ceterms:dualDegree` or even `requiredDualDegree` or `dependentDualDegree`. We should avoid `dualCedential` because of its potential misuse for linking any two credentials that are somehow related...a muddy situation we do **not** want to create.

Here is a graphic illustrating such dependent dual degrees:

![fig 2 2e](https://cloud.githubusercontent.com/assets/2939046/22249792/46e8ce0c-e1f9-11e6-98d0-3f61d155b48b.png)

**Comment by siuc-nate** [comment]
I would want to avoid encoding the number of related entities in the name of the property - something like "requiredDegree" or "dependentDegree" would be preferable, I'd think (though perhaps it's not realistic to imagine 3 or more degrees having this kind of connection).

Is this kind of connection exclusive to degrees or could it be found elsewhere in our credential subtypes?

**Comment by stuartasutton** [comment]
Nate, that invites all kinds of misuse of a property that is indeed quite specific. E.g., a `MasterDegree` could be construed as having a `dependentDegree` or `requiredDegree` of a `BachelorDegree`... to identify just one such inappropriate use. 

It needs a very specific definition that limits it use to solving the identified problem of a **co-requisite degree**; so, why invite relatively unlimited use. Perhaps `coRequisiteDegree`

DEFINITION:
> A co-requisite degree at the same level tailored to be earned simultaneously with the subject degree.

COMMENT:
> Includes dual (double) degrees that cannot be earned independent of each other.

**Comment by siuc-nate** [comment]
That sounds better to me.  Is this something we still want to do right now, given our pending discussions of refinements to ConditionProfile, requirements, etc.?

**Comment by stuartasutton** [comment]
I see no reason to wait for discussions with issues we have already identified. Reading back through this thread, we could define a `coRequisiteResource` defined as a resource that must be completed at the same time as the resource being described. Then, in a particular instance, the nature of the thing could be determined by the particular range class; e.g. a dual degree would be something like this
```
BachelorDegreeA==coRequisiteResource==>BachelorDegreeB. 
```
Of course, one could look at the possibility of the same structure with `prerequisite`...

**Comment by stuartasutton** [comment]
...or, simply `corequisite`

**Comment by siuc-nate** [comment]
I like the notion of corequisite, so long as that is distinct enough that we won't need to use the same term for something else - e.g. corequisiteEntry, corequisiteCompletion, etc.  It might be better to try to use two-word terms simply to give them a bit of inherent pseudo-namespacing.

Anyway though, the only other thing that sticks out in my mind is the specification of "at the same time" - this could be interpreted too strictly.  Maybe something a bit more lax, like "a resource that must be [some word for "worked on" or "progressed in"] concurrently with the resource being described"?  Or were you intentionally saying that corequisite resources must be attained simultaneously?

Maybe I'm overthinking these things.  I do like corequisite as a starting point though.

**Comment by stuartasutton** [comment]
We should craft the definition of "dual degrees" to require that the resources are not just any two degrees, but are mutually required. While they have a degree of simultaneity (i.e., admitted into both at the same time), their completion may not be exactly the same. The "mutually required" means that the relationship is based on a formal arrangements that frequently involve the acceptance of some credit hours from one program fulfilling requirements in the other. 

The notion of "dual degrees" does not imply completion of any set of degrees. For example, I hold 3 masters degrees--one on law, one in library and informatiton science, and a third in Theatrical Design. Even if I had completed two of them at the same time, they would not be considered dual degrees.

See: https://en.wikipedia.org/wiki/Double_degree

**Comment by siuc-nate** [comment]
Per our 4/4/2017 call:

**URI:** ceterms:corequisite
**Definition:** A resource that must be pursued concurrently with the resource being described.
**Comment:** Includes dual (double) degrees that cannot be earned independent of each other.
**Domain:** ceterms:Credential, ceterms:AssessmentProfile, ceterms:LearningOpportunityProfile
**Range:** ceterms:ConditionProfile

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in history tracking.
