### ISSUE TITLE
Refine handling of ConditionProfile and requirements-related properties

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#309]
Use/Refer to https://github.com/CredentialTransparencyInitiative/vocabularies/projects/2 

Over the last few weeks we have discussed a number of changes having to do with defining requirements and our use of ConditionProfile.  I feel these discussions, while valuable, are somewhat disjointed and lack the context of each other.

This issue is intended to help us all get on the same page about exactly how we're handling ConditionProfile and the requires, alternateRequirements, entryConditions, etc., properties.

(Potentially) relevant issues:
- #188 "Consider adding CredentialAlignmentObject to range of requires & recommends"
- #297 "Add an alternativeCondition property"
- #275 "Distinguishing between 'entry' and 'exit' conditions"
- #296 "Need an "entryCondition" like property"
- #289 "Property to relate (dependent) dual degrees"
- #247 "Consider a ConditionManifest Class"
- #295 "Need a "submissionOf" property for required submissions"
- #181 "ConditionProfile: Add CostProfile"
- #121 "Consider dropping TaskProfile"

In essence, I would like to gather all of our new properties and decisions in regards to handling requirements into this thread.

My current understanding of our intent is as follows:

- The "requires" property simply points to a requirement (e.g. an AssessmentProfile) or to a set of requirements (e.g. a ConditionProfile)
- The "alternativeCondition" property points to a set of requirements in such a way that the pursuer only needs to fulfill one entity pointed to by an alternativeCondition in order to progress, and this is how multiple routes to obtain a credential can be defined
- "entryConditions" is a special case that applies to learning opportunities and indicates the requirements to begin participating in a learning opportunity (presumably there would be a second ConditionProfile pointed to by "requires" that indicates the requirements for completing the opportunity, although it may be useful to explicitly indicate these via an "exitConditions" property)
- ConditionManifest is a concept that is intended to define a common set of requirements at the organization level in a way that can be referenced by other requirements as a base set
- The combination of "estimatedCost", "condition", "alternativeCondition", "submissionOf", and probably "description" enables defining enough information to allow us to drop TaskProfile
- A "coRequisiteDegree" property will be added to the Degree class (and its subclasses) to handle a special case where two or more degrees must be earned simultaneously in order to earn any of them. This will not directly involve a ConditionProfile and instead would be a direct relationship between the Degrees involved

I'm hoping we can get on the same page with all of this.

**Comment by stuartasutton** [comment]
Nate, I am a bit adverse to putting all comments around conditions/requires in one github issue like this. As this issue grows with discussion around numerous separate things, it will be unmanagable and related comments won't collocate and cannot be individually handled. Wouldn't it be more efficient to continue to keep issues separate and to collocate them through a github *Condition Profile* project. It is possible to create such a project and then link the separate issues to it; see https://help.github.com/articles/adding-issues-and-pull-requests-to-a-project/. Then we have the benefit of tracking (opening/closing/labeling) distinct issues while still collocating all of those issues under a project.

**Comment by siuc-nate** [comment]
That might work - when I get a chance I'll look into it deeper.  My main goal in trying to consolidate the issues was to make sure that each issue wasn't existing in a vacuum (for instance, the handling of "requires" vs "additionalCondition" vs "alternativeCondition" vs "entryCondition" vs "coRequisiteDegree" all have something to do with each other, but their respective issues did not seem to take one another into account).

**Comment by stuartasutton** [comment]
Nate, no questioning of your rationale. We just need the optimal process that accomplishes the desired outcome while keeping as much of github issue functionality available.

**Comment by jkitchensSIUC** [comment]
Also see #247 Consider New ConditionManifest.

**Comment by siuc-nate** [comment]
Except for the TaskProfile issue, the issues above have been taken care of through the April CTDL release.
