### ISSUE TITLE
Consider for Credentialing Action a Status Property 

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#311]
For example: Accredited, Pre-accredited, Approved, Recognized for QA Organizations.

As part of the process of working with QA Orgs, Emilie and Scarlett will maintain a Google Sheet to identify the statuses used along with definitions.

**Comment by siuc-nate** [comment]
Is this covered by http://credreg.net/Ctdl/terms/actionStatusType ?

**Comment by stuartasutton** [comment]
We need to make sure we are distinguishing between the **kind of action** and the **status of of an action**--e.g., an `AccreditAction` with a "Probationary" status. Actions types (classes) include `AccreditAction`, `ApproveAction`, `RecognizeAction` (we don't currently have a `PreAccreditAction`?? (see: https://ope.ed.gov/accreditation/Glossary.aspx)). It seems to me that those listed by you Jeanne are kinds of actions that are (or should be) covered in the subclasses. 

You are correct, Nate, we do have the http://credreg.net/Ctdl/terms/actionStatusType controlled vocabulary for statuses of existing `CredentialAction` subclasses. So far, it only has the 4 concepts defined by schema.org. That's what Emile and Scarlett should be looking for and inventorying for review.

We should likely be watching this [action status vocabulary](http://credreg.net/Ctdl/terms/actionStatusType) in parallel with the [credential status vocabulary](http://credreg.net/Ctdl/terms/actionStatusType#ActionStatus). They are nor exactly unrelated.

**Comment by siuc-nate** [comment]
See #328
