### ISSUE TITLE
Recognizes/RecognizedBy/RecognizedIn and Endorses/EndorsedBy/EndorsedIn

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#312]
This Google sheet tracked QA related properties https://docs.google.com/document/d/13td5-K4uYrfInkX2mpxeO-XpN9mFIraoe8NSciv7f58/edit?usp=sharing

Consider creating Subproperties of the following.  This needs to be based on feedback from the QA Advisory Group. 

These are external/third party assertions about a credential, learning opportunity or assessment.

[ceterms:AccreditAction](http://credreg.net/ctdl/terms#AccreditAction)
[ceterms:accredits](http://credreg.net/ctdl/terms#accredits)
[ceterms:accreditedBy](http://credreg.net/ctdl/terms#accreditedBy)
[ceterms:accreditedIn](http://credreg.net/ctdl/terms#accreditedIn)
[serviceType:AccreditService](http://credreg.net/ctdl/terms#AccreditService)

[ceterms:RecognizeAction](http://credreg.net/ctdl/terms#RecognizeAction)
[ceterms:recognizes](http://credreg.net/ctdl/terms#recognizes)
[ceterms:recognizedBy](http://credreg.net/ctdl/terms#recognizedBy)
[ceterms:recognizedIn](http://credreg.net/ctdl/terms#recognizedIn)
[serviceType:RecognizeService](http://credreg.net/ctdl/terms#RecognizeService)

[ceterms:ApproveAction](http://credreg.net/ctdl/terms#ApproveAction
[ceterms:approves](http://credreg.net/ctdl/terms#approves)
[ceterms:approvedBy](http://credreg.net/ctdl/terms#approvedBy)
[ceterms:approvedIn](http://credreg.net/ctdl/terms#approvedIn)
[serviceType:ApproveService](http://credreg.net/ctdl/terms#ApproveService)

[ceterms:RegulateAction](http://credreg.net/ctdl/terms#RegulateAction)
[ceterms:regulates](http://credreg.net/ctdl/terms#regulates)
[ceterms:regulatedBy](http://credreg.net/ctdl/terms#regulatedBy)
[ceterms:regulatedIn](http://credreg.net/ctdl/terms#regulatedIn)
[serviceType:RegulateService](http://credreg.net/ctdl/terms#RegulateService)

These terms will be given to the QA Advisory Group, with the question "What is the distinguishing characteristic of each type of third-party assertion?"

From Oxford English Dictionary:

- endorsement - an act of giving one's public approval or support to someone or something.
- recognize - 1. identify from knowledge of appearance or character 2. acknowledge the existence, validity, or legality of
- acknowledge - recognize the fact or importance or quality of, •accept the validity or legitimacy of

to include: Acknowledge (e.g. we acknowledge the resources meets some criteria)
ceterms:AcknowledgeAction
ceterms:acknowledges
ceterms:acknowledgedBy
ceterms:acknowledgedIn
serviceType:AcknowledgeService

to include: Endorse (e.g. we endorse the resource)
ceterms:EndorseAction
ceterms:endorses
ceterms:endorsedBy
ceterms:endorsedIn
serviceType:EndorseService

**Comment by jkitchensSIUC** [comment]
From Roy Swift on June 26, 2017:

Endorsement – Giving a formal approval or strong recommendation to something in a public manner and often requiring a signature from an authority.

Recognition – An acknowledgement, appreciation, or acclaim or indicating a validity of an achievement, service,  or ability.

**Comment by stuartasutton** [comment]
As verbs:

>**endorses:** A formal approval or strong recommendation to something in a public manner and often requiring a signature from an authority.
**endorsedBy:** An agent providing a formal approval or strong recommendation to something in a public manner often requiring a signature from an authority.

and (term revisions)...

>**recognizes:** An acknowledgement, appreciation, or acclaim or indicating a validity of an achievement, service, or ability.
**recognizedBy:** An agent providing an acknowledgement, appreciation, or acclaim or indicating a validity of an achievement, service, or ability.

**Comment by siuc-nate** [comment]
@stuartasutton Would we want to tweak those to use the "agent being described"/"resource being referenced" style of writing we use all over the rest of CTDL?

Also, does this come down to modifying the definitions of recognizes/recognizedBy, and creating new "endorses" and "endorsedBy" properties?  What about "endorsesIn", "EndorseService", and "EndorseAction"?
