### ISSUE TITLE
Revising comments to definitions for LearningOpportunity and LearningOpportunityProfile

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#317]
I remain uncomfortable that `entryCondition` does not include a domain of `credential` but only `Assessment` and `LearningOpportunity`. This "unease" could probably be addressed by refining the definitions or comments for LearningOpportunity and LearningOpportunityProfile to more explicitly include things like completion of an apprenticeship. E.g., in my late teens, I completed an apprenticeship as a grocery clerk through UFCW and my "award" was journeyman status for being over 18 and having completed a year's worth of hours as in apprentice status.  Given `entryConditions` current definition, that apprenticeship condition has to be either an `Assessment` or a `LearningOpportunity`.  

`LearningOpportunity` is defined as:

> **Definition:** Structured and unstructured learning and development opportunities based in direct experience, formal and informal study, observation, and involvement in discourse and practice.

`LearningOpportunityProfile` is defined as:

> **Definition:** A resource describing a learning opportunity.
>**Comment:** Educational opportunities include required and optional programs, courses of study, and other structured experiences intended to serve as educational or training events.

While we may infer that an apprenticeship is encompassed by `LearningOpportunity` and `LearningOpportunityProfile`, lots of people trying to create data will toally miss it. 

Can this be made more explicit in definitions or comments? E.g., qualifying "direct experience" and "structured experiences"?

**Comment by siuc-nate** [comment]
I would support expanding the comment (and perhaps definition).  Perhaps a comment like:

"Examples of learning opportunities include education and training programs and classes, courses of study, apprenticeship or work experience programs, or other structured experiences intended to serve as educational or training events."

**Comment by stuartasutton** [comment]
I like it. 

Then, if they still don't get learning opportunity is inclusive of apprenticeship, they are just not reading. AND, it would be good for me to develop an example that has an apprenticeship for the Guide that makes it clear.

**Comment by siuc-nate** [comment]
Action to be taken:
> **ADD Triple:**
> **Subject:** ceterms:LearningOpportunity
> **Predicate:** dcterms:description
> **Object:** Examples of learning opportunities include education and training programs and classes, courses of study, apprenticeship or work experience programs, or other structured experiences intended to serve as educational or training events.

**Comment by siuc-nate** [comment]
This change has been made in pending and recorded in history tracking.
