### ISSUE TITLE
Consider stating who can create a CredentialingAction

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#321]
Currently, the defintion of a [`CredentialingAction`](http://purl.org/ctdl/terms/CredentialingAction) is defined as follows:

> An action taken by an agent affecting the status of an object resource.

I suggest that we add a comment that states:

> Since an instance of `CredentialingAction` is a claim that a certain agent has taken the action being described, creation of such a `CredentialingAction` should be reserved to the agent of that action. 

There are abundant properties for resources in the CTDL to make such assertions regarding that action in their descriptions (e.g., "Organization A has been [`accreditedBy`](http://purl.org/ctdl/terms/accreditedBy) Organization B."). While Organization A can make that assertion, only Organization B should create an AccreditAction stating that it has indeed accredited Organization A. Ultimately, such assertions may even be verifiable (signed).

If such is the case, some variation of the last paragraph should be added to the Guide's section on credentialing actions.

**Comment by siuc-nate** [comment]
See issue #330
