### ISSUE TITLE
Competency references from ConditionProfile, AssessmentProfile & LearningOpportunityProfile

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#322]
Currently `ConditionProfile`, `AssessmentProfile`, and `LearningOpportunityProfile `have a `targetCompetency` property. So all work well in terms of Linked Data references to competencies from these three entity types. But, the means to describe aspects of the referenced concepts directly without `CredentialAlignmentObject` in range is not possible.

So, should we add `CredentialAlignmentObject` to the range of these three profiles?

**Comment by siuc-nate** [comment]
It's not clear what the intent of this issue is - the profiles are classes, and thus cannot have a range.  The profiles also already have a targetCompetency property.  When you say "referenced concepts", do you mean the competencies themselves?

**Comment by stuartasutton** [comment]
Sorry, I was far from clear. The point is inconsistent ranges with
targetCompetency and targetCompetencyFramework--targetCompetency has
CredentialAlignmentObject as range and targetCompetencyFramework has
CompetencyFramework as range. In the former, there is no means of directly
referencing a competency except through an CredentialAlignentObject while
the latter has only the means to directly reference a framework but no
means to describe it as provided by the CredentialAlignmentObject. Should
they a consistent range pattern?

**Comment by siuc-nate** [comment]
Oh, I see. My first instinct is to say we should use AlignmentObject for both, but in the case of frameworks, would we really just be trading (omitting other properties for brevity):

{
   targetCompetencyFramework: "http://someframework.com/123"
}

for

{
   targetCompetencyFramework: {
      framework: "http://someframework.com/123"
   }
}

Or would you leverage the name and description fields here too?

Actually, come to think of it, if you're targeting the framework, would the framework URL go in the framework property or the targetURL property?

**Comment by stuartasutton** [comment]
Well, in truth, you have the **exact same issue** with `Competency` as you do above with `ComptencyFramework`.  In a purely RDF sense, If I want to simply identify the competency or the competency framework, the first is preferred; i.e., 

```
{
targetCompetencyFramework: "http://someframework.com/123"
}
```
...and

```
{
targetCompetency: "http://someframework.com/xyz"
}
```
But, if instead of resolving and then including additional information inthe manner of RDF, we want to information directly (e.g., names of things), then using `CredentialAlignmentObject`is necessary for:

```
{
targetCompetencyFramework: "http://someframework.com/123",
frameworkName: "Best Competencies Ever"
}
```
...and

```
{
targetCompetency: "http://someframework.com/xyz"
targetNodeDescription: "Jonny can tie his shoes in under 5 seconds."
}

**Comment by stuartasutton** [comment]
Nate, you say: "Actually, come to think of it, if you're targeting the framework, would the framework URL go in the framework property or the targetURL property?"

There is no such thing as `targetURL` on `CredentialAlignmentObject`. You have `targetNode` and `framework`.

**Comment by siuc-nate** [comment]
Does this come down to the following?:

ceterms:targetCompetencyFramework
add range: ceterms:CredentialAlignmentObject

**Comment by siuc-nate** [comment]
This change has been made in pending and recorded in history tracking.
