### ISSUE TITLE
Determine whether to eliminate or refine ceterms:CredentialPerson 

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#324]
The CTDL Agent superclass http://credreg.net/ctdl/terms#Agent includes the following subclasses:

ceterms:CredentialOrganization
ceterms:CredentialPerson
ceterms:QACredentialOrganization

http://credreg.net/ctdl/pending#CredentialPerson is currently considered to be "Unstable."   
UnstableThe term is under development and not yet recommended for use. Unstable terms are subject to removal.

ceterms:CredentialPerson Definition: An person who plays one or more key roles in the lifecycle of a credential. 

The CTDL team is seeking feedback to determine whether the CTDL needs a CredentialPerson class. The CredentialPerson class was added early on at the suggestion of the TAC; however, the team is struggling a bit with whether persons are actually necessary and within the scope as a credentialing agent. 

In thinking about this, please remember that person-as-recipient of a credential is absolutely out of scope for CTDL. We leave expressions of person-as-recipient to our colleagues in the badging community and those dealing with verifiable claims of credentials earned.

In the lifecycle of a credential including creation, offering and administration; (2) quality assurance, or (3) provision of related assessments or learning opportunities the following questions are included with a survey to be disseminated to all TAC members and all quality assurance and credentialing partners.

Survey URL: https://www.surveymonkey.com/r/credentialperson

The survey includes the following questions:

- Quality assurance for a credential could be issued by a person (rather than an organization to where the person may be affiliated)?
- Credentials could be created by a person (rather than an organization to where the person may be affiliated)?
- Credentials could be issued by a person (rather than an organization to where the person may be affiliated)?
- Learning opportunities for the purpose of earning a credential could be offered by a person (rather than an organization to where the person may be affiliated)?
- Assessments for the purpose of earning a credential could be offered by a person (rather than an organization to where the person may be affiliated)?

**Comment by stuartasutton** [comment]
It is quite clear that there is no consensus for removing `CredentialPerson`. 

In addition to refining the properties that 'fit' person as opposed to organization, we need to refine the definition and comment to make clear that a `CredentialPerson` is the ***primary agent*** in the provision of resources or services in the lifecycle of a related credential. This eliminates persons who "work" for organizations and provide services on their behalf, regardless of fame or reputation. If identifying such persons is to be a function of the CTDL, then we should have appropriate properties for doing so on Credential, Learning Opportunity Profile etc.

**Comment by siuc-nate** [comment]
I have created a document to start comparing properties of Person with properties of Organization:
https://docs.google.com/spreadsheets/d/1D_APV3M4BPzl025FVZMu0ctMBAeWnleDRSUxN-q3sLc/edit#gid=0

**Comment by siuc-nate** [comment]
Per our 3/28/2017 discussion:
We have identified the properties to be added, removed, or kept in this spreadsheet:
https://docs.google.com/spreadsheets/d/1D_APV3M4BPzl025FVZMu0ctMBAeWnleDRSUxN-q3sLc/edit#gid=0  

Actions:
---
ceterms:CredentialPerson is to be **removed** from the **rdfs:range** predicate of the following subjects:
- ceterms:accreditedBy
- ceterms:address
- ceterms:agentType
- ceterms:alternativeIdentifier
- ceterms:credentialingAction
- ceterms:duns
- ceterms:fein
- ceterms:foundingDate
- ceterms:hasVerificationService
- ceterms:jurisdiction
- ceterms:missionAndGoalsStatement
- ceterms:missionAndGoalsStatementDescription
- ceterms:naics
- ceterms:regulatedBy

---
ceterms:CredentialPerson is to be **added** to the **rdfs:range** predicate of the following subjects:
- ceterms:approvedIn
- ceterms:image
- ceterms:socialMedia
- ceterms:subjectWebpage
- ceterms:targetContactPoint

---
ceterms:CredentialPerson itself will have its **vs:status** predicate changed from **vs:unstable** to **vs:pending**

---
The CredentialPerson-related property, ceterms:trainingOffered, will have its **vs:status** predicate changed from **vs:stable** to **vs:deprecated**

---
Therefore, the resultant list of properties that have a range that includes ceterms:CredentialPerson will be:

- ceterms:approvedBy
- ceterms:approvedIn
- ceterms:approves
- ceterms:description
- ceterms:email
- ceterms:image
- ceterms:keyword
- ceterms:offers
- ceterms:owns
- ceterms:recognizedBy
- ceterms:recognizedIn
- ceterms:recognizes
- ceterms:renews
- ceterms:revokes
- ceterms:sameAs
- ceterms:serviceType
- ceterms:socialMedia
- ceterms:subjectWebpage
- ceterms:targetContactPoint
- ceterms:trainingOffered
- ceterms:worksFor
- ceterms:affiliation
- ceterms:familyName
- ceterms:givenName
- ceterms:honorificSuffix

**Comment by siuc-nate** [comment]
The changes listed above have been made in pending CTDL and noted in the history tracking.
http://credreg.net/ctdl/pending#CredentialPerson
