### ISSUE TITLE
Showing "Pending" on live terms view

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#325]
Currently, http://www.credreg.net/ctdl/terms has the "Pending" tab. Should it? Doesn't this encourage general people using the vocabulary to perhaps use terms that are not ready for prime-time? Is this a tab intended for people watching CTDL development...e.g., upcoming releases?

**Comment by jkitchensSIUC** [comment]
Pending should not show on the CTDL only on Pending.  It will be removed.
