### ISSUE TITLE
Changes to range of minimumDuration & maximumDuration

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#326]
We have an error (pointed out by the CEDS team) with the `ceterms:minimumDuration` and `ceterms:maximumDuration` properties that have a currently declared range of `xsd:dateTime` as defined by ISO 8601. The range for both properties should be `xsd:duration`.

The xsd:duration value takes the form PnYnMnDTnHnMnS. 
>For example, "P3Y6M4DT12H30M5S" represents a duration of "three years, six months, four days, twelve hours, thirty minutes, and five seconds". [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601#Durations)

**Comment by siuc-nate** [comment]
Given the nature of the error, is this something we can correct immediately, or will it need to be handled in the next release?

**Comment by stuartasutton** [comment]
Well, we might mark it as unstable in the current release and make the
change in pending.

**Comment by siuc-nate** [comment]
This issue was posted to our google group:
https://groups.google.com/forum/#!topic/cti-technical-committee/J5IvSbZ240o

If we have not heard any objections by Friday (March 3rd), we will make this change to the live release.

**Comment by siuc-nate** [comment]
I have made the changes in live CTDL.
