### ISSUE TITLE
Add a property to  ceterms:CredentialingAction to point to verification of that action

### ISSUE THREAD

**Issue by mparsons1953** [CredentialEngine/vocabularies#329]
We need to be able to go from aceterms:CredentialingAction (http://credreg.net/ctdl/terms#CredentialingAction) to some resource that verifies the authenticity and status of that action.  

For example, we need to be able to get from a CredentialAction metadata document to a page like http://hlcommission.org/component/directory/?Action=ShowBasic&Itemid=&instid=50&lang=en

**Comment by siuc-nate** [comment]
Per our discussion on 2/28/2017:

It's fine to add a property for this.  Should there be additional domains for such a property?

**Comment by siuc-nate** [comment]
Proposal (I'm not sure if the usage note is too verbose/necessary):

URI: ceterms:actionVerification
Label: Action Verification
Definition: A resource that verifies the action being described.
Domain: ceterms:CredentialingAction (and its subclasses)
Range: xsd:anyURI
Usage Note: This is a resource that verifies the status of this action and is particular to this specific action. It is not a directory of such resources or a description of how such verification might generically be characterized.

**Comment by stuartasutton** [comment]
The usage note is not too long.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
