### ISSUE TITLE
Reserve creation of a CredentialingAction to the agent of the action

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#330]
We should add a comment to the definition of `CredentialingAction` and all of its subclasses that the creator role of an instance of a `CredentialingAction` should be **reserved to the agent of that action**. 

So, for example, where Org A accredits Org B (or some program of Org B), an instance of AccreditAction should be created by Org A and not Org B. Org B has sufficient means to claim that it or its program has been `accreditedBy` Org A. 

I suggest the following comment addition to `CredentialingAction` and its subclasses:

> Since a CredentialingAction is a claim that some QACredentialOrganization has taken a verifiable action, creation of instances of CredentialingAction and its subclasses should be reserved to the agent of those actions. A beneficiary organization of such an action has the means to reference a CredentialingAction's agent through properties such as accreditedBy.

Alternatively:

> Since an instance of `CredentialingAction` is a claim that a certain agent has taken the action being described, creation of such a `CredentialingAction` should be reserved to the agent of that action.

**Comment by siuc-nate** [comment]
See #321

**Comment by siuc-nate** [comment]
Action to be taken:
**Add (triple):**
> **Subject:** ceterms:CredentialingAction
> **Predicate:** rdfs:Comment
> **Object:** Since an instance of CredentialingAction is a claim that a certain agent has taken the action being described, creation of such a CredentialingAction should be reserved to the agent of that action.

**Comment by siuc-nate** [comment]
These changes have been made in pending and noted in the history tracking.
