### ISSUE TITLE
Correct typo in usage note for ceterms:administrationProcess

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#333]
The usage note for administrationProcess is missing an "and" between "lifecycle of a credential" and "the proctoring of assessments".  I have also tweaked the wording to make it read more smoothly.

Proposed action to be taken:

**Remove**
> **Subject:** ceterms:administrationProcess
> **Predicate:** vann:usageNote
> **Object:** "Processes administered include, but are not limited to, execution of events and processes in the lifecycle of a credential the proctoring of assessments."

**Add**
> **Subject:** ceterms:administrationProcess
> **Predicate:** vann:usageNote
> **Object:** "Examples of processes administered include the execution of events and processes in the lifecycle of a credential, and the proctoring of assessments."

**Comment by stuartasutton** [comment]
This would be consider a trivial correction. Go ahead.

**Comment by siuc-nate** [comment]
I have made this change in pending CTDL and noted it in the history tracking.
