### ISSUE TITLE
Replace claimType:Verifiedclaim with claimType:VerifiedClaim

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#335]
In order to be consistent with the other terms in the ClaimType ( http://credreg.net/ctdl/terms/ClaimType ) vocabulary (and because it was probably an error to begin with), I propose:

1) Deprecate claimType:Verifiedclaim
2) Create claimType:VerifiedClaim (which is otherwise identical)
3) Mark claimType:Verifiedclaim as superseded by claimType:VerifiedClaim

**Comment by stuartasutton** [comment]
Yes, this is an error (not bug). I agree with the proposed actions.

**Comment by siuc-nate** [comment]
Action to be taken:

- Deprecate ceterms:Verifiedclaim

- Create ceterms:VerifiedClaim
URI: ceterms:VerifiedClaim
Label: Verified Claim
Definition: Verifiable representation of the credential holder's credential that is controlled by the credentialing organization.
In Scheme: ceterms:ClaimType

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
