### ISSUE TITLE
Add claimType:QualityAssuranceClaim

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#336]
During our discussions of CredentialingAction, we proposed adding the following term to the ClaimType ( http://credreg.net/ctdl/terms/ClaimType ) vocabulary.  

The Claim Types  are: 
- claimType:BadgeClaim
- claimType:TranscriptClaim
- claimType:Verifiedclaim

In lieu of using claimType:Verifiedclaim for Quality Assurance claims, the proposal is to inlcude the concept  claimType:QualityAssuranceClaim:

Proposal:
**URI:** claimType:QualityAssuranceClaim
**Label:** Quality Assurance Claim
**Definition:** Verifiable representation of quality assurance that is controlled by the quality assurance organization.
**In Scheme:** ceterms:ClaimType

**Comment by stuartasutton** [comment]
Looks OK to me.

**Comment by siuc-nate** [comment]
Action to be taken:
**URI:** claimType:QualityAssuranceClaim
**Label:** Quality Assurance Claim
**Definition:** Verifiable representation of quality assurance that is controlled by the quality assurance organization.
**In Scheme:** ceterms:ClaimType

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
