### ISSUE TITLE
Add xsd:anyURI to range of ceterms:sameAs in live CTDL release

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#340]
For whatever reason, ceterms:sameAs has _no_ range defined:
http://credreg.net/ctdl/terms/sameAs

I propose:

**Add:**
> **Subject:** ceterms:sameAs
> **Predicate:** rdfs:range
> **Object:** xsd:anyURI

**Comment by siuc-nate** [comment]
Note: This problem presents an issue for validating credentials in the CER, so I recommend we expedite it in a fashion similar to how we fixed the range of the duration properties ( #326 )

**Comment by stuartasutton** [comment]
Nate, that looks OK to me. Strange that it didn't have a range already...I'm fairly confident that it did have one.

**Comment by siuc-nate** [comment]
I have made this change in pending CTDL and noted it in the history tracking.

However, that still leaves the matter of this being a flaw in the current, live release of CTDL.  Is there any problem with adding it now?

**Comment by siuc-nate** [comment]
Per our 3/14/2017 conversation, we will hold off on taking action on this for now, pending action in schema.org related to the sameAs property.

**Comment by siuc-nate** [comment]
Closing this since this change went live with the April release.
