### ISSUE TITLE
Clarify distinction between agentPurpose/agentPurposeDescription and missionAndGoalsStatement/missionAndGoalsStatementDescription

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#341]
Currently we have two pairs of properties that seem to have a high degree of overlap:

[ceterms:agentPurpose](http://credreg.net/ctdl/terms/agentPurpose)
**Range:** xsd:anyURI
**Definition:** A resource that describes the agent's primary purpose.
**Comment:** QACredentialOrganization Examples include: assisting employers seeking competent practitioners; enabling tuition aid; ensuring credential issuers meet standards for enter occupations; enabling eligibility for financial aid; determining if government regulations are followed, and promoting professional advancement.

[ceterms:agentPurposeDescription](http://credreg.net/ctdl/terms/agentPurposeDescription)
**Range:** rdfs:Literal
**Definition:** A description of the primary purpose of the agent being referenced.
**Comment:** QACredentialOrganization Examples include: assisting employers seeking competent practitioners; enabling tuition aid; ensuring credential issuers meet standards for enter occupations; enabling eligibility for financial aid; determining if government regulations are followed, and promoting professional advancement.

and

[ceterms:missionAndGoalsStatement](http://credreg.net/ctdl/terms/missionAndGoalsStatement)
**Range:** xsd:anyURI
**Definition:** A resource that defines or explains the mission and goals statement of the resource being described.

[ceterms:missionAndGoalsStatementDescription](http://credreg.net/ctdl/terms/missionAndGoalsStatementDescription)
**Range:** rdfs:Literal
**Definition:** The mission and goals statement of the described agent.

---

What is the difference between:
"A resource that describes the agent's primary purpose."
and
"A resource that defines or explains the mission and goals statement of the resource being described."

Additionally, what is the difference between:
"A description of the primary purpose of the agent being referenced."
and
"The mission and goals statement of the described agent."

Or, more simply, what is the difference between:
"primary purpose"
and
"mission and goals"

Do we really need both pairs of properties?

**Comment by stuartasutton** [comment]
I understand, @siuc-nate, that these feel similar. Historically, the `agentPurpose` and `agentPurposeDescription` came first and the mission statement stuff was added because the QA folks wanted it. Functionally, their content ***could*** be quite distinct in terms of precision. Mission statement are generally idealistic and somewhat abstract while the purpose data ***should*** be more precise and grounded. 

But, you are right that they are otherwise similar and people are likely to plop the same information into both.

**Comment by siuc-nate** [comment]
Then perhaps we should strongly clarify the definitions - as is, I don't think they would pass our own basic test of "what is the [significant] differentiating factor that justifies the existence of this property?" that we have applied in the past.

**Comment by stuartasutton** [comment]
One way would be to deprecate `ceterms:missionAndGoalsStatementDescription` so they can only point to a mission statement page. Then the properties focusing on "purpose" carry the load and are framed very explicitly.

**Comment by siuc-nate** [comment]
Per our 3/14/2017 conversation:

- Deprecate ceterms:agentPurpose
- Deprecate ceterms:missionAndGoalsStatementDescription
- Revise the comment for ceterms:agentPurposeDescription to: "Short phrases denoting purpose such as those found on the "about" page of a website."

**Comment by siuc-nate** [comment]
Actions:

Remove:
URI: ceterms:agentPurpose
Predicate: dcterms:description
Object: "QACredentialOrganization Examples include: assisting employers seeking competent practitioners; enabling tuition aid; ensuring credential issuers meet standards for enter occupations; enabling eligibility for financial aid; determining if government regulations are followed, and promoting professional advancement."

Add:
URI: ceterms:agentPurpose
Predicate: dcterms:description
Object: "Examples include the "about" page of a website."

Remove:
URI: ceterms:agentPurposeDescription
Predicate: dcterms:description
Object: "QACredentialOrganization Examples include: assisting employers seeking competent practitioners; enabling tuition aid; ensuring credential issuers meet standards for enter occupations; enabling eligibility for financial aid; determining if government regulations are followed, and promoting professional advancement."

Add:
URI: ceterms:agentPurposeDescription
Predicate: dcterms:description
Object: "Short phrases denoting purpose such as those found on the "about" page of a website."

These changes have been made in pending CTDL and noted in the history tracking.
