### ISSUE TITLE
Remove schema:Email from range of ceterms:email

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#342]
http://schema.org/Email does not exist, but it is in range of http://credreg.net/ctdl/terms/email. Note that http://schema.org/email _does_ exist, and is already marked as an equivalent property.

Proposal:
**Remove:**
> **Subject:** ceterms:email
> **Predicate:** rdfs:range
> **Object:** schema:Email

**Comment by stuartasutton** [comment]
Yes, an error...should be corrected as suggested.

**Comment by siuc-nate** [comment]
I have made this change in pending CTDL and noted it in history tracking.
