### ISSUE TITLE
Fix range of ceterms:partOfIdentifierValueSet

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#343]
http://credreg.net/ctdl/terms/partOfIdentifierValueSet
The range incorrectly has:
ceterms:IdentifierVaueSet

It should be:
ceterms:IdentifierValueSet

Even though the property is deprecated, the typo creates a problem with generating validation and schema documents.  @stuartasutton is this something that can be corrected prior to the next release?

**Comment by siuc-nate** [comment]
Actually, since the term is deprecated, do we need to include it in validation?

**Comment by stuartasutton** [comment]
Yes, go ahead and correct.

**Comment by stuartasutton** [comment]
Yes, since deprecate does not mean remove. So there may be data that has used it that should not be flagged as invalid.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
