### ISSUE TITLE
Determine minimum expected data/required properties

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#344]
See https://github.com/CredentialEngine/CredentialRegistry/issues/5

We need to determine which properties should be required to have a minimal CTDL document for as many classes as it makes sense to have required properties for.  This is primarily for the sake of validation.

**Comment by stuartasutton** [comment]
Putting together a subgroup from the TAC membership to tackle a proposed "thin" profile for further discussion has been raised with the TAC. We just need to move on it if we are confident that we have everything they need already in the CTDL.

On our own, we might put together a short list of people we might like to see on that subgroup so we can coax.

**Comment by siuc-nate** [comment]
I have created a spreadsheet to help us work through the required properties for our main classes:
https://docs.google.com/spreadsheets/d/1rpRU8vChloTY5ggMD5vouYI71n5BBjTpmRiAZImL3Lg/edit#gid=0

I have taken a very minimalist approach here; we may want to recommend more properties.

**Comment by jkitchensSIUC** [comment]
A survey for feedback on required and recommended data for the registry is going out to all advisory groups by June 26th.  A PDF of the online survey is here https://drive.google.com/file/d/0B1uSTaYpjhXJNk83U3p1TVdJVzA/view?usp=sharing

**Comment by leolara** [comment]
@jkitchensSIUC should I be assigned to this? It seems a bit out of my scope, or do I misunderstand something?

**Comment by siuc-nate** [comment]
@leolara We wanted to keep you in the loop on this since there will be an impact on the validation in the Registry.  We got our survey back from our advisory groups and will be acting on it soon.

**Comment by cwd-mparsons** [comment]
@stuartasutton @jkitchensSIUC @siuc-nate 
The manifests were not part of the discussions on minimum data. 
Shouldn't there be a policy for minimum required data for the cost and condition manifests, with at least:
- Name
- Description
- Subject webpage (Cost details for Cost manifest)
- CTID

**As well**
Can a condition manifest exist without at least one condition profile, such as required?
Can a cost manifest exist without at least one estimated cost profile?
It may be possible to just describe the purpose of the manifest via the description, but would a description be considered enough?

**Comment by siuc-nate** [comment]
This has been taken care of.
