### ISSUE TITLE
Rework ASN profile page to more closely match the CTDL viewer

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#345]
We want to make http://credreg.net/ctdl/frameworkschema have the same sort of visual look and feel as http://credreg.net/ctdl/terms.

Would we still want this page to be pure HTML that pulls from our shared drive or should it be generated from a spreadsheet?

**Comment by stuartasutton** [comment]
Well, there is certainly something to be said for being consistent in technical underpinnings of the documentation. So, I'd follow the same technical documentation path as the CTDL.

**Comment by jkitchensSIUC** [comment]
I'm going as far as saying it could be entered in the schema database, use the same table formats and be handled identically as CTDL releases.

**Comment by siuc-nate** [comment]
@jkitchensSIUC just to clarify: would we be adding all of the ASN stuff to CTDL (as in, make it a part of the schema itself, show it in the metadata viewer and serializations, include it in workit, etc.)?  Or would it still be separate (like history tracking)?

**Comment by stuartasutton** [comment]
No, we would not be adding all the ASN stuff to CTDL. Also, there are other
issues, such as no single namespace. ASN is an application profile that
includes properties from more than the ASN schema--e.g. Dublin Core terms
etc.

**Comment by stuartasutton** [comment]
I brought up the multiple namespaces in ASN **only** because there might be technical mechanisms in place that rely on the namespace to determine how a property of class end's up being grouped and displayed in the interface.

**Comment by siuc-nate** [comment]
This has been done.
