### ISSUE TITLE
Determine if decisionInformation property should be added to the verificationServiceProfile

### ISSUE THREAD

**Issue by mparsons1953** [CredentialEngine/vocabularies#346]
Bob Sheets requested that decision information is needed on verification service profile. He thought that it could be a boolean, where Yes- means have decision information on the website. 
Upon discussion with Jeanne, we felt that it should be a URL. DecisionInformation was removed from the profile in November: #195 
https://github.com/CredentialEngine/vocabularies/issues/195

**Comment by stuartasutton** [comment]
#195 removed both `ctdl:decisionInformationDescription` (Literal) and `ctdl:decisionInformation` (xsd:anyURI) on `ceterms:VerificationServiceProfile`. So we are adding back `ctdl:decisionInformation` (xsd:anyURI) only. Can we dig up the original definition.

**Comment by jkitchensSIUC** [comment]
@mparsons1953 @stuartasutton @siuc-nate we need to talk about this one. I don't understand the value or how it would be utilized in the real world to have a boolean that answers if something is on a web page.

**Comment by stuartasutton** [comment]
Jeanne, we did have a property called `ceterms:decisionInformation` (xsd:anyURI) that was dropped well before the first release. It was a property on `ceterms:ProcessProfile` and was defined as follows:

> A resource that describes the types of decisions that are made about the processes the organization performs and how those decisions are defined.

There was also a `ceterms:decisionInformationDescription` (rdfs:Literal) defined as:

> The types of decisions that are made about the processes the organization performs and how those decisions are defined.

I agree with Jeanne that this property with a boolean value is rather senseless on either `ceterms:VerificationServiceProfile` or `ceterms:ProcessProfile`. I assume this points to a webpage where decision criteria can be found.

**Comment by siuc-nate** [comment]
Relevant document:
https://docs.google.com/document/d/13td5-K4uYrfInkX2mpxeO-XpN9mFIraoe8NSciv7f58/edit#heading=h.gjdgxs

**Comment by siuc-nate** [comment]
In the past year or so since this issue was opened, there has been no demonstration that this is needed.  Closing this issue until such a need appears.
