### ISSUE TITLE
Implement ceterms:financialAssistance

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#348]
Long ago, we had determined that we would indicate financial assistance information via ceterms:financialAssistance and ceterms:FinancialAlignmentObject:
https://docs.google.com/document/d/1KDdOXpCX0b3KyJnvR52hyOOwhbeUCMtBzlLbPZYV1vc/edit# (ctrl + f "financial")
Issue #125

However, only FinancialAlignmentObject was ever actually created (perhaps due to financialAssistance not being included in the action column on the right).

We should correct this oversight - currently no properties point at FinancialAlignmentObject.

**URI:** ceterms:financialAssistance
**Definition:** The types of financial assistance for which the resource being described qualifies.
**Domain:** ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile
**Range:** ceterms:FinancialAlignmentObject

**Comment by jkitchensSIUC** [comment]
Students want to to search and filter to identify credentials that qualify for financial aid. An organization may have an OPEID but not all programs qualify for financial aid.

**Comment by stuartasutton** [comment]
The range gives us the means of describing through Financial AlignmentObject. But, that implies a framework on the other end and the proposed definition suggests a set of types of financial aid assistance.

**Comment by siuc-nate** [comment]
That's correct.  An example might look like this (borrowed from the google doc):
```
{
	"@type": "ctdl:LearningOpportunityProfile",
	"ctdl:financialAssistance": [
		{
			"@type": "ctdl:FinancialAlignmentObject",
			"targetName": "FAFSA",
			"targetDescription": "FAFSA Description text"
			"targetUrl": "http://www.fafsa.ed.gov/"
		}
	]
}
```
Though I suppose could rework it so that FAFSA was the framework and some specific element of it was the financial aid? It might make more sense for some types of financial aid than others, depending on how complex they are or how many options they offer.  The point is that we needed a way to name, describe, and link to financial aid, and AlignmentObject made sense for that since it includes exactly those fields (plus financial aid could be thought of as a framework)

If I remember correctly, FinancialAlignmentObject was the way you wanted to handle this - the class was, I think, your creation.  Is there a problem with adding the property to point to it?

**Comment by jkitchensSIUC** [comment]
Is there a reason not to include ceterms:Credential? 

URI: ceterms:financialAssistance
Definition: The types of financial assistance for which the resource being described qualifies.
Domain: ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile
Range: ceterms:FinancialAlignmentObject

**Comment by siuc-nate** [comment]
Per our 3/21/2017 conversation, we will add financialAssistance to all three:

**URI:** ceterms:financialAssistance
**Definition:** The types of financial assistance for which the resource being described qualifies.
**Domain:** ceterms:Credential, ceterms:LearningOpportunityProfile, ceterms:AssessmentProfile
**Range:** ceterms:FinancialAlignmentObject

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
