### ISSUE TITLE
Change label of ceterms:verificationMethodDescription

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#350]
Currently we have:
ceterms:hasVerificationService
ceterms:verificationDirectory
ceterms:verificationService
ceterms:verifiedClaimType
ceterms:verificationMethodDescription

With labels:
Has Verification Service
Verification Directory
Verification Service URL
Verified Claim Type
**Validation** Method Description

We should change the label, "Validation Method Description" to "Verification Method Description" for the sake of consistency.

**Comment by stuartasutton** [comment]
@siuc-nate, this looks like a simple error to me. Since it does not entail a change to the URI, it should simply be changed and noted.

**Comment by siuc-nate** [comment]
Action to be taken:

**Remove:**
> **URI:** ceterms:verificationMethodDescription
> **Predicate:** rdfs:label
> **Object:** "Validation Method Description"

**Add:**
> **URI:** ceterms:verificationMethodDescription
> **Predicate:** rdfs:label
> **Object:** "Verification Method Description"

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
