### ISSUE TITLE
ConditionProfile still has a reference to targetTask, should it be set to unstable?

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#351]
@stuartasutton 
The ConditionProfile class still has a reference to targetTask, and the latter has a status of stable.
As the TaskProfile class has a status of  unstable,  should this be set as deprecated, or at least unstable.

**Comment by stuartasutton** [comment]
I would hope we could reach a conclusion on whether we are keeping the unstable `Task` entity or not and make this corrections at the same time. @jkitchensSIUC & @siuc-nate, what do we need to do to know or do to deprecate `Task`?

**Comment by jkitchensSIUC** [comment]
@stuartasutton @mparsons1953 @siuc-nate this requires a review based mainly on certifications that has yet to occur. I'd like to see the person issue get resolved and closed and then move on to this one.

**Comment by siuc-nate** [comment]
Per our 3/21/2017 meeting, we will set targetTask to be unstable.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
