### ISSUE TITLE
Determine multiplicity of properties for CER application profile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#352]
In order to write our code and documentation effectively, and in order to help others with their implementations, we need to know whether every property in CTDL is supposed to contain a single value or an array of values.

I have existing columns in the spreadsheet we read from that are intended to allow indicating which properties are multi-value and which ones are not.  The JSON schema can accept single, multi, or both.  RDF, as far as I know, doesn't care. The problem is that implementations (workit, the registry, and anything else that someone else comes up with - not just us) _will_ care, because:
```
{
   "someProperty": "someValue"
}
```
and
```
{
   "someProperty": [ "someValue1", "someValue2", "someValue3" ]
}
```
require **different** implementations:
- The class definitions will be different (regardless of programming language)
- The method signatures will be different (regardless of programming language)
- The displays will be different (coding to handle 0-1 blocks of text is different from coding to handle 0-n blocks of text, and it gets even worse for objects)
- The data storage and querying will be different (regardless of SQL or Graph or Document or any other structure)
- Handling searches and search results will be different
- The methods of serializing/deserializing will be different (With JSON, you can't deserialize a single value piece of data into a multi value field or vice versa.)
- The APIs will be different (as will the documentation and what they can do and what they will handle)
- Null/empty checks will be different (coding to handle an empty list is different from coding to handle a null object)
- Validation will be different (see comment: https://github.com/CredentialEngine/CredentialRegistry/issues/21#issuecomment-287490596 )

Basically everything about handling a property in code is **significantly** different depending on whether or not a property is multi value.  And any strongly-typed language (like C#, which we use internally) will not permit a property to be "either/or".  A loosely-typed language like javascript will _allow_ this, but you will still have to write all of the other code _very_ differently. For instance, if your javascript is expecting an array of strings and you give it a single string, then it will treat the string as an array of characters and you can get undesirable results.

So, I cannot stress enough that it is _critical_ that we correctly and reliably define the properties in the way that makes the most sense and is least likely to come back to bite us.

We need to come up with a way of deciding this for existing and future properties.  The most bulletproof method would simply be to say that anything can be multi-value. This would be more easily compatible with XML-based data (such as HTML we intend to crawl), and is the most flexible possible way of handling data, and more closely reflects the "it doesn't care" nature of RDF. _However_, this will make coding much more complex, as, in general, handling a list requires more thought, planning, and lines of code than handling a single value.  

On the other hand, if we are too strict and someday decide that a property we made single-value should really be multi-value, then we've got a problem because any existing data for that property will now require special handling and/or conversion, which can be very messy: 

If we one day decide, for example, that `ceterms:description` should really allow for an array of strings (ie for different languages - setting aside for a moment that that requires objects rather than strings), then suddenly all of our existing `ceterms:description` data is broken and needs to be handled and/or fixed. As do the APIs. As does the documentation. As do other implementations. Now you've got to version your API, make changes in github, update your code to handle both types during the transition (and while your deprecated API is still active), add additional properties and workarounds to your classes...it's a nightmare, really. 

For this reason, I think it's probably smart to start by defaulting everything to being multi-value, even if it means eating the extra overhead.  Then we selectively make certain things single value if and _only_ if we are 100% certain about that choice - for instance, boolean properties make no sense as multi-value properties: `ceterms:globalJurisdiction` makes no sense as both "true" _and_ "false".  Numbers might be another candidate - what sense would it make for a ConditionProfile to have a `ceterms:weight` of `[0.1, 0.5, 0.8]`? Without any grouping or context, the data's meaning is lost.  Dates can probably be single-value; multiple `ceterms:startTime`s wouldn't make sense.  So perhaps it's just `rdfs:literal`s, `xsd:anyURI`s and properties that point to profiles?

We also need to determine whether or not a property can be multi-value _in the context of a given class_ - that is to say, could something like `ceterms:offeredBy` be single-value for AssessmentProfile but multi-value for Credential? I doubt it. I'm reasonably certain we can safely say that a property's multiplicity will be the same regardless of which class it's used with (and if we can lock ourselves into that, it simplifies things a lot)

So, to sum up:
- Determining multiplicity is really, **really** important to get right as early as possible, because changing it later creates a myriad of problems
- The most flexible, but most complicated, way of handling this is to make everything multi-value
- Some properties make no sense as multi-value, so we need a reliable method for determining multiplicity that we can use now and in the future
- Can properties be multi-value in some classes and single-value in others? (I hope not)

**Comment by stuartasutton** [comment]
@siuc-nate & @jkitchensSIUC , I do not take issue with the fact that **implementations** and the **application profiles** that support them require clear restraints on multiplicity and optionality of CTDL properties/classes. But, getting to such application profiles (the CER being one), is exactly what the entire approach we have undertaken has been about (http://www.credreg.net/tac/technicalapproach) -- i.e., going from a 'dictionary' of properties and classes that have no constrains to a tightly constrained "application profile" (that drives the CER). 

So, wearing your CER implementer hat, determining and documenting these constraints on optionality and repeatability of CTDL properties (and classes) matters a great deal. But, there is another "hat" (that we both wear), and that is to design a description language (i.e., the CTDL) that can be used by people across the credential ecosystem to design their **own systems** and to make their **own decisions** about what should be required or whether properties should be repeatable.  So, my problem with this github issue rant is not that such constrain decisions shouldn't be made and documented --**they have to be made**-- but in the context of an application profile, not in the context of the CTDL. You guys (you Nate, Michael, Steve etc.) are struggling now with determining and documenting those constraints for a ***CER application profile of the CTDL***.  

SO, in the context of defining a **CER application profile of the CTDL**, these constraints must be determined and documented. That does not necessitate baking those specific constraints into the CTDL language itself.

**Comment by stuartasutton** [comment]
In sum, @siuc-nate, please don't confuse an application profile and its various constraints with the domain language it relies on. The CTDL is a community domain language defining what can be said about the entities it covers in its "domain". 

This distinction between a community domain language and an application profile of that language is laid out in the DCMI Singapore Framework for expressing a DCAP:

![singapore-framework](https://cloud.githubusercontent.com/assets/2939046/24291456/45a84b0a-1046-11e7-95ec-01c0fbee3c31.png)

http://dublincore.org/documents/singapore-framework/ (worth reading)

The CTDL is a "Community Domain Model" in the "Domain Standards" layer of the of the DCMI Singapore Framework--i.e., it is a community artifact. The CER "Domain Model" is an artifact in the top "Application Profile" layer--i.e., it is a CER-speciic artifact. The CER application profile "uses" the CTDL, but they are different beasts.  

Absolutely **everything** you said about constraints is spot on for a CER application profile (using the CTDL).

**Comment by siuc-nate** [comment]
To summarize:
- Properties that point to URIs and Literals use multiplicity constraints defined here: https://docs.google.com/spreadsheets/d/1mqEHVE6fPzxMhkTgM2Sp3T5ccuw2cDZ78heuyt7azoI/edit#gid=0
- Properties that point to booleans, numbers, and dates are always single-value
- Properties that point to classes are always multi-value
