### ISSUE TITLE
Correct range of ceterms:actionStatusType

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#354]
http://credreg.net/ctdl/terms/actionStatusType
This currently has a range of
schema:ActionStatusType

The range should actually be
ceterms:CredentialAlignmentObject
(because this term points to a vocabulary)

**Comment by stuartasutton** [comment]
Correct. This should be changed.

**Comment by siuc-nate** [comment]
Action: 

**Remove:**
> **Subject:** ceterms:actionStatusType
> **Predicate:** rdfs:range
> **Object:** schema:ActionStatusType

**Add:**
> **Subject:** ceterms:actionStatusType
> **Predicate:** rdfs:range
> **Object:** ceterms:CredentialAlignmentObject

These changes have been made in pending CTDL and noted in history tracking.
