### ISSUE TITLE
Remove schema:ContactPoint from range of ceterms:contactPoint

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#355]
http://credreg.net/ctdl/terms/contactPoint

This is a deprecated property, but since it must still be included in validation and related documents and processes, it is useful to ensure the range actually exists within CTDL.

To this end, I propose we remove schema:ContactPoint from the range of ceterms:contactPoint.

**Comment by stuartasutton** [comment]
I don't understand. ceterms:ContactPoint does exist so I am not sure why we'd remove it from range of this deprecated property.

**Comment by siuc-nate** [comment]
Correct - ceterms:ContactPoint exists, but **schema**:ContactPoint does not (in CTDL).  This can create problems in validation or code that tries to connect entities to the classes they target.

It's not a _huge_ deal, but it is nice to keep the schema tidy.

**Comment by stuartasutton** [comment]
Agreed.

**Comment by siuc-nate** [comment]
Action:

**Remove:**
> **Subject:** ceterms:contactPoint
> **Predicate:** rdfs:range
> **Object:** schema:ContactPoint

This change has been made in pending CTDL and noted in history tracking.
