### ISSUE TITLE
Correct range of ceterms:image

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#356]
http://credreg.net/ctdl/terms/image

This currently has a range of schema:Image, which does not exist.  The related property, http://schema.org/image has a range of either xsd:anyURI or a class called ImageObject.  I do not see any need or use in creating an Image class, even as a placeholder with no properties, so I propose we change the range of ceterms:image to xsd:anyURI.

**Comment by stuartasutton** [comment]
We should go with xsd:anyURI.

**Comment by siuc-nate** [comment]
Action:

**Remove:**
> **Subject:** ceterms:image
> **Predicate:** rdfs:range
> **Object:** schema:Image

Add:
> **Subject:** ceterms:image
> **Predicate:** rdfs:range
> **Object:** xsd:anyURI

These changes have been made in pending CTDL and noted in history tracking.
