### ISSUE TITLE
Correct range of ceterms:learningResource

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#357]
http://credreg.net/ctdl/terms/learningResource

This property is deprecated, but because it must be included in validation and similar processes, it still ideally has a range that exists in CTDL.  So, I propose we change the range of ceterms:learningResource from asn:LearningResource to ceterms:LearningResource

**Comment by stuartasutton** [comment]
Agreed.

**Comment by siuc-nate** [comment]
Action:

**Remove:**
> **Subject:** ceterms:learningResource
> **Predicate:** rdfs:range
> **Object:** asn:LearningResource

**Add:**
> **Subject:** ceterms:learningResource
> **Predicate:** rdfs:range
> **Object:** ceterms:LearningResource

These changes have been made in pending CTDL and noted in history tracking.
