### ISSUE TITLE
Clarify distinction between ceterms:costDetails and ceterms:description

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#358]
ceterms:costDetails seems to just be a rehash of ceterms:description.  When or why would you use one over the other? Both of them have a domain of ceterms:CostProfile.

http://credreg.net/ctdl/terms/costDetails

If no significant reason can be found for keeping this property, I propose we deprecate it.

**Comment by stuartasutton** [comment]
It does seem that the likelihood would be that the same data would be provided for both. If deprecated, the reason should make clear that `ceterms:description` should be used instead. That does not imply thats `ceterms:description` supersedes it.

**Comment by siuc-nate** [comment]
Actually, I made a mistake - costDetails is a URI rather than a literal.  I was in the middle of several things at the time and didn't notice this.  I don't think there is any action to be taken here.
