### ISSUE TITLE
Add ceterms:CredentialOrganization and ceterms:QACredentialOrganization to the domain of ceterms:industryType

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#359]
Currently there is no way to indicate what industry(ies) an organization operates in, as the industryType property is only attached to Credential.

I propose adding industryType to Credential/QA Organization as well.

**Comment by stuartasutton** [comment]
Makes sense.

**Comment by siuc-nate** [comment]
Action:

**Add:**
> **Subject:** ceterms:industryType
> **Predicate:** rdfs:domain
> **Object:** ceterms:CredentialOrganization

**Add:**
> **Subject:** ceterms:industryType
> **Predicate:** rdfs:domain
> **Object:** ceterms:QACredentialOrganization

These changes have been made in pending CTDL and noted in history tracking.
