### ISSUE TITLE
Should the range of ceterms:weight be xsd:decimal as opposed to xsd:float?

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#360]
Currently, the range of `ceterms:weight` is `xsd:float`? Should it be changed to `xsd:decimal`?

**Comment by siuc-nate** [comment]
I think we should be consistent across ranges - anything else that uses float should use decimal if we make the switch.

Is there a particular justification for changing the range?

**Comment by stuartasutton** [comment]
Not sure of accuracy on my part. http://net-informations.com/q/faq/float.html
