### ISSUE TITLE
Update definition for ceterms:offers

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#361]
http://credreg.net/ctdl/terms/offers

The comment for ceterms:offers is better-written than its definition, and means the same thing. I propose we replace the definition for offers with the comment for offers, and then remove the comment.

**Comment by stuartasutton** [comment]
That's acceptable to me.

**Comment by siuc-nate** [comment]
Action to be taken:

**Remove**
> **Subject:** ceterms:offers
> **Predicate:** rdfs:comment
> **Object:** "Offers access to or issues the resource being referenced."

**Add**
> **Subject:** cetermsceterms:offersPersonType
> **Predicate:** rdfs:comment
> **Object:** "The agent being described offers or confers the resource being referenced."

**Remove**
> **Subject:** ceterms:offers
> **Predicate:** dcterms:description
> **Object:** "The agent being described offers or confers the resource being referenced."

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in history tracking.
