### ISSUE TITLE
Change "organization" to "agent" in the definitions for ceterms:serviceType and ceterms:AgentServiceType

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#362]
In order to apply serviceType and its vocabulary to Person, we need to update their definitions to replace "organization" with "agent".

**Comment by siuc-nate** [comment]
Action to be taken:

**Remove**
> **Subject:** ceterms:serviceType
> **Predicate:** rdfs:range
> **Object:** "The type of service offered by the organization."

**Add**
> **Subject:** ceterms:serviceType
> **Predicate:** rdfs:range
> **Object:** "The type of service offered by the agent being described."

**Remove**
> **Subject:** ceterms:AgentServiceType
> **Predicate:** rdfs:comment
> **Object:** "The type of service offered by the organization."

**Add**
> **Subject:** ceterms:AgentServiceType
> **Predicate:** rdfs:comment
> **Object:** "An enumeration of types of services offered by an agent."

**Comment by stuartasutton** [comment]
Yup.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
