### ISSUE TITLE
Suppress ceterms:worksFor, ceterms:employee, and ceterms:affiliation in CER application profile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#364]
Per our 3/28/2017 discussion

There was some back and forth on whether or not we should deprecate these terms because, while technically valid, they invite undesirable usage of ceterms:CredentialPerson:

- ceterms:worksFor
- ceterms:employee
- ceterms:affiliation

Perhaps we should mark them as unstable for now?

**Comment by stuartasutton** [comment]
I have no objection to them being marked as unstable while recognizing that someone relying on a stable designation might be a bit annoyed to find them now unstable.

**Comment by siuc-nate** [comment]
We never quite decided on deprecating them - perhaps we should move forward on that instead?

**Comment by stuartasutton** [comment]
Let's mark them as unstable and not deprecate.

**Comment by siuc-nate** [comment]
Per our 4/4/2017 call:
We will not make any of the above changes; these will instead be excluded in the CER Application Profile.

**Comment by siuc-nate** [comment]
These have been noted here:
https://github.com/CredentialEngine/vocabularies/projects/5
