### ISSUE TITLE
Add ceterms:QACredentialOrganization to the range of several properties

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#365]
Currently, the following properties have a range that includes ceterms:CredentialOrganization, but not ceterms:QACredentialOrganization.  I propose we add it:

- ceterms:affiliation
- ceterms:copyrightHolder
- ceterms:object
- ceterms:worksFor

**Comment by stuartasutton** [comment]
I agree.

**Comment by siuc-nate** [comment]
Action to be taken:

**Add**
> **Subject:** ceterms:affiliation
> **Predicate:** rdfs:range
> **Object:** ceterms:QACredentialOrganization

**Add**
> **Subject:** ceterms:copyrightHolder
> **Predicate:** rdfs:range
> **Object:** ceterms:QACredentialOrganization

**Add**
> **Subject:** ceterms:object
> **Predicate:** rdfs:range
> **Object:** ceterms:QACredentialOrganization

**Add**
> **Subject:** ceterms:worksFor
> **Predicate:** rdfs:range
> **Object:** ceterms:QACredentialOrganization

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
