### ISSUE TITLE
Determine what to do with ceterms:PersonType

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#366]
http://credreg.net/Ctdl/terms/PersonType

This was added a long time ago, probably in the early days of ceterms:CredentialPerson

Since we are stabilizing CredentialPerson, we should either:
1) Add a property to point to this vocabulary, and flesh out the vocabulary with some terms
or
2) Deprecate ceterms:PersonType

**Comment by stuartasutton** [comment]
Are others as hard pressed to think of differentiating terms for [`ceterms:PersonType`](http://credreg.net/Ctdl/terms/PersonType) vocabulary that would not be substantively duplicative of existing properties such as [`ceterms:serviceType`](http://credreg.net/ctdl/pending#serviceType) and its companion [`ceterms:AgentServiceType`](http://credreg.net/ctdl/pending#AgentServiceType) vocabulary?

**Comment by siuc-nate** [comment]
None come to mind.  Would this be a TAC question?

**Comment by jkitchensSIUC** [comment]
This needs to be deprecated.

**Comment by siuc-nate** [comment]
Action to be taken:

**Remove**
> **Subject:** ceterms:PersonType
> **Predicate:** vs:term_status
> **Object:** vs:stable

**Add**
> **Subject:** ceterms:PersonType
> **Predicate:** vs:term_status
> **Object:** vs:deprecated

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in history tracking.
