### ISSUE TITLE
Update definition, comment, etc. of ceterms:CredentialPerson

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#367]
http://credreg.net/ctdl/pending#CredentialPerson
Currently the definition of CredentialPerson is broad (and contains a typo):
"An person who plays one or more key roles in the lifecycle of a credential."

This does not adequately scope CredentialPerson to _just_ those persons who have a direct role with a credential.  We need to fix the definition, and perhaps add a comment and/or usage note.

Thoughts?

**Comment by stuartasutton** [comment]
Yes, we need further guidance through a comment such as the following:

> The CredentialPerson class should be used to describe persons directly engaged as primary agent in credentialing actions such as approving, offering, recognizing, renewing and revoking credentials and should not include persons merely affiliated with, or employed by organizations that perform such actions.

**Comment by siuc-nate** [comment]
Per our 4/4/2017 call:

We will revise the definition and add a comment:
**Definition:** A person who plays a role as primary agent in a credentialing action.
**Comment:** The CredentialPerson class should be used to describe persons directly engaged as primary agent in credentialing actions such as approving, offering, recognizing, renewing and revoking credentials and should not include persons merely affiliated with, or employed by organizations that perform such actions.

**Comment by siuc-nate** [comment]
Action to be taken:
**Remove**
> **Subject:** ceterms:CredentialPerson
> **Predicate:** rdfs:comment
> **Object:** "An person who plays one or more key roles in the lifecycle of a credential."

**Add**
> **Subject:** ceterms:CredentialPerson
> **Predicate:** rdfs:comment
> **Object:** "A person who plays a role as primary agent in a credentialing action."

**Add**
> **Subject:** ceterms:CredentialPerson
> **Predicate:** dcterms:description
> **Object:** "The CredentialPerson class should be used to describe persons directly engaged as primary agent in credentialing actions such as approving, offering, recognizing, renewing and revoking credentials and should not include persons merely affiliated with, or employed by organizations that perform such actions."

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in history tracking.
