### ISSUE TITLE
Change the range of ceterms:foundingDate from xsd:dateTime to rdfs:Literal

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#368]
In order to enable entry of partial dates in a way that is universally flexible, we should change the range of ceterms:foundingDate from xsd:dateTime (which requires a full date) to rdfs:Literal (which allows "1995", "January 2012", "3/2011", etc).

This date is not a critical element used in any calculations anyway, and is typically just a point of trivia or interest in regards to an organization, so I do not see a downside.

we would also likely want to remove foundingDate as a subproperty of ceterms:temporalCoverage.

**Comment by cwd-mparsons** [comment]
I would prefer only number.
The downside would being able to do minimum validation.
Requiring a number (for each section), prevents spelling issues, as well as use of multiple languages.

**Comment by siuc-nate** [comment]
If we only want a number, then I think a "foundingYear" property would make more sense.

**Comment by stuartasutton** [comment]
As I noted in #370, I don't see why this simply can't have a range of `xsd:date`.

**Comment by siuc-nate** [comment]
We want to enable entry of partial dates (such as the founding year, sometimes with a month) and not require a full date for this property.

**Comment by stuartasutton** [comment]
OK, so what's wrong with xsd:gYear (https://www.w3.org/TR/xmlschema-2/#built-in-primitive-datatypes)

**Comment by siuc-nate** [comment]
gYear wouldn't allow a value like "January 2001", only the number 2001.

If foundingDate should permit any portion of a date, I think it should be a string.

If foundingDate should **only** be the year, I think we should still make it a string _and_ create a "foundingYear" property that could then use xsd:gYear

if foundingDate should permit only a full date, then we can use it as-is (albeit with a change to xsd:date instead of xsd:dateTime)

Ultimately founding date is mostly just an informational property rather than something that _needs_ to be strictly controlled for use in calculations, sorting, etc., unless you have some niche system that groups organizations by how old they are (in which case foundingYear would likely be adequate, unless you have a number of organizations that were created in the same year), which may be an edge case beyond something we need to burden the majority of schema users with.

My proposal is thus:
- Change the range of foundingDate to a Literal
- Create a foundingYear property with a range of xsd:gYear

Alternatively (perhaps this meets all needs?):
- Change the range of foundingDate to xsd:date
- Create a foundingYear property with a range of xsd:gYear
- Create a foundedOn property that is a literal

An entry system such as our editor could present a date field to the user and _if_ they happen to enter a complete date, store the information within foundingDate, otherwise store it within foundedOn (perhaps with a similar check to see if they only entered a year?)

**Comment by siuc-nate** [comment]
Per our 4/7/2017 call:
We will change the range of ceterms:foundingDate to rdfs:literal.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in history tracking.
