### ISSUE TITLE
Change all properties that currently have a range of xsd:dateTime to use xsd:date instead

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#369]
Because we do not use the time aspect and because xsd:dateTime requires a full date and time to be included, we should change anything that currently uses xsd:dateTime to use xsd:date instead (except for foundingDate - see #368 ).

These properties are:
- ceterms:alignmentDate
- ceterms:dateEffective
- ceterms:endTime
- ceterms:startTime
- ceterms:temporalCoverage

**Comment by siuc-nate** [comment]
Action to be taken:

**Remove**
> **Subject:** ceterms:alignmentDate
> **Predicate:** rdfs:range
> **Object:** xsd:dateTime

**Add**
> **Subject:** ceterms:alignmentDate
> **Predicate:** rdfs:range
> **Object:** xsd:date

**Remove**
> **Subject:** ceterms:dateEffective
> **Predicate:** rdfs:range
> **Object:** xsd:dateTime

**Add**
> **Subject:** ceterms:dateEffective
> **Predicate:** rdfs:range
> **Object:** xsd:date

**Remove**
> **Subject:** ceterms:endTime
> **Predicate:** rdfs:range
> **Object:** xsd:dateTime

**Add**
> **Subject:** ceterms:endTime
> **Predicate:** rdfs:range
> **Object:** xsd:date

**Remove**
> **Subject:** ceterms:startTime
> **Predicate:** rdfs:range
> **Object:** xsd:dateTime

**Add**
> **Subject:** ceterms:startTime
> **Predicate:** rdfs:range
> **Object:** xsd:date

**Remove**
> **Subject:** ceterms:temporalCoverage
> **Predicate:** rdfs:range
> **Object:** xsd:dateTime

**Add**
> **Subject:** ceterms:temporalCoverage
> **Predicate:** rdfs:range
> **Object:** xsd:date

**Comment by stuartasutton** [comment]
See #370. I don't think we should redefine the range of `ceterms:startTime` and `ceterms:endTime`. rather, we should leave them as-is and add new `ceterms:startDate` and `ceterms:endDate` properties with range of `xsd:date` and use these new terms where we are currently using `ceterms:startTime` and `ceterms:endTime`.

**Comment by siuc-nate** [comment]
@stuartasutton I have created this issue to address the points you bring up: #373 

For the rest, the revised proposal is:

**Remove**
> **Subject:** ceterms:alignmentDate
> **Predicate:** rdfs:range
> **Object:** xsd:dateTime

**Add**
> **Subject:** ceterms:alignmentDate
> **Predicate:** rdfs:range
> **Object:** xsd:date

**Remove**
> **Subject:** ceterms:dateEffective
> **Predicate:** rdfs:range
> **Object:** xsd:dateTime

**Add**
> **Subject:** ceterms:dateEffective
> **Predicate:** rdfs:range
> **Object:** xsd:date

**Remove**
> **Subject:** ceterms:temporalCoverage
> **Predicate:** rdfs:range
> **Object:** xsd:dateTime

**Add**
> **Subject:** ceterms:temporalCoverage
> **Predicate:** rdfs:range
> **Object:** xsd:date

**Comment by stuartasutton** [comment]
These look OK to me.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
