### ISSUE TITLE
Add ceterms:ConditionProfile to the domain of ceterms:subjectWebpage

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#371]
In order to facilitate linking to a description of conditions, we should add ceterms:ConditionProfile to the domain of ceterms:subjectWebpage. Previously, ConditionProfile would have used referenceURL/resourceURL for this, but those properties were removed.

**Comment by siuc-nate** [comment]
Action to be taken:

**Add**
> **Subject:** ceterms:subjectWebpage
> **Predicate:** rdfs:domain
> **Object:** ceterms:ConditionProfile

**Comment by stuartasutton** [comment]
I see no problem with adding `ConditonProfile` as a domain of`subjectWebpage`. Although not asked, I'd say the same for `CondiitonManifest`.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in history tracking.
