### ISSUE TITLE
Rewrite definition and usage note of ceterms:spatialCoverage

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#372]
https://credreg.net/ctdl/terms/spatialCoverage

The definition and usage note seem to have been almost or entirely copied from https://credreg.net/ctdl/terms/temporalCoverage and are incorrect for a property that is supposed to describe a geographic area.

The schema.org definition for spatialCoverage:
"The spatialCoverage of a CreativeWork indicates the place(s) which are the focus of the content. It is a subproperty of contentLocation intended primarily for more technical and detailed materials. For example with a Dataset, it indicates areas that the dataset describes: a dataset of New York weather would have spatialCoverage which was the place: the state of New York."

Proposed definition:
"The place(s) which are the focus of the resource being described."
Proposed usage note:
"In the CTDL, the ceterms:spatialCoverage property serves as a super-property for an array of sub-properties defining location-dependent or area-dependent aspects of a resource."

**Comment by stuartasutton** [comment]
Change looks OK to me.

**Comment by siuc-nate** [comment]
Action to be taken:

**Remove**
> **Subject:** ceterms:spatialCoverage
> **Predicate:** rdfs:comment
> **Object:** "The temporalCoverage of a CreativeWork indicates the period that the content applies to, i.e. that it describes, either as a DateTime or as a textual string indicating a time period in ISO 8601 time interval format."

**Add**
> **Subject:** ceterms:spatialCoverage
> **Predicate:** rdfs:comment
> **Object:** "The place(s) which are the focus of the resource being described."

**Remove**
> **Subject:** ceterms:spatialCoverage
> **Predicate:** vann:usageNote
> **Object:** "In CTDL, the ceterms:spatialCoverage property serves as a super-property for an array of sub-properties describing specific time-dependent aspects of a resource."

**Add**
> **Subject:** ceterms:spatialCoverage
> **Predicate:** vann:usageNote
> **Object:** "In the CTDL, the ceterms:spatialCoverage property serves as a super-property for an array of sub-properties defining location-dependent or area-dependent aspects of a resource."

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
