### ISSUE TITLE
Replace ceterms:startTime and ceterms:endTime with new properties: ceterms:startDate and ceterms:endDate

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#373]
Per @stuartasutton 's comment here: https://github.com/CredentialEngine/vocabularies/issues/369#issuecomment-292234095

We should create two new properties:
- ceterms:startDate
- ceterms:endDate

Each with the same set of domains as ceterms:startTime and ceterms:endTime:
- ceterms:CostProfile
- ceterms:CredentialingAction (and subclasses)

Then, if I am interpreting that comment correctly, remove those domains from ceterms:startTime and ceterms:endTime

This would result in
- Two new properties, ceterms:startDate and ceterms:endDate
- CostProfile and CredentialingAction would use startDate and endDate instead of startTime and endTime
- startTime and endTime would have **no** domain

Would that last bullet imply we should deprecate startTime and endTime? It's possible they could be useful later.  Would it be better to simply leave them alone entirely and only create the new properties?

**Comment by siuc-nate** [comment]
Per our 4/7/2017 call:

- Create ceterms:startDate and ceterms:endDate
- Remove domains from ceterms:startTime and ceterms:endTime
- Do **not** deprecate ceterms:startTime and ceterms:endTime

**Comment by stuartasutton** [comment]
Look good to me, Nate.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.

**Comment by jkitchensSIUC** [comment]
Thank you.
