### ISSUE TITLE
ceterms:EarningsProfile

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#376]
Crosswalk to other standards and determine additional properties. 

[ceterms:EarningsProfile](ceterms:EarningsProfile)

**Comment by jkitchensSIUC** [comment]
Prepare to show WIOA eligible providers list to include employment and earnings in the Fall.

**Comment by stuartasutton** [comment]
Jeanne, do we have a google doc that lists other relevant standards for earnings (statistical parameters etc.)?

**Comment by jkitchensSIUC** [comment]
@stuartasutton don't have a Google doc yet, but will.  Below is from Bob Sheets.
 
Earnings (ceterms:earnings)  profile of credential holder earnings data. Include statistical data on employment and earnings for the credential being described (property definition and usage note)

The profile definition is: "A resource that describes earning and related statistical information for a given credential." http://credreg.net/ctdl/terms/EarningsProfile 

- Credential Profiled (ceterms:credentialProfiled) profile of the credential being referenced
- Median Earnings (ceterms:medianEarnings) The median earnings
-  High Earnings (ceterms:highEarnings) The upper interquartile earnings
-  Low Earnings (ceterms:lowEarnings)  The lower interquartile earnings
- ost Receipt Months (ceterms:postReceiptMonths) The number of months following the receipt of the credential when the employment and earnings data was collected
- Jurisdiction (ceterms: jurisdicdtion) The geo-political region in which the described resource is applicable.
- Region (ceterms: region) A geo-political area of the described resource.
- Source (ceterms:source) The source of this resource's information  (URI)
- Date Effective (ceterms:dateEffective) The effective date of the described resource content.

Questions:

- Different  uses of jurisdiction and region in addressing the coverage of the geographic area  from which earnings data were gathered.

This is a reply from @siuc-nate

Way back when CTDL was first being developed and we first tackled the handling of location-related data, we created both ceterms:GeoCoordinates (the thing that "region" points at) and ceterms:JurisdictionProfile (which "jurisdiction" points at).  Jurisdiction Profile contains a main jurisdiction and jurisdiction exceptions, both of which are GeoCoordinates objects. So far in workit, we do not use ceterms:region at all.  This is intentional – the purpose of region is to be a shortcut to include GeoCoordinates data without going through a JurisdictionProfile (Stuart, correct me if I'm wrong).  The idea is that the user of CTDL would use either one profile or the other; not both. If anything, we should remove ceterms:region, I think.

**Comment by stuartasutton** [comment]
We should not be hasty in dropping `ceterms:region`. The fact that Workit doesn't use it isn't a satisfactory reason to drop it. The properties `ceterms:region` and `ceterms:jurisdiction` have very different definitions/intentions. One has to do with an area of *applicability* and the other does not.

`ceterms:region`:
>A geo-political area of the described resource.

`ceterms:jurisdiction`:
>The geo-political region in which the described resource is applicable.

One points at a region **of applicability** and the other merely points to a region. It's not impossible to see the use of `ceterms:region` denoting a "geographic area from which earnings data were gathered" that implies nothing about jurisdiction of applicability.

**Comment by jkitchensSIUC** [comment]
Examples of performance measures that we will encounter in IN, NJ, WA and TX state pilot projects that will integrate employment and earnings data

Eligible Training Provider Performance Reports
For WIOA core programs, States must report the results of primary performance indicators set forth at section 116(b)(2)(A) of WIOA: 

1. the percentage of program participants who are in unsubsidized employment during the second quarter after exit from the program;
2. the percentage of program participants who are in unsubsidized employment during the fourth quarter after exit from the program; 
3. the median earnings of program participants who are in unsubsidized employment during the second quarter after exit from the program

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate Backup information:
- Background paper in Google Drive: https://drive.google.com/file/d/0B1uSTaYpjhXJZFI4ME1SYU9WR00/view?usp=sharing  
- Original review planning doc in Google Drive https://drive.google.com/file/d/0B1uSTaYpjhXJZFI4ME1SYU9WR00/view?usp=sharing
-

**Comment by siuc-nate** [comment]
Per Bob, http://credreg.net/ctdl/terms/EarningsProfile should also have ceterms:description

**Comment by siuc-nate** [comment]
See #628 for final proposal.
