### ISSUE TITLE
ceterms:EmploymentOutcomeProfile

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#377]
Crosswalk to other standards and determine additional properties. 

[ceterms:EmploymentOutcomeProfile ](http://credreg.net/ctdl/terms#EmploymentOutcomeProfilel)

**Comment by stuartasutton** [comment]
Jeanne, do we have a google doc started that lists relevant standards we should be looking at?

**Comment by jkitchensSIUC** [comment]
@stuartasutton, no Google doc yet, but will be adding one.

This is from Bob Sheets:
EmploymentOutcome  (ceterms:employmentOutcome) profile of jobs obtained with this credential by occupation and industry for a given period and area (property definition)
                The profile definition is: "The employment outcomes and related statistical information for a given credential." http://credreg.net/ctdl/terms/EmploymentOutcomeProfile 

- Credential Profiled (ceterms:credentialProfiled) profile of the credential being referenced
- Jobs Attained (ceterms:jobsObtained)  The number of jobs obtained in the region during a given timeframe.  
- Jurisdiction (ceterms: jurisdicdtion) The geo-political region in which the described resource is applicable.
- Source (ceterms:source) The source of this resource's information  (URI)
- Date Effective (ceterms:dateEffective) The effective date of the described resource content.
- Description (ceterms:description)  A short description of the resource being described

Question:  

-  Jobs Attained should be revised to referent number of credential holders who are employed as a percent of all credential holders who whose employment status was being determined in the same timeframe (e.g., employment rate).                              https://github.com/CredentialEngine/vocabularies/issues/416 
- Parallel treatment of geocoding:  See above answer – region should probably not be used
- Parallel use of source and description-  https://github.com/CredentialEngine/vocabularies/issues/417 
- Profile description implies occupation and industry but no properties addressing that Technically it's the property description, but: https://github.com/CredentialEngine/vocabularies/issues/418

**Comment by jkitchensSIUC** [comment]
Examples of performance measures that we will encounter in IN, NJ, WA and TX state pilot projects that will integrate employment and earnings data

Eligible Training Provider Performance Reports
For WIOA core programs, States must report the results of primary performance indicators set forth at section 116(b)(2)(A) of WIOA: 

1.  the percentage of program participants who are in unsubsidized employment during the second quarter after exit from the program;
2. the percentage of program participants who are in unsubsidized employment during the fourth quarter after exit from the program; 
3. the median earnings of program participants who are in unsubsidized employment during the second quarter after exit from the program

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate Backup information:
- Background paper in Google Drive: https://drive.google.com/file/d/0B1uSTaYpjhXJZFI4ME1SYU9WR00/view?usp=sharing  
- Original review planning doc in Google Drive https://drive.google.com/file/d/0B1uSTaYpjhXJZFI4ME1SYU9WR00/view?usp=sharing

**Comment by jkitchensSIUC** [comment]
The employer's preferences and hiring would also need to be verifiable actions, along the lines of the quality assurance actions.

**Comment by siuc-nate** [comment]
Per Bob, the definition of http://credreg.net/ctdl/terms/employmentOutcome references the industry and occupation to which the data applies, but http://credreg.net/ctdl/terms/EmploymentOutcomeProfile does not contain such properties.

So, we should add ceterms:industryType and ceterms:occupationType to ceterms:EmploymentOutcomeProfile.

**Comment by siuc-nate** [comment]
Per Bob, the definition should be changed from:
"The number of jobs obtained in the region during a given timeframe."

to:
"The number of credential holders who are employed as a percent of all credential holders who whose employment status was being determined in the same timeframe (e.g., employment rate)."

It might be worth wordsmithing it a bit to clarify whether "all credential holders" refers to all holders of the same credential as "number of credential holders" or if it refers to all holders of any credential (which I suspect it does not).

Perhaps something like "The number holders of a given credential who are employed, as a percentage of all holders of that credential, within a given timeframe."

Per Stuart:
Just to be certain, is this saying that the definition of jobsObtained in a given timeframe is expressed as the percentage of all holders of the credential who are employed?

**Comment by siuc-nate** [comment]
See #628 for final proposal.
