### ISSUE TITLE
Missing `audLevel` prefix in vocabulary table at top of CTDL viewer

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#378]
In the prefix table for vocabularies at the top of the CTDL viewer, we are missing the prefix `audLevel`

Prefix | Vocabulary Name | Vocabulary Title
------|-------------------|----------------|
audlevel | http://purl.org/ctdl/vocabs/audienceLevel/ | Audience Level Concept Scheme

This has (connected?) reverberations in the context file viewer. If you look at the context file for [Audience Level](http://credreg.net/ctdl/schema), you'll see that the prefix `audLevel` definition is missing in the context list making the file somewhat uninterpretable [1].

[1] http://credreg.net/ctdl/schema/context/AudienceLevel/json?release=20170224

**Comment by siuc-nate** [comment]
Was this unstable at some point? We don't seem to have created a PURL for it, either.  Anyway, I can go ahead and take care of this.

**Comment by stuartasutton** [comment]
I don't recall whether it was unstable...might have been. It's OK now.

**Comment by siuc-nate** [comment]
The item has been added.
