### ISSUE TITLE
Missing PURL for audLevel (Audience Level vocabulary)

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#379]
There is no PURL declared for the Audience Level vocabulary.

name | type | target
----|----|----
/ctdl/vocabs/audLevel/ | partial | http://credreg.net/ctdl/vocabs/AudienceLevel/

Companion issues: #378 & listing at https://github.com/CredentialEngine/vocabularies/issues/223#issuecomment-262500419

**Comment by jkitchensSIUC** [comment]
@siuc-nate are you adding this PURL?

**Comment by siuc-nate** [comment]
Yes, I will be taking care of this shortly.

**Comment by siuc-nate** [comment]
The PURL has been added.
