### ISSUE TITLE
Shouldn't the content file for the CTDL include the vocabulary terms?

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#380]
I think we may have a conceptual issue with the jsonld context file. 

Currently, we have a [context file for "CTDL"](http://credreg.net/ctdl/schema/context/json?release=20170224) and then separate context files for each of the controlled vocabularies. However, I can imagine no instance data using CTDL for describing a credential that does not also use some concepts from the controlled vocabularies? Therefore, shouldn't the CTDL context file also include all of the concept terms? Otherwise, how can such instances reference a single context file and cover everything in their instance data?

The schema.org context file includes concepts (enumerations) in its context file. Granted, schema.org constrains everything to one namespace, but nevertheless, I'm wondering whether all of our classes (including concepts in concept schemes) shouldn't everything be in one grand context file.

Could this possibly account for older data in WorkIt that had no context declarations of prefixes for controlled vocabularies...they weren't in the master context file?

Related issue at https://github.com/schemaorg/schemaorg/issues/990

**Comment by siuc-nate** [comment]
The context file you linked to includes the vocabularies - did you intend to link to something else?

**Comment by jkitchensSIUC** [comment]
@mparsons1953 @siuc-nate yes, the context file includes everything so it includes concept schemes.  @siuc-nate did you get with @mparsons1953 and go over this?

**Comment by siuc-nate** [comment]
I am not aware of any issues @mparsons1953 has with the context file.

@stuartasutton is something still missing?

**Comment by stuartasutton** [comment]
Apparently, it's all there, so this issue can be closed.
