### ISSUE TITLE
Expand URI prefixes in definition tables

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#381]
@siuc-nate, would it be difficult to expand the prefix'd URIs in the definition tables in the viewers to their full URI? We need to add a little insurance that people using the properties and classes explicitly see and use their full URI. This is a little (a lot?) of insurance that people don't simply grab the URL from their browser and use it for the class or property URI. 

The result of this change would look like the following:
<table>
<tr><td colspan="2">ceterms:accreditedBy</td></tr>
<tr><td>URI</td><td>http://purl.org/ctdl/terms/accreditedBy</td></tr>
<tr><td>Label</td><td>Accredited By</td></tr>
</table>

...and for a vocabulary concept:

<table>
<tr><td colspan="2">inputType:Governments</td></tr>
<tr><td>URI</td><td>http://purl.org/ctdl/vocabs/inputType/Governments</td></tr>
<tr><td>Label</td><td>Governments</td></tr>
</table>

**or even ...(prefix missing in header row)**

<table>
<tr><td colspan="2">accreditedBy</td></tr>
<tr><td>URI</td><td>http://purl.org/ctdl/terms/accreditedBy</td></tr>
<tr><td>Label</td><td>Accredited By</td></tr>
</table>

...and for a vocabulary concept:

<table>
<tr><td colspan="2">Governments</td></tr>
<tr><td>URI</td><td>http://purl.org/ctdl/vocabs/inputType/Governments</td></tr>
<tr><td>Label</td><td>Governments</td></tr>
</table>
I understand that all the user needs to do is look at the prefix and go to the table to expand it to a full URI, however, the added insurance could reduce headaches down the road when we see things like the following in code:

```
http://credreg.net/ctdl/vocabs/Audience/#accreditedBy
http://credreg.net/ctdl/vocabs/Audience/#Governments
```

I'm asking this question because I'm looking at some user code this AM and grabbing the URL from their browser is exactly what happened.

**Since this affects nothing substantively, this is a change that could simply be done at any time.**

**Comment by siuc-nate** [comment]
It wouldn't be very hard to make the changes you describe.  I will try to get that done today.

**Comment by siuc-nate** [comment]
A little late on this, but, I have made a few updates: http://credreg.net/ctdl/terms

- The full URI is now displayed in the URI row
- A "Shorthand URI" row displays the prefix:Value short URI (not sure if we want to keep this - I find it useful)
- There was an issue where the page would not jump to vocabulary terms on load. This has been fixed

I am hesitant to remove the prefix from the URI displayed in the orange header of each table, particularly when it comes to vocabulary terms, since it serves to group the terms together in a meaningful and useful way.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate can this be closed?

**Comment by stuartasutton** [comment]
Yes, I've checked a few of the tables and all looks good.
