### ISSUE TITLE
ceterms:RevocationProfile

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#382]
ceterms:RevocationProfile http://credreg.net/ctdl/terms#revocation

Revocation profile is specific to the credential to which it is attached (i.e., "here is how to lose this credential") rather than ("here is how to lose any credential we offer"). Is such data common enough to merit changing the profile?

This makes sense for certifications that each have some criteria for revocation including not meeting renewal requirements.  It doesn’t work for other types that could revoke based on org-wide policy such as cheating.

**Comment by siuc-nate** [comment]
Is this something we can put to the TAC? It would be good to have some sense of whether most data about revocation is specific to credentials or whether it tends to be blanket/organization-level stuff.

**Comment by stuartasutton** [comment]
Is this one of those places where we'd be better off letting experience guide any next steps? We do know that the revocation of a specific credential is currently and adequately covered [e.g. [1]](http://www.ctc.ca.gov/educator-discipline/FAQ.html). The definition could easily be applicable across an array of credentials:

> 	Processes and criteria for ending (revoking) the validity or operation of an awarded credential.

Jeanne, can we point to one or two actual instances where revocation rises to the level of cross-institution 'manifest' like we have with costs and conditions?  If we have actual cases (that aren't fringe), then a TAC query isn't likely to provide anything past what is known though such actual cases.

**Comment by siuc-nate** [comment]
If anything I would just add ceterms:revocation to ConditionManifest rather than create another manifest profile.

**Comment by siuc-nate** [comment]
Per Jeanne - we don't have any data that currently suggests a need for this. Closing this issue.
