### ISSUE TITLE
Create meta namespace

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#383]
This will exist outside of CTDL but be used by it for documentation purposes.

**Comment by stuartasutton** [comment]
That is correct. It would be outside the CTDL. However, there is no reason it should not have the look and feel of the CTDL property/class viewer so there is no new learning curve for users in building a mental model of how the definitions tables are interpreted...they are, after all, just property and class definitions in the meta namespace (http://archive.org/services/purl/purl/ctdl/meta/).

**Comment by siuc-nate** [comment]
What would these properties and classes be?

Also, is this issue the same as/covered by #385 ?

**Comment by stuartasutton** [comment]
Yes this is related specifically to #385 and specifically to https://github.com/CredentialEngine/vocabularies/issues/385#issuecomment-300280609

**Comment by siuc-nate** [comment]
The new schema management system I'm working on will accommodate a "meta" schema in addition to CTDL and CTDL-ASN.

**Comment by siuc-nate** [comment]
This has been taken care of.
