### ISSUE TITLE
Instances of manifest descriptions (Condition & Cost) need URI

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#384]
Instances of both `CostManifest` and `ConditionManifest` need to be identified by URI and not as blank nodes since they will, by nature, be referenced across graphs (i.e., from multiple credentials referencing the same manifests.  So these need to join the list of entities identified by URI (`Credential` subclasses, `Agent` subclasses, `LearningOpportunityProfile`, `AssesmentProfile` - https://github.com/CredentialEngine/CredentialRegistry/issues/31).

I **still** have a lurking suspicion that ConditionProfile should also join the list.

**Comment by leolara** [comment]
@cwd-mparsons @siuc-nate this would mean that they should have their own JSON schema and be added to the registry as a new @type set?

**Comment by cwd-mparsons** [comment]
@leolara @siuc-nate 
The short answer is yes, these will be top level classes with their own schema. The condition manifest is in pending status, and so is not in the Json-ld schema generated from credReg.net. This will be part of the next release.

**Comment by jkitchensSIUC** [comment]
Both  CostManifest and ConditionManifest must to be identified by URI and not as blank nodes.  

Posting another issue to keep open whether or not ConditionProfile and CostProfile must also be identified by URI.

**Comment by jkitchensSIUC** [comment]
@siuc-nate @cwd-mparsons @leolara if this is documented with the CER Guide page http://credreg.net/registry and validated as stated for ConditionManifest and the forthcoming CostManifest this will have been completed.
