### ISSUE TITLE
Enable Assessments and Learning Opportunities to have additional connection types

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#386]
Currently, [Credential](http://credreg.net/ctdl/pending#Credential) has the following "connection" properties:
- requires
- recommends
- preparationFrom
- advancedStandingFrom
- isRequiredFor
- isRecommendedFor
- isPreparationFor
- isAdvancedStandingFor
- commonConditions

However, [AssessmentProfile](http://credreg.net/ctdl/pending#AssessmentProfile) and [LearningOpportunityProfile](http://credreg.net/ctdl/pending#LearningOpportunityProfile) only have
- requires
- recommends
- commonConditions

Technically, all of the connection properties are indirectly available to AssessmentProfile and LearningOpportunityProfile via the "commonConditions->ConditionManifest" route.  However, this leaves us unable to _directly_ define relationships such as the one defined [here](http://www.nocti.org/PDFs/JobReady/4143_Health_Assisting.pdf) between the "Today's Class" curriculum and the assessment being described. Specifically:
```
(NOCTI Health Assisting [Assessment Profile])-[preparationFrom]->(Today's Class [Learning Opportunity Profile])
```

So, I propose that the **domains and ranges** of the properties below be extended to include ceterms:AssessmentProfile and ceterms:LearningOpportunityProfile:
- preparationFrom
- advancedStandingFrom
- isRequiredFor
- isRecommendedFor
- isPreparationFor
- isAdvancedStandingFor

**Comment by stuartasutton** [comment]
I've no objection.

**Comment by siuc-nate** [comment]
Action to be taken:
For each of the properties below, Add both **rdfs:domain** and **rdfs:range** of **ceterms:AssessmentProfile** and **ceterms:LearningOpportunityProfile**:
- preparationFrom
- advancedStandingFrom
- isRequiredFor
- isRecommendedFor
- isPreparationFor
- isAdvancedStandingFor

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
