### ISSUE TITLE
Add new audience vocabulary terms to explicitly cover military spouses and dependents

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#387]
While working on CostManifest, I have been attempting to fit various institutions' costs into the existing CostProfile structure.  While this does work, there are some gaps.  One of these that I have seen in a few places are cases where current and former military, sometimes including their spouses, and sometimes including their dependents, get different prices.

[Currently](http://credreg.net/ctdl/terms/Audience) we have audience:CurrentMilitary and audience:FormerMilitary.  FormerMilitary mentions that it "May include qualified spouses and dependents"; CurrentMilitary does not mention this.

Given that prices may be different for a Current/Former Military person, their spouse, and/or their dependent ([example here](http://www.kaplanuniversity.edu/information-technology/cybersecurity-bachelor-degree.aspx)), we need to define those additional audiences explicitly.

To this end, I think we need these additional Audience vocabulary terms:
- audience:CurrentMilitarySpouse
- audience:CurrentMilitaryDependent
- audience:FormerMilitarySpouse
- audience:FormerMilitaryDependent

This should cover the gamut.  We will of course need to setup proper definitions and such.

It may also be worth either adding the "May include qualified military spouses and children." usage note to CurrentMilitary _or_ removing it from FormerMilitary (if we add the above terms), for consistency.

**Comment by stuartasutton** [comment]
I think the addition of these four properties is acceptable. I would **remove** the "May include qualified spouses and dependents" from the definition of `FormerMilitary`.

**Comment by siuc-nate** [comment]
Proposed Changes:

**Remove:**
> **Subject:** ceterms:FormerMilitary
> **Predicate:** vann:usageNote
> **Object:** "May include qualified military spouses and children."

**Create:**
**URI:** audience:CurrentMilitarySpouse
**Label:** Current Military Spouse
**Definition:** Spouse of a current member of a nation's military.
**In scheme:** ceterms:Audience

**URI:** audience:CurrentMilitaryDependent
**Label:** Current Military Dependent
**Definition:** Dependent (usually a child) of a current member of a nation's military.
**In scheme:** ceterms:Audience

**URI:** audience:FormerMilitarySpouse
**Label:** Former Military Spouse
**Definition:** Spouse of a veteran of a nation's military.
**In scheme:** ceterms:Audience

**URI:** audience:FormerMilitaryDependent
**Label:** Former Military Dependent
**Definition:** Dependent (usually a child) of a veteran of a nation's military.
**In scheme:** ceterms:Audience

**Comment by stuartasutton** [comment]
OK for me.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.

**Comment by cwd-mparsons** [comment]
These have been updated in the code tables.
