### ISSUE TITLE
Loosen the definition of ceterms:costDetails

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#389]
I propose the following change to the definition of [ceterms:costDetails](http://credreg.net/ctdl/terms/costDetails):
Current: "A resource containing human-readable, in-depth information about the cost of the credential."
Proposed: "A resource containing human-readable, in-depth information about the cost(s) being described."

My reasoning is:
- costDetails is a property of CostProfile, thus there is no (direct) "credential" to reference
- CostProfile is used for much more than just credentials
- costDetails does not point to the cost of something; rather, it points to information about the cost(s) themselves
- I would like to use costDetails in CostManifest as well; this slightly looser definition will enable that

Thoughts?

**Comment by stuartasutton** [comment]
Makes sense and is not likely to cause any harm to existing systems using the term.

**Comment by siuc-nate** [comment]
Action to be taken:

**Remove:**
> **Subject:** ceterms:costDetails
> **Predicate:** rdfs:comment
> **Object:** "A resource containing human-readable, in-depth information about the cost of the credential."

**Add:**
> **Subject:** ceterms:costDetails
> **Predicate:** rdfs:comment
> **Object:** "A resource containing human-readable, in-depth information about the cost(s) being described."

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
