### ISSUE TITLE
Should CostProfile and/or ConditionProfile be identified by URI as top level entities?

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#390]
Per Stuart's suggestion/question, we need to determine whether or not CostProfile and/or ConditionProfile need to be referenced externally by other entities, or if their respective manifest profiles are sufficient.

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton wasn't this nailed down last week?  Let's make sure it's 100% clear in both of these guides. The guides need to identify the requirement for URIs.  

This impacts the Registry Guide http://credreg.net/registry - Needs to have definitive information about URIs.  Does the CTDL Guide also need a new section for URIs possibly a section 1.1? Or under Primary Classes?

**Comment by stuartasutton** [comment]
Jeanne, here's a little context. Back in mid-November, I posited that `ceterms:ConditionProfile` could have some utility identified by URI as opposed to being a bnode. That would make them referencable outside the graph in which they are defined.  At the level of the vocabulary and records in the CER, there is no need for anything but a bnode.  You can tell in a graph model whether a particular entity could stand as a bnode if it only has **one arrow pointing to it**. In the description set of a Credential in the CER, that is true--i.e. **only one arrow pointing to the profile**. 

So, this is probably not so much a CER matter as it is a CTDL matter. In the wild, it would not be unreasonable for some third party to reference an instance of `ceterms:ConditionProfile` such as follows:

![2017-05-01-condition_profile_uri](https://cloud.githubusercontent.com/assets/2939046/25594790/fcf10f24-2e76-11e7-8f49-bfa071ac8b7f.png)

In the figure above, the Organization B relating its learning opportunity of to the learning opportunity of Organization A from outside the CER is perfectly reasonable. My point at the time was that Organization B might want to assert that it conforms to the remaining conditions of Organization A's condition set.

Anyway, in the wild, people will or will not identify an instance of `ceterms:ConditionProfile` they are creating by URI as they see fit for their needs. This is in the spirit of an unconstrained CTDL supporting many uses. Of course, the CER has every right to say 'no' we aren't supporting  `ceterms:ConditionProfile` instances identified by URI.

**Comment by siuc-nate** [comment]
If it's outside the CER, then anything could have a URI, so, I suppose there's nothing we can do to affect or control this.  Within the CER context, however, I do not think we should enable single ConditionProfiles or CostProfiles to be referenceable on their own.

**Comment by siuc-nate** [comment]
Per our 5/9/2017 call, we will close this for now.
