### ISSUE TITLE
Update definition of ceterms:ctid to accomodate changes to the usage of CTID

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#393]
See https://github.com/CredentialEngine/CredentialRegistry/issues/66

**Comment by stuartasutton** [comment]
Draft updates to definition and usage note of [`ceterms:ctid`]():

### Definition

##### Delete
>A globally unique Credential Transparency Identifier (CTID) issued by the Credential Registry Service (CRS) by which the creator/owner/provider of a credential recognizes the credential in transactions with the external environment (e.g., in verifiable claims involving the credential).
##### Add
>A globally unique Credential Transparency Identifier (CTID) by which the creator/owner/provider recognizes the resource in transactions with the external environment (e.g., in verifiable claims involving the credential).

### Usage Note

#### Delete
>A CTID is resolved through the CRS returning the Credential Registry data describing the identified credential. The CTID is the equivalent of a version identifier for the credential. Different versions of a credential are considered distinct expressions and each must be assigned its own CTID. Each version of a credential can have only one CTID assigned by the Credential Registry Service (CRS) upon registration with the Credential Registry.  However, a single version of a credential may have distinct identifier values for both the ctid property and the credentialId property. In such a case both identifiers will be recognized by the credential creator/owner/provider in transactions with the external environment.

#### Add

>The CTID is the equivalent of a version identifier for the resource. Different versions of a resource are considered distinct expressions and each must be assigned its own CTID. Each version of a resource can have only one CTID assigned.  However, a single version of a resource may have distinct identifier values for both the ctid property and the credentialId property. In such a case both identifiers will be recognized by the resource creator/owner/provider in transactions with the external environment.

**Comment by siuc-nate** [comment]
We will also extend the range of ctid to include
- ceterms:AssessmentProfile
- ceterms:LearningOpportunityProfile
- ceterms:CredentialOrganization
- ceterms:QACredentialOrganization
- ceterms:ConditionManifest
- ceterms:CostManifest

**Comment by siuc-nate** [comment]
All of these changes **except the addition of CostManifest to the domain** have been made in pending CTDL and noted in history tracking. I will add the reference to CostManifest once CostManifest itself has been added.

Leaving this issue open until that time.

**Comment by siuc-nate** [comment]
This has now also been added to CostManifest.
