### ISSUE TITLE
Create a class that allows pointing to entities that do not have known metadata/identifiers

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#394]
Referring to https://github.com/CredentialEngine/CredentialRegistry/issues/37

Summary: The CTDL relies heavily on being able to point to entities by their URI, which in turn requires (or at least implies) the existence of a CTID ( per #393 ).  However, especially early on, most of this data will not exist in any referenceable way.

This problem can be addressed, I think, by either using AlignmentObject (or some subclass thereof) that enables pointing to an entity in a looser way.  For instance:
```
{
   "@type": "ceterms:Certificate",
   "ceterms:accreditedBy": [
      { "@id": "http://credentialengineregistry.org/resources/ce-[UUID]" }
   ]
}
```
This works if the entity `http://credentialengineregistry.org/resources/ce-[UUID]` exists in the registry.  If it does not, however, then an alternative is needed.  For example:
```
{
   "@type": "ceterms:Certificate",
   "ceterms:accreditedBy": [
      {
         "@type": "ceterms:CredentialAlignmentObject",
         "ceterms:targetNodeName": "Some third party organization",
         "ceterms:targetNode": "http://somethirdpartyorganization.org"
      }
   ]
}
```

I believe this solves the primary issue, though it does beg the question of whether or not "CredentialAlignmentObject" is appropriate or if a new subclass is needed.

This would also require extending the range of all properties that currently point to a top-level object to include this (new?) alignment object.

@stuartasutton Thoughts?

**Comment by stuartasutton** [comment]
Nate, this is part of a bundle of issues that have to be resolved together and need discussion before people start down an implementation path. As you note, this relates to issue https://github.com/CredentialEngine/CredentialRegistry/issues/88 and now issue https://github.com/CredentialEngine/CredentialRegistry/issues/37. 

### Using `ceterm:CredentialAlignmentObject`

While probably sounding like an annoying broken record, the solution to referencing an organization, credential, learning opportunity or assessment entity not in the CER is absolutely not [`ceterm:CredentialAlignmentObject`](http://credreg.net/ctdl/terms/CredentialAlignmentObject). The range of `ceterm:CredentialAlignmentObject` is **always** a framework which is clearly defined for us:

>(Definition) "An alignment to a credentialing framework." (Comment) "Used to describe the alignment of a resource in the credentialing environment to frameworks such as concept schemes, specialized controlled lists, and competencies."

References to other credentials or organizations are simply **not** "frameworks". We can't use `ceterm:CredentialAlignmentObject` just because it seems to provide an attractive 'data structure' while ignoring its definition. Subclassing it won't help since the subclass is nevertheless a 'kind of' the superclass--i.e., a framework.

### References to Organizations and Credentials

Just because there is no official description of an organization in the CER does ***not*** mean that a credential wanting to say it has been accredited by such an organization can't do so. They abnsolutely can...even if CER rules say that they cannot create an official instance of `ceterms:QACredentialOrganization` for that body. Below is an example where the accreditor is referenced quite simply using a bnode. 

#### Turtle
```
@prefix ceterms: <http://purl.org/ctdl/terms/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://credentialEngineRegistry.org/resources/CE-D680FE7F-CF61-41DC-841E-3A2C91BF96BC> a ceterms:BachelorDegree ;
    ceterms:ctid "CE-D680FE7F-CF61-41DC-841E-3A2C91BF96BC" ;
    ceterms:name "Brewing Certificate"@en-US ;
    ceterms:accreditedBy [ a ceterms:QACredentialOrganization ;
        ceterms:name "Northwest Region Accreditor of Breweries"@en-US ;
        ceterms:subjectWebpage <http://NorthWestBrewers/accreditation> ] .
```
#### JSONLD

```
{
  "@context": {
    "ceterms": "http://purl.org/ctdl/terms/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@graph": [
    {
      "@id": "http://credentialEngineRegistry.org/resources/CE-D680FE7F-CF61-41DC-841E-3A2C91BF96BC",
      "@type": "ceterms:BachelorDegree",
      "ceterms:ctid": "CE-D680FE7F-CF61-41DC-841E-3A2C91BF96BC",
      "ceterms:name": {
        "@language": "en-US",
        "@value": "Brewing Certificate"
      },
      "ceterms:accreditedBy": {
        "@id": "_:ub14bL9C26"
      }     
    },
    {
      "@id": "_:ub14bL9C26",
      "@type": "ceterms:QACredentialOrganization",
      "ceterms:name": {
        "@language": "en-US",
        "@value": "Regional Accreditor of Breweries"
      },
      "ceterms:subjectWebpage": {
        "@id": "http://NorthWestBrewers/accreditation"
      }
    }
  ]
}
```
Also, in the wild, there would be no issue of identifying by URI a description of an organization found in dbpedia, Fastbase or some other RDF store. In a linked data world, who says that the URI identifying an organization has to be to a record in the CER?

**Comment by siuc-nate** [comment]
Then perhaps we need a _super_ class of AlignmentObject that contains useful elements of its structure without the "alignment to a framework" constraint.

Anyway, the publishing structure you suggest would fail against the validation mechanism we're using, as it does not account for a `@graph` object.  The registry also, as far as I know, lacks the capacity to handle "fake" versions of top-level entities (i.e., those identified with bnodes).  In essence, the data needs to be inside of the "main" record - which I suppose would be possible, but it may then be confusing to have cases where organization objects (or other top-level objects) are inside of other things instead of reliably being at the top level.

However, this sort of replicates what I was proposing with AlignmentObject anyway - providing a small record that works more as a pointer than as an actual instance of something - but, I am leery of doing it this way since it muddies the reliability of what class shows up where in the data.  The reason I would use some AlignmentObject-like class instead is because a developer would know for sure that that is a pointer to something else, rather than a record itself, which makes the data easier to understand.

**Comment by stuartasutton** [comment]
OK, but we need to discuss this further because the result I suggested is
standard RDF...where a bnode is not a "fake" version of anything.

**Comment by siuc-nate** [comment]
Sorry, I meant fake in the sense that it is not created, owned, or controlled by the organization it is referencing, nor is it intended to be an authoritative record of such an organization, merely a pointer that borrows the existing organization class.

**Comment by stuartasutton** [comment]
Nate, let's get this on the agenda for Tuesday's call. The "thing" being referenced is nonetheless a member of the class Credential or LearningOpportunity etc.

**Comment by stuartasutton** [comment]
Setting aside how the current solution stack handles this, I'm puzzled how the following code snippets are **technically** any different as json : 

### Yours

```
{
   "@type": "ceterms:Certificate",
   "ceterms:accreditedBy": [
      {
         "@type": "ceterms:CredentialAlignmentObject",
         "ceterms:targetNodeName": "Some third party organization",
         "ceterms:targetNode": "http://somethirdpartyorganization.org"
      }
   ]
}
```
### Mine 
```
{
   "@type": "ceterms:Certificate",
   "ceterms:accreditedBy": [
      {
         "@type": "ceterms:QACredentialOrganization",
         "ceterms:name": "Some third party organization",
         "ceterms:subjectWebpage": "http://somethirdpartyorganization.org"
      }
   ]
}
```
They are technically not different as code, but miles apart when it comes to accuracy. The think being referenced by `ceterms:accreditedBy` in both snippets is a `ceterms:QACredentialOrganization`. One correctly identifies it as such and the other tries to mask its identity by calling it a different kind of thing (hoping the end user will 'get' that the value is actually a `ceterms:QACredentialOrganization`...we just can't aren't calling it what it is). In the service of transparency, trying to mask the identity of this QACredentialOrganizaiton to machines as something else, doesn't diminish any potential negative impact of the assertion (which may or may not be true).

As bNodes, neither describes a referencable entity outside the confines of this particular instance of `ceterms:Certificate`.

**Comment by stuartasutton** [comment]
I think that we need to be clear that the party making these kinds of assertions )`accreditedBy`) is not wanting to create a description of the object entity...i.e., not wanting to create a full description of a QA organization. They are just needing to identify the referent entity.  If there were a reliable URI of that entity anywhere, it could be used. It would not need to be to an resource in the CER. E.g., if someone wanted reference Stanford, they could do so by providing a LinkedIn or dbpedia URI (e.g., see http://dbpedia.org/page/Stanford_University (note formats))...

**Comment by siuc-nate** [comment]
I understand what you're saying in an RDF sense, but I am trying to account for the CER's management of individual records.  As I mentioned in my previous post, embedding the data directly in the record is perhaps a workable solution, but I am still hesitant to suggest that any piece of JSON calling itself an Organization (or some other top level thing) should not be the authoritative record of that thing.

I'm also looking at it from an implementation standpoint.  To that end, I am not looking at it as a comparison between
```
{
   "@type": "ceterms:Certificate",
   "ceterms:accreditedBy": [
      {
         "@type": "ceterms:CredentialAlignmentObject",
         "ceterms:targetNodeName": "Some third party organization",
         "ceterms:targetNode": "http://somethirdpartyorganization.org"
      }
   ]
}
```
and
```
{
   "@type": "ceterms:Certificate",
   "ceterms:accreditedBy": [
      {
         "@type": "ceterms:QACredentialOrganization",
         "ceterms:name": "Some third party organization",
         "ceterms:subjectWebpage": "http://somethirdpartyorganization.org"
      }
   ]
}
```
but rather a comparison between
```
{
   "@type": "ceterms:Certificate",
   "ceterms:accreditedBy": [
      {
         "@id": "http://credentialengineregistry.org/resources/ce-623ffae7-a738-4de4-823b-029237fa441c"
      }
   ]
}
```
and
```
{
   "@type": "ceterms:Certificate",
   "ceterms:accreditedBy": [
      {
         "@type": "ceterms:CredentialAlignmentObject",
         "ceterms:targetNodeName": "Some third party organization",
         "ceterms:targetNode": "http://somethirdpartyorganization.org"
      }
   ]
}
```

Note that in the "real" case (that is, the case where the record does exist and is pointed to via `@id`), no information is given about what the resource is either. That piece of JSON, the block with an `@id` is effectively a pointer, just as the pseudo-alignment object would be.

**Comment by siuc-nate** [comment]
Per our 5/16/2017 call:

We will explore solving this problem at the implementation level by using a class (not a CTDL class, but a class within the implementing system) that accomplishes the goals above.  Such a class would contain id, name, description, subjectWebpage, and socialMedia properties (possibly others as needed).  This would require a change to the JSON validation schema used by the registry, but these constraints should prevent problems with over-describing an organization since this data will be embedded within the JSON record.

In other words:
- We should avoid this approach: https://github.com/CredentialEngine/CredentialRegistry/issues/37#issuecomment-301165955
- We should require publishers to update their records directly rather than provide an indirect "resolver" service
- We should allow publishing a record that looks like either of the below:
```
{
   "@type": "ceterms:Certificate",
   "ceterms:accreditedBy": [
      {
         "@type": "ceterms:QACredentialOrganization",
         "ceterms:name": "Some third party organization",
         "ceterms:subjectWebpage": "http://somethirdpartyorganization.org"
      }
   ]
}
```
or
```
{
   "@type": "ceterms:Certificate",
   "ceterms:accreditedBy": [
      {
         "@id": "http://credentialengineregistry.org/resources/ce-623ffae7-a738-4de4-823b-029237fa441c"
      }
   ]
}
```
- Consuming systems will have to be advised to inspect the identifier to know what to do with the data returned; `http://credentialengineregistry.org/resources/ce-623ffae7-a738-4de4-823b-029237fa441c` and `http://dbpedia.org/page/Stanford_University` may both be about the same organization, but will return significantly different data with different schemas, and the consuming system needs to be ready for this.
- We need to consider how this approach impacts the various use cases such as
   - Publishing directly
   - Publishing via workit editor
   - Publishing via easy publish/registry assistant API
   - Webpage crawler/screen scrape publishing

**Comment by stuartasutton** [comment]
To clarify: Are we in a hold pattern here as to the vocabulary while we determine how the CER will manage third-party organizations (per #37)? In other words, have we settled that it's not a CTDL/RDF problem, but an implementation problem with the CER? I'd like to consider the CTDL issue closed. I.e., the following are valid:

```
{
   "@type": "ceterms:Certificate",
   "ceterms:accreditedBy": [
      {
         "@type": "ceterms:QACredentialOrganization",
         "ceterms:name": "Some third party organization",
         "ceterms:subjectWebpage": "http://somethirdpartyorganization.org"
      }
   ]
}
``` 
and
```
{
   "@type": "ceterms:Certificate",
   "ceterms:accreditedBy": [
      {
         "@id": "http://credentialengineregistry.org/resources/ce-623ffae7-a738-4de4-823b-029237fa441c"
      }
   ]
}
```
and
```
{
   "@type": "ceterms:Certificate",
   "ceterms:accreditedBy": [
      {
         "@id": "http://dbpedia.org/resource/Stanford_University"
      }
   ]
}
```

**Comment by siuc-nate** [comment]
If we're not creating a pointer class (which I still feel like we may need), then I think this issue is closed for now as far as CTDL is concerned.  It does need to continue, however, in https://github.com/CredentialEngine/CredentialRegistry/issues/37
