### ISSUE TITLE
Record stabilization of terms

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#395]
With today's CTDL release, the following terms have had their vs:term_status changed from vs:pending to vs:stable:

- ceterms:commonConditions
- ceterms:corequisite
- ceterms:endDate
- ceterms:evidenceOfAction
- ceterms:financialAssistance
- ceterms:geoURI
- ceterms:hasConditionManifest
- ceterms:inLanguage
- ceterms:startDate
- claimType:VerifiedClaim
- claimType:QualityAssuranceClaim
- ceterms:ConditionManifest
- ceterms:CredentialPerson

These changes need to be recorded in history tracking.

@stuartasutton These changes belong with today's release, not the next one, correct? I ask because these terms already have it recorded in their history for this release that their status was set to vs:pending. Do those history declarations get replaced, or added to? (If added, how would a consumer of the data know whether the current status is pending or stable?)

**Comment by stuartasutton** [comment]
@siuc-nate, I'm not sure I understand the question. Whatever the answer, it should be done with this release.

Are these facts accurate using ceterms:commonConditions as the example?

1. The property ceterms:commonConditions existed before today's release with a status of "pending"; and
2. With this release, the status changed to "stable".

If that is the case, then you'd have a change set for delete "pending" and add "stable".

But I fear I may be misinterpreting the question.

**Comment by siuc-nate** [comment]
No, I think that answers my question - I mostly just wanted to confirm that two changesets within the same release for the same property was the correct way to do it.  Thanks.

**Comment by stuartasutton** [comment]
Nate, I think I am still a bit confused. If there is a flip flop in the same pending...then there isn't anything for a release. For example, if a term is changed in pending from unstable to stable and then changed back to unstable in the same iteration of pending, then there has simply been no change.

**Comment by siuc-nate** [comment]
No, Unstable isn't involved - the change goes from:
[Not existing] -> [pending] -> [stable]
With all of these (or more specifically the last two) happening within the same release.

In other words, before the release, the terms were documented by showing up in the pending metadata viewer with a status of pending.  When that became the live release, they went from pending to stable - but all of this was still within the context of the one single release.

So a status change from nothing -> pending and from pending -> stable both get recorded for the same release, unless I'm missing something?

**Comment by stuartasutton** [comment]
Personally, I'd go from nothing to pending. Since nothing isn;t a status, I'd just go to stable (i.e., just an add stable).

**Comment by siuc-nate** [comment]
These changes have been made.
