### ISSUE TITLE
Add "Graduation Fee" as a Cost Type

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#397]
Per a suggestion here:
https://trello.com/c/XtAVU50c/86-we-are-frequently-running-into-institutions-with-graduation-fees-is-this-something-that-is-in-ctdl-where-it-would-be-possible-to
"We are frequently running into institutions with graduation fees. Is this something that is in CTDL where it would be possible to add this option?"

The proposal is to add the following term:
**URI:** costType:GraduationFee
**Label:** Graduation Fee
**Definition:** Cost for graduating from an educational program.
**In Scheme:** ceterms:CostType

**Comment by stuartasutton** [comment]
This sounds reasonable.

P.S. I do not seem to have access to this trello board.

**Comment by stuartasutton** [comment]
I just reread the definition of GraduationFee and wonder if it won't be frequently misinterpreted as an aggregate set of fees for graduating. Perhaps:

> A separate fee charged for graduating from an educational program.

Or something like that.

**Comment by siuc-nate** [comment]
Action to be taken:

**Add:**
**URI:** costType:GraduationFee
**Label:** Graduation Fee
**Definition:** A separate fee charged for graduating from an educational program.
**In Scheme:** ceterms:CostType

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in history tracking.
