### ISSUE TITLE
Review Cost Type vocabulary concepts

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#398]
All of the concepts for [CostType](http://credreg.net/ctdl/terms/CostType) are currently marked as vs:unstable.

We need to **review** them and change **the ones we want to keep** to vs:stable:
- costType:AggregateCost
- costType:Application
- costType:BackgroundCheck
- costType:EnrollmentFee
- costType:LearningResource
- costType:Meals
- costType:OptionalCharges
- costType:ProcessingFee
- costType:ProgramSpecificFee
- costType:ReexaminationFee
- costType:RenewalFee
- costType:ReschedulingFee
- costType:RoomOrResidency
- costType:ScoringFee
- costType:StandaloneAssessment
- costType:StudentServicesFee
- costType:TechnologyFee
- costType:Tuition

**Comment by stuartasutton** [comment]
Yes. I can't even recall why they are marked unstable.

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton all of the above costs are legit. They are based on the numerous partner cost information looked at.  We spent quite a bit of time identifying these costs and ensuring each cost was uniquely defined.  The entire cost profile was marked as unstable at the time of the first release.  All details about these costs were documented in Google Drive https://docs.google.com/spreadsheets/d/19--mCccXkLeCxxQ74c1lx5_k31FCIyk-d-PRqHgQqls/edit?usp=sharing . There are likely additional documents and this was documented in GitHub.

**Comment by siuc-nate** [comment]
Fair enough.

So, the action to be taken is to change the **vs:term_status** of each of the properties below from **vs:pending** to **vs:stable**
- costType:AggregateCost
- costType:Application
- costType:BackgroundCheck
- costType:EnrollmentFee
- costType:LearningResource
- costType:Meals
- costType:OptionalCharges
- costType:ProcessingFee
- costType:ProgramSpecificFee
- costType:ReexaminationFee
- costType:RenewalFee
- costType:ReschedulingFee
- costType:RoomOrResidency
- costType:ScoringFee
- costType:StandaloneAssessment
- costType:StudentServicesFee
- costType:TechnologyFee
- costType:Tuition

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
