### ISSUE TITLE
Remove Competency and CompetencyFramework from domain of inLanguage

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#399]
In #338, ceterms:Competency and ceterms:CompetencyFramework were erroneously added to the domain of ceterms:inLanguage.  Those two classes are intended to be propertyless placeholder classes akin to ceterms:Assessment and ceterms:LearningOpportunity.

Proposed action:

**Remove:**
> **Subject:** ceterms:inLanguage
> **Predicate:** rdfs:domain
> **Object:** ceterms:Competency

**Remove:**
> **Subject:** ceterms:inLanguage
> **Predicate:** rdfs:domain
> **Object:** ceterms:CompetencyFramework

**Comment by stuartasutton** [comment]
This looks fine to me.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in history tracking.
