### ISSUE TITLE
Fix typo in definition of ceterms:isRecommendedFor

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#400]
http://credreg.net/ctdl/terms/isRecommendedFor
The definition incorrectly says "resource**s**" instead of "resource".

Proposed action:

**Remove:**
> **Subject:** ceterms:isRecommendedFor
> **Predicate:** rdfs:comment
> **Object:** "The resources being described is recommended for the resource being referenced."

**Add:**
> **Subject:** ceterms:isRecommendedFor
> **Predicate:** rdfs:comment
> **Object:** "The resource being described is recommended for the resource being referenced."

@stuartasutton this seems like a trivial change. Any problem with going forward right away?

**Comment by stuartasutton** [comment]
No problem. It is trivial correction, can be changed immediately, and need not be documented in the change history.

**Comment by siuc-nate** [comment]
Done. Thanks, Stuart.

@cwd-mparsons please update this in the database code tables. Thanks.

**Comment by cwd-mparsons** [comment]
The database code tables have been updated.
