### ISSUE TITLE
Caution on using inverse properties

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#402]
It's worth reading Dan Brickley's comment on the (current) approach of schema.org in handling inverse properties; e.g.:

> `Person==birthPlace==>Place`
`Place==birthPlaceOf==>Person`

https://github.com/schemaorg/schemaorg/issues/1156#issuecomment-302864071

Dan's argument of the cost in bloating the vocabulary with a mass of inverse properties delcarations has to be considered. Also, as he illustrates, inverses can be handled at the point of use:

```
{ 
  "@context": "http://schema.org/",
  "@type": "Place",
  "name": "Bognor Regis",
  "@reverse": 
    { 
      "birthPlace": 
         {
          "@type": "Person",
          "name": "Jane Doe"
         } 
    }
}
```

In addition, in formal schema, use of `owl:inverseOf` to achieve this end through explicit declaration of two properties has its dangers--e.g., what if `Place` doesn't agree :-)

**Comment by siuc-nate** [comment]
@stuartasutton Given the changes we made in #445, can we close this?

**Comment by stuartasutton** [comment]
Yes. It's main value is in showing how schema.org uses @reverse.
