### ISSUE TITLE
Add new properties: ceterms:teaches and ceterms:assesses

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#403]
We have instances in Workit where we use `targetCompetency` referencing `CredentialAlignmentObject` with `alignmentType` literal values of: 

1. "requires" and "teaches" options in the editor with `LearningOpportunity`; and
2. "requires" and "assess" options in the editor with `Assessment`.

There are a couple of Workit code samples below for a `LearningOpportunity` and for an `Assessment` that use "teaches" and "assesses". [Haven't seen any WorkIt examples of "requires", but the exact same analysis and solution applies as it does to `ceterms:assesses` and `ceterms:teaches`.]  

In sum, I propose that we create two new properties: `teaches` and `assesses`. We already have a [`ceterms:requires`](http://purl.org/ctdl/terms/requires) property.  These new properties can be modeled off the definitions of these same concepts in the pending [LRMI Alignment Type Vocabulary](https://github.com/dcmi/lrmi/blob/master/lrmi_vocabs/alignmentType.ttl) (however, not concepts as in LRMI but as properties):

> **`ceterms:assesses`:** "The resource being described may be used to assess the competency being referenced."
**`ceterms:teaches`:** "The resource being described may be used to teach the competency being referenced."

**Both the new `ceterms:assesses` and `ceterms:teaches` can be declared as subproperties of `ceterms:targetCompetency`.**

Here is a current example from `LearningOpportunity` in Workit and the `targetCompetency` property with an `alignmentType` of "Teaches":
 
```
  "ceterms:targetCompetency": [
    {
      "@type": "ceterms:CredentialAlignmentObject",
      "ceterms:alignmentType": "Teaches",
      "ceterms:codedNotation": [
        "1"
      ],
      "ceterms:frameworkName": "Program Learning Outcomes",
      "ceterms:targetNodeName": "Health Assessment: Conduct comprehensive and focused assessments of health and illness parameters in individuals, groups, and vulnerable populations"
    },
```
and this is the same situation but with an `AssessmentProfile` with `alignmentType` of "Assesses":

```
"ceterms:targetCompetency": [
    {
      "@type": "ceterms:CredentialAlignmentObject",
      "ceterms:alignmentType": "Assesses",
      "ceterms:framework": {
        "@id": "http://www.nocti.org/PDFs/JobReady/1337_21st_Century_Skills_for_Workplace_Success.pdf"
      },
      "ceterms:frameworkName": "NOCTI 21st Century Skills for Workplace Success",
      "ceterms:targetNode": {
        "@id": "http://www.nocti.org/PDFs/JobReady/1337_21st_Century_Skills_for_Workplace_Success.pdf"
      },
      "ceterms:targetNodeDescription": "Interpret and comprehend technical and general interest in written material",
      "ceterms:targetNodeName": "Reading Skills"
    },
```
Using the new `teaches` and `assesses` properties, these axmples would look like the following"

```
  "ceterms:teaches": [
    {
      "@type": "ceterms:CredentialAlignmentObject",
      "ceterms:codedNotation": [
        "1"
      ],
      "ceterms:frameworkName": "Program Learning Outcomes",
      "ceterms:targetNodeName": "Health Assessment: Conduct comprehensive and focused assessments of health and illness parameters in individuals, groups, and vulnerable populations"
    },
```
and

```
"ceterms:assesses": [
    {
      "@type": "ceterms:CredentialAlignmentObject",
      "ceterms:framework": {
        "@id": "http://www.nocti.org/PDFs/JobReady/1337_21st_Century_Skills_for_Workplace_Success.pdf"
      },
      "ceterms:frameworkName": "NOCTI 21st Century Skills for Workplace Success",
      "ceterms:targetNode": {
        "@id": "http://www.nocti.org/PDFs/JobReady/1337_21st_Century_Skills_for_Workplace_Success.pdf"
      },
      "ceterms:targetNodeDescription": "Interpret and comprehend technical and general interest in written material",
      "ceterms:targetNodeName": "Reading Skills"
    },
```
**NOTE:** The current domain and range of `ceterms:requires` already covers this use.

**Comment by siuc-nate** [comment]
Action to be taken:

**Create:**
**URI:** ceterms:assesses
**Label:** Assesses
**Definition:** The resource being described may be used to assess the competency being referenced.
**Domain:** ceterms:AssessmentProfile
**Range:** ceterms:CredentialAlignmentObject

**Create:**
**URI:** ceterms:teaches
**Label:** Teaches
**Definition:** The resource being described may be used to teach the competency being referenced.
**Domain:** ceterms:LearningOpportunityProfile
**Range:** ceterms:CredentialAlignmentObject

**Comment by stuartasutton** [comment]
Both `ceterms:assesses` and `ceterms:teaches` should be declared as subproperties of `ceterms:targetCompetency`.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
