### ISSUE TITLE
Is the use of both industryType and naics in credentialOrganization (and QA) redundant?

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#404]
@stuartasutton 
Credential and QACredentialOrganization both have properties of: ceterms:naics, and ceterms:industryType.

ceterms:naic
**Definition:**
The North American Industry Classification System (NAICS) code for a particular organization or business person.

ceterms:industryType
**Definition:**
The class identifier for the industry context from an established framework.
**Usage Note:**
For U.S. credentials, best practice is to use a framework such as the NAICS (North American Classification System). Other credentials may use any framework of the class ceterms:IndustryClassification.

Given that the recommendation (for U.S.) for industryType is to use naics, should there be a separate distinct property for naics?

**Comment by stuartasutton** [comment]
Yes, both are necessary but the `ceterms:industryType` usage note should be revised to eliminate this ambiguity. Like schema.org, we've provided some properties for widely used identifier systems like NAICS, DUNS etc. However, in this case, not all countries of the world use NAICS. The `ceterms:industryType` supports the use of vocabularies other than NAICS for codes commonly used in other countries.

The usage note for `ceterms:industryType` sould be changes as follows:

DELETE: 

>For U.S. credentials, best practice is to use a framework such as the NAICS (North American Classification System). Other credentials may use any framework of the class ceterms:IndustryClassification.

ADD:

>Best practice in identifying industries for U.S. credentials is to provide the NAICS code using the `ceterms:naics` property. Other credentials may use the `ceterms:industrytype` property and any framework of the class ceterms:IndustryClassification such as the Standard Industrial Classification (SIC) or the International Standard Industrial Classification of all Economic Activities (ISIC).

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
