### ISSUE TITLE
Update the usage note for ceterms:sameAs to enable sources like dbpedia

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#405]
We need to draft the text of the usage note.

**Comment by stuartasutton** [comment]
I suggest a different solution. We should change the definition so it more closely aligns with the `schema.org/sameAs`: "URL of a reference Web page that unambiguously indicates the item's identity." The `ceterms:sameAs` should be defined as "A resource that unambiguously indicates the identity of the resource being described."  Declare the ceterms an equivalent property to the schema.org, and, then drop the usage note.

**Comment by siuc-nate** [comment]
As long as that solves the core problem (being able to point at dbpedia and similar entities as a "this is what this is" source of information), then I am fine with it.

**Comment by stuartasutton** [comment]
It does.

**Comment by stuartasutton** [comment]
Having given this more thought, I'd suggest:

>**Definition:** "A resource that unambiguously indicates the identity of the resource being described."
**Usage Note:** "Resources that may indicate identity include, but are not limited to, descriptions of entities in open databases such as DBpedia and Wikidata or social media accounts such as FaceBook and LinkedIn."
**Equivalent Property:** schema.org/sameAs

**Comment by stuartasutton** [comment]
Formally:

DELETE:
```
   rdf:subject ceterms:sameAs ;
   rdf:predicate rdfs:comment ;
   rdf:object "The resource being described is the same as the resource being referenced."
```
ADD:
```
   rdf:subject ceterms:sameAs ;
   rdf:predicate rdfs:comment ;
   rdf:object "A resource that unambiguously indicates the identity of the resource being described."
```
ADD:
```
   rdf:subject ceterms:sameAs ;
   rdf:predicate dcterms:description ;
   rdf:object "Resources that may indicate identity include, but are not limited to, descriptions of entities in open databases such as DBpedia and Wikidata or social media accounts such as FaceBook and LinkedIn."
```

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
