### ISSUE TITLE
Remove ceterms:commonConditions from ceterms:ConditionManifest

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#406]
Currently we enable a ConditionManifest to reference another ConditionManifest, which allows creating a recursive "tree" of ConditionManifests:
![image](https://cloud.githubusercontent.com/assets/21346519/26794178/49b78452-49e6-11e7-8911-eecf100cfbc7.png)

However, since all of the data from each condition manifest would need to be retrieved and concatenated together, there is no particular benefit to this complexity.  In fact, it makes it much more difficult to process (and to document).  The resulting data would be identical if it were published this way instead:
![image](https://cloud.githubusercontent.com/assets/21346519/26794211/6adee062-49e6-11e7-8808-782571fb5309.png)
Note that this method of publishing is already possible, and that a hybrid of the two is also thus technically possible (and even more confusing).

Note also that the second method enables the consumer of the credential to know up-front that there are multiple Condition Manifests to consume without having to check each one individually for a "child" Condition Manifest (if the commonConditions property were removed from it).

And, if ConditionManifest B or C are updated, then the Credential "receives" the updates just as immediately under either structure.

Additionally, all of the Condition Manifests would be in one flat layer at the Organization level regardless of which of the two structures above are used:
![image](https://cloud.githubusercontent.com/assets/21346519/26794262/9bbecc06-49e6-11e7-8c89-e6cc097c27ca.png)

So, I believe it was an error in (my) judgment to include commonConditions as a property of Condition Manifest. It makes it far more difficult to process and to provide easy-to-understand guidance. The flatter approach is better, and loses nothing in terms of data. 

You also _gain_ the ability to pick and choose which Condition Manifest(s) apply to your object without having to worry that the data inside that Manifest might some day be modified by a reference to another Manifest you didn't want, or deal with a situation where a chain of manifests is _almost_ correct, but has one or two sticking points you wish weren't there. And you don't have to worry about Condition Manifest C referencing Condition Manifest A, or any other form of self-referential looping.

I think it is **much** cleaner if it is flat.

My proposal is thusly:
**Remove:**
> **Subject:** ceterms:commonConditions
> **Predicate:** rdfs:domain
> **Object:** ceterms:ConditionManifest

@stuartasutton what are your thoughts?

**Comment by stuartasutton** [comment]
Makes sense.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in history tracking.
