### ISSUE TITLE
Should the ConditionManifest include properties for connection properties

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#409]
The condition manifest definition includes the condition profile properties.
http://credreg.net/ctdl/terms#ConditionManifest

- ceterms:recommends
- ceterms:requires
- ceterms:entryCondition
- ceterms:corequisiteCondition
- ceterms:advancedStandingFrom
- ceterms:isAdvancedStandingFor
- ceterms:isPreparationFor
- ceterms:isRecommendedFor
- ceterms:isRequiredFor
- ceterms:preparationFrom

The last 6 properties (starting with ceterms:advancedStandingFrom), are _**connection**_ type conditions. These types of conditions are very specific and do not seem likely to be reuseable conditions.
Should these be removed from the condition manifest class?

**Comment by siuc-nate** [comment]
Proposed Actions to be taken:

**Remove:**
> **Subject:** ceterms:advancedStandingFrom
> **Predicate:** rdfs:domain
> **Object:** ceterms:ConditionManifest

**Remove:**
> **Subject:** ceterms:isAdvancedStandingFor
> **Predicate:** rdfs:domain
> **Object:** ceterms:ConditionManifest

**Remove:**
> **Subject:** ceterms:isPreparationFor
> **Predicate:** rdfs:domain
> **Object:** ceterms:ConditionManifest

**Remove:**
> **Subject:** ceterms:isRecommendedFor
> **Predicate:** rdfs:domain
> **Object:** ceterms:ConditionManifest

**Remove:**
> **Subject:** ceterms:isRequiredFor
> **Predicate:** rdfs:domain
> **Object:** ceterms:ConditionManifest

**Remove:**
> **Subject:** ceterms:preparationFrom
> **Predicate:** rdfs:domain
> **Object:** ceterms:ConditionManifest

**Comment by stuartasutton** [comment]
If the action needed is approval. These removal changes accurately reflect the discussion and conclusion from out Tuesday call.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
