### ISSUE TITLE
Fix typo in the label for Online Only

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#412]
http://credreg.net/ctdl/terms#OnlineOnly has "OnlineOnly" instead of "Online Only" for its label.

Proposal:

**Remove:**
> **Subject:** deliveryType:OnlineOnly
> **Predicate:** skos:prefLabel
> **Object:** "OnlineOnly"

**Add:**
> **Subject:** deliveryType:OnlineOnly
> **Predicate:** skos:prefLabel
> **Object:** "Online Only"

**Comment by stuartasutton** [comment]
Yes, correct the error.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in history tracking.
