### ISSUE TITLE
Enable third-party mapping (AlignmentMap)

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#413]
There are two parts to this:
1. The CTDL implications
2. The service/location implications

See https://github.com/CredentialEngine/vocabularies/issues/392#issuecomment-300272149 and subsequent posts

**Comment by siuc-nate** [comment]
@stuartasutton You created some images relevant to this that graphed out a proposed solution.  Can you post them here?  Thanks.

**Comment by stuartasutton** [comment]
Yes, I have been working on a PowerPoint on and off for weeks about 3 weeks. I want to do some incorporation from issue #414 that has reverberations from O*Net that can be extrapolated to 3rd-party mapping contexts as well.

**Comment by stuartasutton** [comment]
## Proposal Basics
A `ceterms:Map` is a resource comprised of a set of relationships (triples) asserted by a 3rd party who is not (necessarily) privy to either of the two resources being mapped. As a distinct class of entity, `ceterms:Maps` express the relationships between resources without affect on the canonical descriptions of those resources.  The model does not limit the classes of entities that can be mapped. Thus, all of the following would be appropriate.

>Credential==requires==>Competency
Occupation==requires==>Skill | Competency 
Learning Resource==recommends==>Competency
Course==recommends==>Exercise

The model for 3rd party mappings include three entities:

>**Agent.** The 3rd party making the mapping assertion(s).
>
>**Map.** An entity comprised of a set of `ceterms:hasStatement` relationships to individual `rdf:Statement` entities. 
>
>**Statement.** rdf:Statement entities comprised of: (1) `rdf:subject`, `rdf:predicate`, `rdf:object` (i.e., the triple), and (2) such other properties refining the relationship being mapped including provenance and other characteristics. 

The basic mapping model looks like the following: 

![2017-07-13-map 1](https://user-images.githubusercontent.com/2939046/28754720-5c112406-7500-11e7-8015-b8b04a541cf2.png)

## Example

The following example, expressed in Turtle (and also in JSONLD), illustrates a *single* mapping between an (imaginary) occupation in an occupations framework and a required (imaginary) skill in a skills framework. Using a `ceterms:level` property modeled on the notion of "level" in O*Net, the mapping by Organization X claims that the degree that the skill is needed to perform the occupation has been set at "70" (an O*Net standardized score).  

You can imagine an instance of  `ceterms:Map` with **many more logically related mappings** than just one.

### Turtle
```
@prefix ceterms: <http://purl.org/ctdl/terms/> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix exterms: <http://www.example.com/terms/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://credReg.org/resources/8cb87987-cf9b-413b-8ca5-f06baeeab74e> a ceterms:CredentialOrganization ;
    ceterms:hasMap <http://credReg.org/statements/maps/ddc8f33a-bed8-4800-a841-c28ec770ea4a> ;
    ceterms:name "Oganization X"@en-US .

<http://credReg.org/statements/6d829c13-c1df-4ea4-a385-ecd783d794e2> a rdf:Statement ;
    ceterms:creator <http://credReg.org/resources/8cb87987-cf9b-413b-8ca5-f06baeeab74e> ;
    ceterms:inMap <http://credReg.org/statements/maps/ddc8f33a-bed8-4800-a841-c28ec770ea4a> ;
    ceterms:level "70" ;
    rdf:object <http://credReg.org/skills/63d8d96d-1de5-4dab-8d48-1a7f56ca8af4> ;
    rdf:predicate ceterms:requires ;
    rdf:subject <http://credReg.org/occupations/6492737d-592b-4c7a-89a1-571385a9255c> .

<http://credReg.org/statements/maps/ddc8f33a-bed8-4800-a841-c28ec770ea4a> a ceterms:Map ;
    ceterms:hasStatement <http://credReg.org/statements/6d829c13-c1df-4ea4-a385-ecd783d794e2> ;
    ceterms:name "Test Map #1"@en ;
    ceterms:dateCreated  "2017-01-01"^^xsd:date ;
    ceterms:dateModified  "2017-07-29"^^xsd:date ;
    ceterms:ownedBy <http://credReg.org/resources/8cb87987-cf9b-413b-8ca5-f06baeeab74e> .
```
### JSONLD
```
{
  "@context": {
    "ceterms": "http://purl.org/ctdl/terms/",
    "dc": "http://purl.org/dc/elements/1.1/",
    "exterms": "http://www.example.com/terms/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@id": "http://credReg.org/mapgraphs/314caffe-b7f1-41d9-99b2-6b1d9c5c1e79",
  "@graph": [
    {
      "@id": "http://credReg.org/resources/8cb87987-cf9b-413b-8ca5-f06baeeab74e",
      "@type": "ceterms:CredentialOrganization",
      "ceterms:asserts": {
        "@id": "http://credReg.org/statements/6d829c13-c1df-4ea4-a385-ecd783d794e2"
      },
      "ceterms:hasMap": {
        "@id": "http://credReg.org/statements/maps/ddc8f33a-bed8-4800-a841-c28ec770ea4a"
      },
      "ceterms:name": {
        "@language": "en-US",
        "@value": "Organization X"
      }
    },    
    {
      "@id": "http://credReg.org/statements/6d829c13-c1df-4ea4-a385-ecd783d794e2",
      "@type": "rdf:Statement",
      "ceterms:assertedBy": {
        "@id": "http://credReg.org/resources/8cb87987-cf9b-413b-8ca5-f06baeeab74e"
      },
      "ceterms:inMap": {
        "@id": "http://credReg.org/statements/maps/ddc8f33a-bed8-4800-a841-c28ec770ea4a"
      },
      "ceterms:level": "70",
      "rdf:object": {
        "@id": "http://credReg.org/skills/63d8d96d-1de5-4dab-8d48-1a7f56ca8af4"
      },
      "rdf:predicate": {
        "@id": "ceterms:requires"
      },
      "rdf:subject": {
        "@id": "http://credReg.org/occupations/6492737d-592b-4c7a-89a1-571385a9255c"
      }
    },
    {
      "@id": "http://credReg.org/statements/maps/ddc8f33a-bed8-4800-a841-c28ec770ea4a",
      "@type": "ceterms:Map",
      "ceterms:dateCreated": {
        "@type": "xsd:date",
        "@value": "2017-01-01"
      },
      "ceterms:dateModified": {
        "@type": "xsd:date",
        "@value": "2017-07-29"
      },
      "ceterms:hasStatement": {
        "@id": "http://credReg.org/statements/6d829c13-c1df-4ea4-a385-ecd783d794e2"
      },
      "ceterms:name": {
        "@language": "en",
        "@value": "Test Map #1"
      },
      "ceterms:ownedBy": {
        "@id": "http://credReg.org/resources/8cb87987-cf9b-413b-8ca5-f06baeeab74e"
      }
    }
  ]
}
```

**Comment by stuartasutton** [comment]
Note that the `Agent` entity need not necessarily be considered an entity in the model, but just some external agent resource that is referenced from both the `ceterms:Map` and the `rdf:Statement` entities. E.g., a `ceterms:Map` instance might simply reference the URI of an existing CredentialOrganization entity in the CER or a resource in something like dbpedia.

**Comment by stuartasutton** [comment]
The `rdf:Statement` entity is used instead of some similar entity like `ceterms:CredentialAlignmentObject` because `rdf:Statement` is a built in entity in the RDF data model and therefore supported by RDF parsers, triplestores etc.
