### ISSUE TITLE
ConditionManifest (and costManifest) should having an organization role like assertedBy or ownedBy

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#415]
@stuartasutton 
A condition manifest is meant to stand alone, and be published to the registry as a separate entity. 
Currently there is no property to indicate the related organization who owns (like a credential) or asserts it (like a condition profile). The organization has the **hasConditionManifest** property, but there is no reverse property.

I would think one of the latter two (or perhaps some other property) should be added to condition manifest, and cost manifest.

**Comment by stuartasutton** [comment]
@cwd-mparsons, I hear you, but I wonder if you really want to do anything about it. In an RDF world, those reverse properties could exist (owl:inverseOf | schema.org/inverseOf). In RDF it makes sense as a means if getting the inverse data because a triplestore will create the implied triple when an explicit triple is present--i.e., no one has to fill in data for both direction, just one (the explicit triple). The second is automatically 'implied' to exist (i.e., the implied triple) and may even made manifest and stored in the database. 

So, it's a trade off. If you could mimic the behavior of a graph database and simply create the inverse data (i.e., conditionManifestOf) from the entered data (hasConditionManifest), then it would make sense. Forcing data entry people to manually put in such data is likely not worth it.

**Comment by siuc-nate** [comment]
In this case I think it's more a problem of retrieval - if a consuming system gets the data for a credential, and that credential points to a condition (or cost) manifest, then there is no way of knowing who owns that manifest.  In most cases it will be the same org that owns the credential, but not always.

Having said that, I'm not sure what difference the owner of the manifest makes, other than enabling a more complete display of data (or enabling a user/system to explore the graph further?). Which might be worthwhile.

Either way, we do already have the properties that Mike suggested (or a new property as you suggested), so I think it's worth discussing further.

**Comment by stuartasutton** [comment]
>"In this case I think it's more a problem of retrieval - if a consuming system gets the data for a credential, and that credential points to a condition (or cost) manifest, then there is no way of knowing who owns that manifest."

I think the circumstances where the manifest might be owned by someone other than the party asserting the "has" relationship is too slim to care about any 3rtd-party owner.

**Comment by cwd-mparsons** [comment]
So should 'conditionManifestOf' or  'assertedBy' be added to the Condition and Cost manifests?

**Comment by stuartasutton** [comment]
I would say no.

**Comment by jkitchensSIUC** [comment]
@cwd-mparsons @stuartasutton @siuc-nate let's make sure this is closed tomorrow. If any changes are needed they need to go with the June 30th release.

**Comment by cwd-mparsons** [comment]
If a user retrieves a condition manifest from the registry, there would be no indication of the related organization. Or if a user just searches for condition manifests in the registry, the resulting resources would not have a reference to the asserting organization.
It would seem that we need something concrete here.

**Comment by cwd-mparsons** [comment]
Add conditionManifestOf to ConditionManifest, and costManifestOf to CostManifest.

**Comment by siuc-nate** [comment]
Actions to be taken: 

Create:
**URI:** ceterms:conditionManifestOf
**Label:** Condition Manifest Of
**Definition:** The Condition Manifest being described is maintained by the resource being referenced.
**Domain:** ceterms:ConditionManifest
**Range:** ceterms:CredentialOrganization, ceterms:QACredentialOrganization
**InverseOf:** ceterms:hasConditionManifest

Create:
**URI:** ceterms:costManifestOf
**Label:** Cost Manifest Of
**Definition:** The Cost Manifest being described is maintained by the resource being referenced.
**Domain:** ceterms:CostManifest
**Range:** ceterms:CredentialOrganization, ceterms:QACredentialOrganization
**InverseOf:** ceterms:hasCostManifest

**Comment by jkitchensSIUC** [comment]
@siuc-nate is this being closed today?

**Comment by siuc-nate** [comment]
This was taken care of with the previous release.
