### ISSUE TITLE
Update the definition of ceterms:jobsObtained

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#416]
Per Bob, the definition should be changed from:
"The number of jobs obtained in the region during a given timeframe."

to:
"The number of credential holders who are employed as a percent of all credential holders who whose employment status was being determined in the same timeframe (e.g., employment rate)."

It might be worth wordsmithing it a bit to clarify whether "all credential holders" refers to all holders of the same credential as "number of credential holders" or if it refers to _all_ holders of _any_ credential (which I suspect it does not).

Perhaps something like "The number holders of a given credential who are employed, as a percentage of all holders of that credential, within a given timeframe."

**Comment by stuartasutton** [comment]
Just to be certain, is this saying that the definition of jobsObtained in a given timeframe is the percentage of all holders of the credential who are employed?

**Comment by siuc-nate** [comment]
See #377
