### ISSUE TITLE
Add description to EarningsProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#417]
Per Bob, http://credreg.net/ctdl/terms/EarningsProfile should also have ceterms:description

**Comment by jkitchensSIUC** [comment]
This is related to #376

**Comment by stuartasutton** [comment]
Leaving off `ceterms:description` was an oversight...no need for any discussion that I can see.

**Comment by siuc-nate** [comment]
See #376
