### ISSUE TITLE
Changes to main navigation for Technical Planning website (CTDL Guide)

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#421]
In a recent meeting with people unfamiliar with the CTDL, it became apparent that the "CTDL Guide" heading is being misread as a section header and not as a destination. Reconsider.

**Comment by siuc-nate** [comment]
The navigation menu has always slightly bothered me for that reason. It probably made more sense earlier on, when the list of options was very different.

I think the simplest solution would just be to actually make those things headers and add links to their respective sections.  

My proposed navigation menu:
![image](https://user-images.githubusercontent.com/21346519/27922319-3f88b100-6240-11e7-8045-31e79f255755.png)

@jkitchensSIUC @stuartasutton thoughts?

**Comment by jkitchensSIUC** [comment]
The navigation change makes sense @siuc-nate and @stuartsutton.

**Comment by stuartasutton** [comment]
Yup, makes sense to me to.

**Comment by siuc-nate** [comment]
This was taken care of.
