### ISSUE TITLE
Deciding and documenting what constitutes "change"

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#422]
We have a policy governing substantive changes in the [CTDL Namespace Policy](http://www.credreg.net/ctdl/namespacepolicy):

>"Changes of definitions within a  CTDL term declaration will be reflected in the affected  CTDL term declaration . If, in the judgment of the CE Technical Team, such changes of meaning are likely to have substantial impact on either machine processing of CTDL terms or the functional semantics of the terms, then these changes will be reflected in a change of URI for the CTDL term or terms in question. The URIs for any new CTDL namespaces resulting from such changes will conform to the CTDL namespace URI patterns defined above."

We have no such policies declared regarding what constitutes a substantive change in credentials (and related entities) and in concept schemes and competency frameworks. We have notions of "version" inherent in the CTID, but nowhere do we define what "change" and "version" mean conceptually or in application. Perhaps each kind of "thing" may have a different set of decision factors, but we need to articulate them.

Regardless, these things need to be spelled out before we begin incurring changes in instances of key entities.

**Comment by siuc-nate** [comment]
Wouldn't the same namespace policy apply to each of those things (the last paragraph implies that anything derived from CTDL namespaces would follow those policies)? 

Or by "instances of key entities" do you mean actual credentials themselves? I thought we were leaving it up to the submitters of data to indicate when a new version of a credential was necessary.

I think I'm missing something here. Can you elaborate further?

Thanks.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate, let's put this on the agenda for next weeks' review.

**Comment by stuartasutton** [comment]
No, Nate. The CTDL Namespace Policy is a different beast. I'm talking about instances of credentials, competencies, learning opportunities, assessments. In essence, our non-schema stuff identified by URI. I.e., what's the level of change permissible before one says that [this] is no longer the same beast and needs a new URI.  We have to be able to say "something" about change to folks like BCSP who might otherwise simply edit at will without asking themselves does this edit actually change the original intent embodied in the URI. I think that change can be framed in much thee same way as the CTDL but tailored to the resource type. --i.e., correcting errors, clarifying etc. as not constituting a change in semantics...that's fairly universal...what does constitute a semantic change may vary by resource type.

**Comment by siuc-nate** [comment]
http://credreg.net/registry#ctid
Currently this section indicates that the publisher of the data is responsible for determining when something is truly a "different beast".  If we need to go into more depth on this, we should discuss it on Tuesday.

**Comment by stuartasutton** [comment]
Nate, the *Credential Engine Registry Guide* definition covers it, but it needs to be stated more precisely as a test and has to show up in places other than the Registry Guide. There is a section on identifiers in the CTDL Guide and the test should be reiterated there. 

In the *Registry Guide* you use the words "cannot be substituted for the previous one" as the test. So the test seems to me to be that a series of versions of a resource should maintain the same CTID until such time as a version no longer has the same full force and effect for all purposes as the previous version. A resource that does not carry the same force and affect for all purposes as the previous version should be assigned a new CTID. The entity exercising authority over the resource is the only party deemed qualified to determine when a new CTID is appropriate.
