### ISSUE TITLE
serviceType:RenewService and serviceType:RevokeService

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#424]
[serviceType:RenewService](http://credreg.net/ctdl/terms/IdentifierValue#RenewServicel)
The Preferred Label is: Renew Credential Service. Shouldn't the Label be: Renew Service?

[serviceType:RevokeService](http://credreg.net/ctdl/terms/IdentifierValue#RevokeService)
The Preferred Label is: Revoke Credential Service. Shouldn't the Label be: Revocation Service?

None of the other services use Credential in the Preferred Label.

**Comment by stuartasutton** [comment]
Yes, the change makes sense, Jeanne.

**Comment by siuc-nate** [comment]
Changes to be made:

**Remove:**
> **Subject:** serviceType:RenewService
> **Predicate:** rdfs:label
> **Object:** Renew Credential Service

**Remove:**
> **Subject:** serviceType:RevokeService
> **Predicate:** rdfs:label
> **Object:** Revoke Credential Service

**Add:**
> **Subject:** serviceType:RenewService
> **Predicate:** rdfs:label
> **Object:** Renew Service

**Add:**
> **Subject:** serviceType:RevokeService
> **Predicate:** rdfs:label
> **Object:** Revoke Service

**Comment by stuartasutton** [comment]
Changes look good to me.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
