### ISSUE TITLE
Service Properties

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#426]
All of the "Service" definitions begin with "The resource being described provide..."  However, all the related actions and predicates all begin with, " The agent being described..."  Shouldn't this be consistent and use "agent" rather than "resource"?

Accredit Service
The resource being described provides accreditation service (serviceType:AccreditService).
Approve Service
The resource being described provides approval service (serviceType:ApproveService).
Endorse Service
Offer Service
The resource being described offers other resources (serviceType:OfferService).
Recognize Service
The resource being described provides recognition service (serviceType:RecognizeService).
Regulate Service
The resource being described provides regulation service (serviceType:RegulateService).
Renew Service
The resource being described provides renewal service (serviceType:RenewService).
Revoke Service
The resource being described provides revocation service (serviceType:RevokeService).

**Comment by stuartasutton** [comment]
There is no problem with being "agent" as you note, Jeanne.

**Comment by siuc-nate** [comment]
Actions:
For the definitions of each of the properties below, change "The resource being described" to "The agent being described":
- ceterms:AccreditService
- ceterms:ApproveService
- ceterms:EndorseService
- ceterms:OfferService
- ceterms:RecognizeService
- ceterms:RegulateService
- ceterms:RenewService
- ceterms:RevokeService

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in history tracking.
