### ISSUE TITLE
Add comment to ceterms:Competency

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#427]
Per our 7/6/2017 meeting:

Proposed change:
**ADD:**
> **Subject:** ceterms:Competency
> **Predicate:** dcterms:description
> **Object:** Learning outcomes and standards are also considered to be competencies in the context of CTDL.

**Comment by stuartasutton** [comment]
> **Subject:** ceterms:Competency
> **Predicate:** dcterms:description
> **Object:** Competency is broadly defined to include assertions of academic, professional, occupational, vocational or life goals, outcomes, and standards however labeled.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
