### ISSUE TITLE
Add ceterms:alternateName to organization

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#428]
To handle abbreviations and alternate names:

**Add:**
> **Subject:** ceterms:alternateName
> **Predicate:** rdfs:domain
> **Object:** ceterms:CredentialOrganization, ceterms:QACredentialOrganization

**Comment by stuartasutton** [comment]
Nate, do you mean:

> **Subject:** ceterms:CredentialOrganization, ceterms:QACredentialOrganization
**Predicate:** ceterms:alternateName
**Object:** Literal/text 

Note that [`schema.org/alternateName`](http://schema.org/alternateName) exists and is declared as a property with a domain of "thing" (as in the alternate name of anything).

**Comment by siuc-nate** [comment]
Not quite.
Credential already has http://credreg.net/ctdl/terms/alternateName ; we just need to add it to the Organization classes.

**Comment by stuartasutton** [comment]
I see...

**Comment by siuc-nate** [comment]
@jkitchensSIUC @stuartasutton are we good with this change?

**Comment by stuartasutton** [comment]
Yup, I', OK with it.

**Comment by siuc-nate** [comment]
The change described in the first post has been made in pending CTDL and noted in the history tracking.
