### ISSUE TITLE
Add Credential to the domain of ceterms:naics

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#430]
The industryType property's usage note indicates that the naics property should be used when indicating a NAICS code. This is currently not possible with Credential, as Credential only has industryType.

Proposal:
**Add:**
> **Subject:** ceterms:naics
> **Predicate:** rdfs:domain
> **Object:** ceterms:Credential (and subclasses)

**Comment by stuartasutton** [comment]
@siuc-nate, I don't think that is necessarily correct.

>"NAICS is an industry classification system that groups **establishments** into industries based on the similarity of their production processes. It is a comprehensive system covering all economic activities. There are 20 sectors and 1,057 industries in 2017 NAICS United States." 

Looks like it establishes the industry to which the "establishment" belongs. Credential wou;dn't seem to fit.

**Comment by siuc-nate** [comment]
The NAICS codes are tied directly to industries ("an industry classification system"), and don't directly connect to establishments at all. 

My larger point here was that the documentation for industryType tells you to do something that is currently impossible to do in the context of a Credential.  So we should either modify the usage note for industryType or consider adding naics to credential.

**Comment by siuc-nate** [comment]
@jkitchensSIUC @stuartasutton @cwd-mparsons Any thoughts on this?

**Comment by stuartasutton** [comment]
@siuc-nate, if you are secure in your reading of NAICS codes, then the following makes sense:

**Add:**
> **Subject:** ceterms:naics
> **Predicate:** rdfs:domain
> **Object:** ceterms:Credential (and subclasses)

**Comment by siuc-nate** [comment]
In looking through the codes themselves (an easy way to do it is to look at the Industry filter in the Workit search), it definitely seems that the codes identify industries.  So, I am pretty sure the change above would be correct.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
