### ISSUE TITLE
Describing the CER repository as a linked dataset with the VoID Vocabulary

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#431]
To increase the visibility of the CER once it goes public, we need to create and publish a VoID description to be used by Linked Data discovery services.

https://www.w3.org/TR/void/

**Comment by jeff-grann** [comment]
Some potential outlets for CER.

- [SWEO Community Project: Linking Open Data on the Semantic Web](https://www.w3.org/wiki/TaskForces/CommunityProjects/LinkingOpenData/DataSets)

- [The Linked Open Data Cloud](https://lod-cloud.net/)

- [Wikipedia: Linked data](https://www.w3.org/wiki/LinkedData)

- [Datahub](https://datahub.io/)

- [Kaggle](https://www.kaggle.com/datasets)

- [Registry of open data on AWS](https://registry.opendata.aws/)

- [Data World](https://data.world/data-partners)

- [LAK Dataset]https://solaresearch.org/initiatives/dataset/)

- [AFEL Dataset for Learning Analytics](http://data.afel-project.eu/catalogue/)
