### ISSUE TITLE
Including targetNode property with concepts from CTDL controlled vocabularies

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#433]
(Posting this here because I don't know which is the correct repo)

I am still running across instances in Workit of references to concepts in CTDL controlled vocabularies that do not include a value for [ceterms:targetNode](http://credreg.net/ctdl/terms/targetNode). For example, see this snippet from the [Black Hawk College organization record](https://credentialfinder.org/organization/1341/Black_Hawk_College):

```
"ceterms:serviceType": [{
        "@type": "ceterms:CredentialAlignmentObject",
        "ceterms:targetNodeDescription": "The resource being described offers other resources.",
        "ceterms:targetNodeName": "Offer Service"
    }]
```

This should be:

```
"ceterms:serviceType": [{
        "@type": "ceterms:CredentialAlignmentObject",
        "ceterms:targetNodeDescription": "The resource being described offers other resources.",
        "ceterms:targetNodeName": "Offer Service",
        "ceterms:targetNode": {"@id": "serviceType:OfferService"}     
    }]
```
This may be an editor problem; if so, whenever the editor includes a concept description from one or our controlled vocabularies or those of others, a `targetNode` should be included **if it is actually encoded as an RDF resource URI and returns the node data**.

**Comment by siuc-nate** [comment]
Are all of the instances of this happening for a particular vocabulary? I recall there was a period where one or two of the vocabularies weren't properly loading values for the targetNode field (I think it might have been organization service type, but I'm not sure).

**Comment by stuartasutton** [comment]
I can't answer the question, Nate.

**Comment by cwd-mparsons** [comment]
@stuartasutton @siuc-nate 
I found the issue. I will update the server tonight. Following is the link for an organization that has the corrected output.

http://lr-staging.learningtapestry.com/ce-registry/envelopes/f6e7f8ef-357b-4438-9d5c-c3079dab20f3

**Comment by stuartasutton** [comment]
Can this issue be closed?

**Comment by siuc-nate** [comment]
This has been fixed.
