### ISSUE TITLE
Unnecessary use of ceterms:alignmentType

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#436]
The `ceterms:alignmentType` property on `ceterms:CredentialAlignmentType` is intended to identify the type of the alignment **when it is otherwise ambiguous**.  It should not be used where unecessary. For example, the flowing snippet from  WorkIt resource: https://credentialfinder.org/credential/1417/21st_Century_Skills_for_Workplace_Success, uses the unambiguous `ceterms:requires` property to reference a `ceterms:ConditionProfile`. It is redundant (and adds nothing semantically) to then say that the `ceterms:alignmentType` of that `ceterms:ConditionProfile` is the literal "requires".

```
    "ceterms:requires": [{
        "@type": "ceterms:ConditionProfile",
        "ceterms:assertedBy": [{"@id": "http://credentialEngineRegistry.org/resources/5a172f5c-63df-4712-b240-cc7dc0aa7a58"}],

        [ ... ]

        "ceterms:name": "Pharmacy Technician Program Courses",
        "ceterms:targetCompetency": [
            {
                "@type": "ceterms:CredentialAlignmentObject",
                "ceterms:alignmentType": "Requires",
                "ceterms:frameworkName": "Pharmacy Technician",
                "ceterms:targetNodeDescription": "This course provides an overview of the fundamentals of pharmacy and the technician\u2019s role in providing pharmaceutical care. ...",
                "ceterms:targetNodeName": "PHAR 101 Introduction to Pharmacy"
            },

**Comment by siuc-nate** [comment]
Is it harmful? I can look into modifying the system to avoid publishing the alignmentType in certain cases if so.

**Comment by stuartasutton** [comment]
No, it breaks nothing. It's just another way in which our data is redundant where it's unnecessary to machines. We already know that the operative predicate for the array in which this data is found is `ceterms:requires`, so the adding the literal "requires" adds nothing.

**Comment by siuc-nate** [comment]
We will explore taking this out, especially now that we have ceterms:assesses and ceterms:teaches.

**Comment by siuc-nate** [comment]
@cwd-mparsons what would it take to remove this from publishing? Is it used anywhere in/by the import?

**Comment by cwd-mparsons** [comment]
@siuc-nate We are not using alignmentType in publishing at all anymore. It is not referenced by the Import either.

**Comment by siuc-nate** [comment]
@cwd-mparsons All right, thanks.
I don't think there's a need to fiddle with the validation JSON for this one, since it's an optional field anyway.
