### ISSUE TITLE
Add PostalAddress to the range of availableAt

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#437]
Currently, `ceterms:availableAt` has a range of `ceterms:GeoCoordinates`. When the location of availability is only a street address, the following is nevertheless necessary:

```
"ceterms:availableAt": [{
        "@type": "ceterms:GeoCoordinates",
        "ceterms:address": [{
            "@type": "ceterms:PostalAddress",
            "ceterms:name": "Joint Base San Antonio",
            "ceterms:addressCountry": "United States",
            "ceterms:addressLocality": "San Antonio",
            "ceterms:addressRegion": "Texas ",
            "ceterms:postalCode": "78234",
            "ceterms:streetAddress": "Joint Base San Antonio-Ft Sam Houston 3038 William Hardee Rd, BLDG 895"
        }],
        "ceterms:name": "Joint Base San Antonio" << REDUNDANT
```
If we add `ceterms:PostAddress` to the range of `ceterms:availableAt`, we can do the following:

```
"ceterms:availableAt": [{
        "@type": "ceterms:PostalAddress" 
        "ceterms:name": "Joint Base San Antonio",
        "ceterms:addressCountry": "United States",
        "ceterms:addressLocality": "San Antonio",
        "ceterms:addressRegion": "Texas ",
        "ceterms:postalCode": "78234",
        "ceterms:streetAddress": "Joint Base San Antonio-Ft Sam Houston 3038 William Hardee Rd, BLDG 895"
        }]
```
When the location actually involves geo-coordinates, then use of `ceterms:GeoCoordinates` makes sense.

**Comment by siuc-nate** [comment]
So to summarize, this is your proposal, correct?:

**Add:**
> **Subject:** ceterms:availableAt
> **Predicate:** rdfs:range
> **Object:** ceterms:PostalAddress

**Comment by stuartasutton** [comment]
Close...

**Add:**
> **Subject:** ceterms:availableAt
> **Predicate:** schema:rangeIncludes
> **Object:** ceterms:PostalAddress

See #438

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
