### ISSUE TITLE
Erroneous use of domain and range instead of domainIncludes and rangeIncludes

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#438]
Back in issue #232, we noted that we needed to explain that CTDL does not use `rdfs:domain` and `rdfs:range` and instead uses `schema:rangeIncludes` and` schema:domainIncludes`. That explanation is in the last paragraph of the [Guide's section 1](http://credreg.net/ctdl/handbook#domainIncludes). Also, our declaration tables for properties have rows labeled "Domain Included" and "Range Included" instead of "Domain" and "Range". **However, throughout the RDF schema, we've done exactly what we said we were not doing and used `rdfs:domain` and `rdfs:range`**.

This is a hard one because it means that we need to eat crow and change all instances of `rdfs:domain` and `rdfs:range` to `schema:domainIncludes` and `schema:rangeIncludes`. After we assess any technical issues this change entails with our own applications, we might do an interim release that has this single change in it but does **not** list out the change with every property in the schema. 

This is massively nontrivial since use of `rdfs:domain` and `rdfs:range` results in inferred entailments in RDF data stores that we need to preclude. It is also something that is quite likely to have escaped the attention of developers at this point. I guess we'll find that out. Note that the change loosens the semantics as opposed to tightening them and that is a good thing (except for someone who might have been relying on RDF inferencing).

**Comment by siuc-nate** [comment]
This _should_ be a fairly easy thing to accomplish in terms of our JSON exports and whatnot, since none of that uses domain/range internally (other than the history tracking, but I think I can fix that with a few queries on the server). 

Do we need to coordinate the timing of this at all or is it just something I need to change when I get the chance (and perhaps not all at once)?

**Comment by stuartasutton** [comment]
I would not say that this is a red hot issue. But we do want to get it done before someone implements a system relying on the referencing power of rdfs:domain and rdfs:range. And, since it basically arithmetically touches on all properties, we need to sufficiently point out the change even though we needn't have it reverberate through the change histories of each property.

**Comment by siuc-nate** [comment]
Does that mean it's something I can implement in stages, as I am able to get to things?

I should have been more clear in my reference to the history tracking - I mean the existing items on the release history page.

**Comment by stuartasutton** [comment]
Yes, it's OK to do in stages. But we should establsh a target for when we think we can have it done.

**Comment by siuc-nate** [comment]
The schema management system has taken care of this.
