### ISSUE TITLE
clarify text in LearningOpportunity usage note

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#439]
### REMOVE:
>**Subject:** ceterms:LearningOpportunity
**Predicate:** vann:usageNote 
**Object:** "Types of learning opportunities such as a Courses class in other namespaces (e.g., schema.org/Course) may be declared as subclasses of ceterms:LearningOpportunity to support their discovery through applications processing CTDL data."

### ADD:
>**Subject:** ceterms:LearningOpportunity
**Predicate:** vann:usageNote 
**Object:** "Classes of learning opportunities defined in other namespaces such as schema.org/Course may be declared as subclasses of ceterms:LearningOpportunity to support their discovery through applications processing CTDL data."

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
