### ISSUE TITLE
Need to add dateCreated and dateModified

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#441]
We currently cover dates affecting the content of a resource (e.g., endDates and startDates), but we have nothing to denote the date of creation or modification of the resource itself. So, I suggest these two properties be created with slightly modified definitions from their analogs in schema.org.

`ceterms:dateCreated`: "The date on which a resource was created."
`ceterms:dateModified`: "The date on which a resource was most recently modified." 

See also https://github.com/CredentialEngine/CompetencyFrameworks/issues/37

**Comment by siuc-nate** [comment]
Would these be related to the resource itself (i.e. the date the credential was created/modified) or to the document itself (i.e. the date this particular JSON blob describing the credential was created/modified)?

**Comment by Lomilar** [comment]
I have a similar opinion in that lastModified could come through the HTTP header. It's arguable that the lastModified header is not appropriate for this use, as it requires metadata representation in the data store. That being said, I have no issues with these existing, but having them be strongly coupled to the schema.org analogs would make interoperability (with say, CASE, which has these properties) a bit easier.

**Comment by siuc-nate** [comment]
Depending on what the intended purpose/use of the properties are, they might make more sense as properties on the registry envelope rather than in the payload.

**Comment by stuartasutton** [comment]
Here's a node from the DQP competency framework defining the framework itself.

```
@prefix asn: <http://purl.org/ASN/schema/core/> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix dct: <http://purl.org/dc/terms/> .
@prefix gemq: <http://purl.org/gem/qualifiers/> .
@prefix loc: <http://www.loc.gov/loc.terms/relators/> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<http://degreeprofile.org/dqp> a asn:StandardDocument ;
    dc:title "Degree Qualification Profile"@en-US ;
    dct:description "The Degree Qualifications Profile (DQP) provides a baseline set of reference points for what students should know and be able to do to earn associate, bachelor’s and master’s degrees. In short, the DQP represents a comprehensive and ongoing effort to clearly define what postsecondary degrees should mean in terms of specific learning outcomes."@en-US ;
    loc:author "Lumina Foundation"@en-US ;
    dc:publisher "Lumina Foundation"@en-US ;
    dct:source <http://degreeprofile.org/wp-content/uploads/2017/03/DQP-web-download-reference-points-FINAL.pdf> ;
    dct:rights "© 2014 Lunina Foundation - All rights reserved"@en-US ;
    dct:rightsHolder "Lumina Foundation"@enUS ;
    dct:created "2011"^^xsd:date ;
    dct:dateModified "2014"^^xsd:date ;
    gemq:hasChild <http://degreeprofile.org/dqp/acl1>,
        <http://degreeprofile.org/dqp/bik1>,
        <http://degreeprofile.org/dqp/cgl1>,
        <http://degreeprofile.org/dqp/is1>,
        <http://degreeprofile.org/dqp/sk1> .
```

**Comment by siuc-nate** [comment]
Per our 8/23/2017 conversation, Stuart will follow up with this.

**Comment by cwd-mparsons** [comment]
@stuartasutton A dateModified will be a very useful property for a crawler process, as well as in search results. 
We are working on an import of the stuff in the registry. The process would be to download all resources that have an updated date greater than the date of the last import. The date used is the UpdatedAt date on the registry envelope. The latter date is appropriate for our purposes as it represents the last date the resource was published to the registry. 
The purpose of a crawler would be to proactively 'pull' credential data from a website, and publish to the registry. In the absence of a dateModified on credential (and others) data, the crawler would publish the resource every day (dependent on the crawl schedule), even if nothing has changed. 
Then import processes like ours, would download and re-process credentials even though there have been no changes. 
There would also be some value in displaying the dateModified in search results, and possibly on detail pages, as well. 
I could also see value in a dateModified on profiles like Cost, and condition profiles, to 'signal' to consumers that there have been changes - even if the changes are not documented.
