### ISSUE TITLE
CostProfile shows as unstable on credreg.net. 

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#443]
@stuartasutton @siuc-nate 
CostProfile is currently tagged as unstable on credReg.net, this seems to be wrong. 

> http://credreg.net/ctdl/terms/CostProfile

As well, approvedBy, approvedIn, and approves are also marked as unstable. I don't recall this as being unstable either.

> http://credreg.net/ctdl/terms/approvedBy

**Comment by siuc-nate** [comment]
Actually, there are a number of unstable things we should probably look at. Some of them appear to have fallen through the cracks when we stabilized ceterms:CredentialPerson.

Go to http://credreg.net/ctdl/terms and click "show unstable" to see all of them.  Of these, we should probably stabilize:

Classes:
- CostProfile

Properties:
- affiliation
- approvedBy
- approvedIn
- approves
- employee
- familyName
- givenName
- honorificSuffix
- regulatedBy
- regulatedIn
- regulates
- worksFor

Concepts:
- residency:InState
- residency:International
- residency:Local
- residency:OutOfState
- residency:Regional
- serviceType:AccreditService
- serviceType:ApproveService
- serviceType:OfferService
- serviceType:RecognizeService
- serviceType:RegulateService
- serviceType:RenewService
- serviceType:RevokeService

There is also [the matter of the entire PurposeType scheme, related property, and concepts](https://github.com/CredentialEngine/vocabularies/issues/87#issuecomment-318110769).

**Comment by siuc-nate** [comment]
Having discussed this with @stuartasutton and @cwd-mparsons, we will stabilize CostProfile.  We still need to review the other terms as well.

**Comment by siuc-nate** [comment]
The following have been stabilized in pending CTDL and noted in history tracking:
Classes:
- CostProfile

Properties:
- affiliation
- approvedBy
- approvedIn
- approves
- employee
- familyName
- givenName
- honorificSuffix
- regulatedBy
- regulatedIn
- regulates
- worksFor

Concepts:
- residency:InState
- residency:International
- residency:Local
- residency:OutOfState
- residency:Regional
- serviceType:AccreditService
- serviceType:ApproveService
- serviceType:OfferService
- serviceType:RecognizeService
- serviceType:RegulateService
- serviceType:RenewService
- serviceType:RevokeService


We still need to review PurposeType per the post above.
