### ISSUE TITLE
Use of ceterms:conditionProfiled

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#445]
@stuartasutton 
ceterms:conditionProfiled (http://credreg.net/ctdl/terms/conditionProfiled) is defined on learningOpportunity, but not on assessment or credentials. I understand that it was included as an inverse property to one of the several condition profiles, to enable use in RDF.
Should it be added to the credential classes and assesmentProfile for consistancy?

**Comment by stuartasutton** [comment]
@cwd-mparsons, to my knowledge, we have not enabled inverse properties anywhere in the CTDL term declarations. A search of the entire JSONLD schema shows none--i.e., no [`owl:inverseOf`](https://www.w3.org/TR/owl-ref/#inverseOf-def) or [`schema.org/inverseOf`](http://meta.schema.org/inverseOf) declarations anywhere and none of the mechanisms defined in [JSON-LD](https://www.w3.org/TR/json-ld/#reverse-properties) 1.0 for inverse properties have been used.  

If we are implementing inverse properties in the system code, we need to inventory those uses and determine which should actually have inverse properties declared in the schema. I somehow doubt that `conditionProfiled` is a good candidate; but it would be useful to know where it was "included" in the application coding.

**Comment by cwd-mparsons** [comment]
@stuartasutton , we don't use conditionProfiled in the application code, as the context of condition to resource can be set/derived by the context, that is adding a condition to credential.
So would the alternate action be to remove this property?

**Comment by stuartasutton** [comment]
The only use of `ceterms:conditionProfiled`(http://credreg.net/ctdl/terms/conditionProfiled) is as follows:

> `LearningOpportunityProfile`===`conditionProfiled`===>`ConditionProfile`

I don't see much value.

**Comment by siuc-nate** [comment]
I would support dropping:
- assessmentProfiled
- conditionProfiled
- credentialProfiled
- learningOpportunityProfiled
- taskProfiled (which reminds me, we need to come to a decision on TaskProfile some time)

**Comment by stuartasutton** [comment]
I agree with Nate that we should deprecate all five.

**Comment by siuc-nate** [comment]
Action: 

**Remove** the vs:term_status of **vs:stable** and add a vs:term_status of **vs:deprecated** to:
- assessmentProfiled
- conditionProfiled
- credentialProfiled
- learningOpportunityProfiled
- taskProfiled

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
