### ISSUE TITLE
Are we at the place where we can deprecate ceterms:TaskProfile

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#447]
As far as I am aware, we have not run across a single instance where [`ceterms:TaskProfile`](http://credreg.net/ctdl/terms/TaskProfile) has been needed.  If so, then we also need to deprecate:

>[`ceterms:targetTask`](http://credreg.net/ctdl/terms/targetTask) 
[`ceterms:taskProfiled`](http://credreg.net/ctdl/terms/taskProfiled)

**Comment by siuc-nate** [comment]
I am okay with deprecating these.

**Comment by siuc-nate** [comment]
Per our 8/23/2017 discussion:
Since there may yet be a purpose for these, we will leave them alone for now.
