### ISSUE TITLE
Create property to indicate renewal frequency

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#453]
Currently we have ceterms:renewal (and related properties renewalBy, and renewedIn) but no way to indicate how often the thing being discussed must be renewed. The renewal property points to ConditionProfile.

I am thinking we need a property to express the frequency of renewal, but I'm not entirely sure whether it belongs on Credential (and subclasses - which are currently the only places you find the renewal-related properties), or if it should be on ConditionProfile (in the event of multiple frequencies dependent upon something else in the conditions).

I think a good compromise is to give the property (let's call it "renewalFrequency") to Credential and give it a range of DurationProfile so that it can express some additional data as needed (much like the estimatedDuration property).

Proposal:
**Create:**
**URI:** ceterms:renewalFrequency
**Label:** Renewal Frequency
**Definition:** Frequency with which the credential needs to be renewed.
**Domain Includes:** ceterms:Credential (and subclasses)
**Range Includes:** xsd:duration

Thoughts?

**Comment by siuc-nate** [comment]
@stuartasutton Actually, on closer inspection, was this the intent of adding maximumDuration to Credential back in #40?

**Comment by siuc-nate** [comment]
Per our 9/22/2017 conversation:
We believe that maximumDuration is sufficient unless there is a specific need to be more particular; however, we need to craft a looser definition that will accommodate renewal frequency.

**Comment by stuartasutton** [comment]
After reviewing yesterday's discussion of editing the definition of `ceterms:maximumDuration` to accommodate the notion of renewal frequency, I think we need to go with a new, more precise property that more aligns with community usage and accommodates the subtle but significant differences in definition and current usage. The `ceterms:minimumDuration` and `maximumDuration` properties deal with approximations and there is **nothing** "approximate" with renewal frequency. It's subtle relationship to `ceterms:maximumDuration` can be handled by declaring a new `ceterms:renewalFrequency` as a kind of maximum duration through making it a subproperty.

### Create:
**URI:** ceterms:renewalFrequency
**Label:** Renewal Frequency
**Definition:** Frequency with which the credential needs to be renewed.
**Domain Includes:** ceterms:Credential (and subclasses)
**Range Includes:** xsd:duration
**Subproperty Of** ceterms:maximumDuration

**Comment by stuartasutton** [comment]
While `renewalFrequency` has been declared as a subproperty of `ceterms:maximumDuration`, a Usage Note should be added to `ceterms:maximumDuration` warning not to use it for describing the renewal frequency of a credential and point people to 'ceterms:renewalFrequency'.

#### Add to `ceterms:maximumDuration`:

**Comment:** The value of ceterms:maximumDuration denotes an approximation of duration.
**Usage Note:** Do not use ceterms:maximumDuration to identify the renewal frequency of a credential; use ceterms:renewalFrequency instead.

**Comment by siuc-nate** [comment]
Should we remove maximumDuration from Credential? I'm pretty sure renewal is the only reason it was there to begin with (this would also negate the need for the usage note).  Otherwise, can we clearly define a reason/purpose to having maximumDuration on Credential?

**Comment by stuartasutton** [comment]
I would not be hasty. min- and maxDuration could be applicable in learning opportunities or assessments in ways quite distinct from renewalFrequency.

**Comment by siuc-nate** [comment]
I'm only proposing to remove it from Credential.  Currently its domain is only Credential and DurationProfile.

**Comment by stuartasutton** [comment]
OK

**Comment by siuc-nate** [comment]
Actions to be taken:

**Create:**
> **URI:** ceterms:renewalFrequency
> **Label:** Renewal Frequency
> **Definition:** Frequency with which the credential needs to be renewed.
> **Comment:** The value of ceterms:maximumDuration denotes an approximation of duration.
> **Usage Note:** Do not use ceterms:maximumDuration to identify the renewal frequency of a credential; use ceterms:renewalFrequency instead.
> **Domain Includes:** ceterms:Credential (and subclasses)
> **Range Includes:** xsd:duration
> **Subproperty Of** ceterms:maximumDuration

**Comment by siuc-nate** [comment]
These changes have been made in CTDL and noted in history tracking.
