### ISSUE TITLE
Proposal for new properties for connecting credentials

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#454]
When we reviewed the [Connecting Credentials Glossary](http://connectingcredentials.org/wp-content/uploads/2016/06/Glossary-of-Credentialing-Terms.pdf), our take away in terms of CTDL was that the following terms in the Glossary identified relationships between credentials and not types of credentials:

> Stackable Credential
Nested Credential
Latticed Credentials
Lateral Credentials

To date, [`ceterms:hasPart`](http://credreg.net/ctdl/terms/hasPart) has been used to handle some of these relationships but is really  appropriate only with Connecting Credentials Modularity (see below).

The definitions in the following sections mainly follow the Connecting Credentials definitions with changes made to better align the definitions to CTDL. 

### Stackable Credential

> **Definition:** A credential that is part of a sequence of credentials that can be accumulated over time to build up a holder’s qualifications and help that holder move along a career pathway to further education, different responsibilities, and potentially higher paying jobs.
**Properties:** `previousStackable` & `nextStackable`
**Domain Includes:** `Credential`
**Range Includes:** `Credential`

Careful consideration should be given to exactly how these sequencing properties are identified since we will likely encounter sequencing with [`CareerPathway`](http://credreg.net/ctdl/terms/CareerPathway) and **may not** want a proliferation of properties for the same sequencing notions. This might lead us in the direction of something like `nextInSequence` and `previousInSequence` (where the things being sequenced are unidentified by the sequencing properties).

### Nested Credential

>**Definition:** An independent credential that is required or recommended by the credential being described such as an externally awarded certification.
**Property:** `nestedCredential`
**Domain Includes:** `Credential`
**Range Includes:** `Credential`

Our example of a degree that requires an independent award of a CompTIA certification fits here.

### Latticed Credential

>**Definition:** Another credential that is interwoven with the credential being described in mutually supporting ways, such as educational progress toward a license and a degree simultaneously. 
**Property:** `latticedWith`
**Domain Includes:** `Credential`
**Range Includes:** `Credential`

An example of latticed credentials would be our running example of the SRJC Dental Assistant Certificate (44 credit hours) and optionally an Associate of Science in Dental Hygiene (98 credit hours). Note the similarity here to the dual degree relationship.

### Lateral Credential

>**Definition:** A credential that enables an earner to move laterally across or between fields of study, such as a certification that is designed in relation to another certification.
**Property:** `lateralCredential`
**Domain Includes:** `Credential`
**Range Includes:** `Credential`

### Modular Credential 

>**Definition:** A module that has been designed as an intrinsic part of a credential that carries independent value, which can be combined in multiple ways with other modules and credentials and across multiple industries. 
**Property:** `standAloneModule`
**Subproperty Of:** `hasPart`
**Domain Includes:** `Credential`
**Range Includes:** `Credential`

Modularity implies a credential comprised of intrinsic parts capable of standing alone (i.e., useful, separate resources). 

Other naming possibilities might be `module` or `standAloneComponent` etc.

Note that this is akin to/same as, but more expressive than, hasPart and declared here as a sub-property of it..

**Comment by siuc-nate** [comment]
I would suggest something along these lines for Nested (in addition to declaring it as a subproperty of requires):
"An independent credential that is required or recommended by the credential being described and nested or embedded in it."

**Comment by stuartasutton** [comment]
## ADD

Use of the class `ceterms:Credential` implies all of the credential subclasses.

### Stackable Credential (properties defining stacking sequence)

> **URI:** ceterms:nextStackable
**Definition:** Credential that is next in a sequence of credentials that can be accumulated over time to build up a holder’s qualifications and help that holder move along a career pathway to further education, different responsibilities, and potentially higher paying jobs.
**Domain Includes:** `ceterms:Credential`
**Range Includes:** `ceterms:Credential`

> **URI:** ceterms:previousStackable
**Definition:** Credential that comes before another in a sequence of credentials that can be accumulated over time to build up a holder’s qualifications and help that holder move along a career pathway to further education, different responsibilities, and potentially higher paying jobs.
**Domain Includes:** `ceterms:Credential`
**Range Includes:** `ceterms:Credential`

### Nested Credential

> **URI:** `ceterms:nestedCredential`
**Definition:** An independently developed credential that is required or recommended such as an externally awarded certification.
**Comment:** For example, an independently awarded CompTIA® certification required by, and nested in, a degree.
**Usage Note:** For a module that has been designed as an integral part of a credential that carries independent value, use `ceterms:standAloneModule`.
**Domain Includes:** `ceterms:Credential`
**Range Includes:** `ceterms:Credential`

### Latticed Credential

>**URI:** `latticedWith`
**Definition:** Another credential that is interwoven with the credential being described in mutually supporting ways, such as educational progress toward a license and a degree simultaneously.
**Comment:** For example,  a dental assistant certificate at 44 credit hours and an optional Associate of Science degree in dental hygiene at 98 credit hours.
**Domain Includes:** `ceterms:Credential`
**Range Includes:** `ceterms:Credential`

### Lateral Credential

>**URI:** `ceterms:lateralCredential`
**Definition:** A credential that enables a credential holder to move laterally across or between fields of study, such as a certification that is designed in relation to another certification.
**Domain Includes:** `ceterms:Credential`
**Range Includes:** `ceterms:Credential`

### Modular Credential 

>**URI:** `ceterms:standAloneModule`
**Definition:** A module that has been designed as an integral part of a credential that carries independent value that can be combined in multiple ways with other modules and credentials. 
**Subproperty Of:** `hasPart`
**Domain Includes:** `ceterms:Credential`
**Range Includes:** `ceterms:Credential`

**Comment by stuartasutton** [comment]
Addition of these credential connection properties (relationships) are part of the larger suite:

### Relationships of Identity

>broadAlignment
exactAlignment
majorAlignment
minorAlignment
narrow Alignment

### Synergistic Relationships
> advancedStandingFrom
corequisite
isAdvancedStandingFor
isPreparationFor
lateralCredential
latticedWith
nestedCredential
nextStackable
preparationFrom
previousStackable
standAloneModule

### Compulsory/Recommended Relationships
> isRecommendationFor
isRequiredFor
requires
recommends

**Comment by siuc-nate** [comment]
I would suggest a common pattern of URIs to more easily group these together when discussing/presenting/etc. Something like:
- nextCredential
- previousCredential
- nestedCredential
- latticedCredential
- lateralCredential
- modularCredential

**Comment by stuartasutton** [comment]
Nate, I want to nix the "has" prefix since a "has" grouping isn't particularly useful. Also, we should not generalize nextCredential and previousCredential because it is not merely a sequencing we are after, but the intention sequence in a contact of stacking. We should not do the inverse until there is a clear demonstration that it's useful. I cannot see some or like Comptia wanting to add all those links.

**Comment by siuc-nate** [comment]
So then:
- nextStackableCredential
- previousStackableCredential
- nestedCredential
- latticedCredential
- lateralCredential
- modularCredential
?

**Comment by stuartasutton** [comment]
Two points:

1. At the beginning of this thread, I noted that the notion of sequencing (next/previous) would have at least two uses: (a) this one in stackable credentials, and (b) something yet to be explored to denote sequence in pathways. I think we need a super classes for the general notions that can be subclassed into a family of more specific relationships. Perhaps something like nextInPath and previousInPath as superclasses and then subclasses of nextStackableCredential and previousStackableCredential.

2. I'm a bit uncomfortable with modularCredential. Perhaps credentialModule would be more explicit and as subtype of hasPart.

**Comment by siuc-nate** [comment]
1. If the intent is to enable a broader range, then I would be fine with nextStackable/previousStackable; however, I'm not sure if one could consider assessments or learning opportunities to be stackable. But I don't know enough to judge. I'm weary of creating a superclass just for this - CTDL is complicated enough as-is.

2. Out of curiosity, would something that is modular want or need to refer to the other components it is modular with? Or would there be some external entity controlling which credentials go where in a set of modular pieces? I worry that tying credentials together by saying "this is modular with that" sort of defeats the purpose of calling them modular - my sense is that if something is truly modular with something else, it doesn't care what that something else is, or whether it's there at all. Modularity implies a lack of (specific) dependence, in my opinion.  But I may be overthinking it.  Anyway, credentialModule is probably just as fine as modularCredential.

**Comment by stuartasutton** [comment]
As for no. 1: OK. But it's like someone building an ontology that has classes for Cat and Dog and then being too weary to create a superclass for Animal. Out in the 'city park', semantic systems are going to want to know these kinds of class family ties so they can infer new information. That's the reason for superclasses. 

As for no. 2: Nate, given your rationale, there should not be any hasPart used in this context. In RDF, these 'components' are not neatly tucked inside the mother ship but are all separately useful entities that by definition can be referenced outside the context in which they are created. So, as independent URI-identified things, they have to have URIs, and, **more critically** they have to have properties to tie connect them.

**Comment by siuc-nate** [comment]
For 1.: If it's useful, I'm not opposed to adding it.  Just playing devil's advocate.

For 2. Fair enough - I was just curious about the logic behind it.

**Comment by stuartasutton** [comment]
## Resources

>[(Connecting Credentials) Glossary of Credentialing Terminology](http://connectingcredentials.org/wp-content/uploads/2016/06/Glossary-of-Credentialing-Terms.pdf)
[Credential Engine and Connecting Credentials Terms Crosswalk](https://docs.google.com/document/d/1zRHQeZN-O4_jMd3lq7rr8XH4ErFOLaiPEmGrntHn9rw/edit)
[Scaling "Stackable Credentials": Implications for Implementation and Policy](https://files.eric.ed.gov/fulltext/ED561777.pdf)


## Add

Use of the class `ceterms:Credential` implies all of the credential subclasses.

### Stackable Credential (properties defining stacking sequence)

> **URI:** ceterms:nextCredentialInStack
**Definition:** Credential that is next in a sequence of credentials that can be accumulated over time to build up a holder’s qualifications and help that holder move along a career pathway to further education, different responsibilities, and potentially higher paying jobs.
**Subproperty Of:** `ceterms:nextInSequence`
**Domain Includes:** `ceterms:Credential`
**Range Includes:** `ceterms:Credential`

> **URI:** ceterms:previousCredentialInStack
**Definition:** Credential that comes before another in a sequence of credentials that can be accumulated over time to build up a holder’s qualifications and help that holder move along a career pathway to further education, different responsibilities, and potentially higher paying jobs.
**Subproperty Of:** `ceterms:previousInSequence`
**Domain Includes:** `ceterms:Credential`
**Range Includes:** `ceterms:Credential`

### Nested Credential

> **URI:** `ceterms:nestedCredential`
**Definition:** Independently developed credential that is required or recommended such as an externally awarded certification.
**Comment:** For example, an independently awarded CompTIA® certification required by, and nested in, a degree.
**Usage Note:** For a module that carries independent value and has been designed as an integral part of a credential, use `ceterms:standAloneModule`.
**Domain Includes:** `ceterms:Credential`
**Range Includes:** `ceterms:Credential`

### Latticed Credential

>**URI:** `latticedCredential`
**Definition:** Credential that is interwoven with the credential in mutually supporting ways, such as educational progress toward a license and a degree simultaneously.
**Comment:** For example,  a dental assistant certificate at 44 credit hours and an optional Associate of Science degree in dental hygiene at 98 credit hours are latticed credentials.
**Domain Includes:** `ceterms:Credential`
**Range Includes:** `ceterms:Credential`

### Lateral Credential

>**URI:** `ceterms:lateralCredential`
**Definition:** Credential that enables a credential holder to move laterally across or between fields of study, such as a certification that is designed in relation to another certification.
**Domain Includes:** `ceterms:Credential`
**Range Includes:** `ceterms:Credential`

## Consider: GeneralProperties

### Next in Sequence

>**URI:** `ceterms:nextInSequence`
**Definition:** Immediately next entity in a series or sequence of entities.
**Domain Includes:** `rdfs:Resource`
**Range Includes:** `rdfs:Resource`

### Previous in Sequence

>**URI:** `ceterms:previousInSequence`
**Definition:** Immediately previous entity in a series or sequence of entities.
**Domain Includes:** `rdfs:Resource`
**Range Includes:** `rdfs:Resource`

**Comment by siuc-nate** [comment]
Per our 4-9-2019 meeting:
Closing this; may reopen if needed.
