### ISSUE TITLE
Add schema.org/inLanguage as equivalent property to ceterms:inLanguage

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#455]
We somehow left off of ceterms:inLanguage the equivalent property reference to schema.org/inLanguage.

**Comment by siuc-nate** [comment]
Actions to be taken:

**Add:**
> **Subject:** ceterms:inLanguage
> **Predicate:** owl:equivalentProperty
> **Object:** schema:inLanguage

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
