### ISSUE TITLE
undeclared namespace prefix errors in ctdl-encoding.ttl

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/vocabularies#456]
Trying to import ctdl-encoding.ttl into protege, I get errors because :
1. Namespace prefix 'dcterms' used but not defined   
2. Namespace prefix 'meta' used but not defined 
3. Namespace prefix 'purpose' used but not defined 

(I can fix well enough to get import working by guessing sensible URIs and adding @prefix lines)

**Comment by siuc-nate** [comment]
Thanks for catching these, Phil. We found the errors in [our release file](http://credreg.net/ctdl/schema/encoding/turtle?release=20170825):

1. We currently have "dct" rather than "dcterms" and will correct this
2. We will add the meta namespace with a coming update to our schema management system
3. Purpose was originally unstable; we created the PURL for it after stabilizing it but forgot to add it to the context and will correct this as well.

**Comment by siuc-nate** [comment]
On closer inspection, I am unable to find any instances of "dcterms". @philbarker is it possible you're using a saved (and perhaps outdated) copy of the encoding? Can you provide a link to it so I can verify it? Thanks.

**Comment by philbarker** [comment]
Thanks Nate, I should have said which version I was using. 
I used http://credreg.net/ctdl/schema/encoding/turtle?release=20170825 
I got it via http://credreg.net/ctdl/schema 
There is dcterms:description in the classes near the top.

**Comment by siuc-nate** [comment]
Thanks.

That explains why I didn't find dcterms - I was looking for it in the schema (perhaps in an "equivalentTo" or something) rather than the encoding itself. Should have been obvious, in hindsight.  Anyway, we'll make the corrections.

**Comment by siuc-nate** [comment]
The context should now have everything.  Note that due to a technical limitation with the current system, it has both a "dct" and a "dcterms" prefix that point to the same place. We'll be rolling out an update to that system soon which will render that unnecessary.  

Thanks again, @philbarker

**Comment by siuc-nate** [comment]
Closing this. If there's anything else that needs to be addressed here, feel free to reopen it.

**Comment by philbarker** [comment]
Thanks Nate, I can confirm that ctdl-encoding now imports into protege.

**Comment by siuc-nate** [comment]
Thanks, Phil.
