### ISSUE TITLE
Improve handling of geospatial terms in CTDL

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#460]
A week or two ago, @stuartasutton mentioned wanting to review the geospatial classes and properties in CTDL to see if we could make improvements.  Currently we have a variety of them, which were added at varying points in development, and they are somewhat difficult to explain and harmonize:

Classes:
- [ContactPoint](http://credreg.net/ctdl/terms/ContactPoint)
- [GeoCoordinates](http://credreg.net/ctdl/terms/GeoCoordinates)
- [JurisdictionProfile](http://credreg.net/ctdl/terms/JurisdictionProfile)
- [PostalAddress](http://credreg.net/ctdl/terms/PostalAddress)

Properties:
- [accreditedIn](http://credreg.net/ctdl/terms/accreditedIn)
- [address](http://credreg.net/ctdl/terms/address)
- [addressCountry](http://credreg.net/ctdl/terms/addressCountry)
- [addressLocality](http://credreg.net/ctdl/terms/addressLocality)
- [addressRegion](http://credreg.net/ctdl/terms/addressRegion)
- [approvedIn](http://credreg.net/ctdl/terms/approvedIn)
- [availabilityListing](http://credreg.net/ctdl/terms/availabilityListing)
- [availableAt](http://credreg.net/ctdl/terms/availableAt)
- [availableOnlineAt](http://credreg.net/ctdl/terms/availableOnlineAt)
- [geoURI](http://credreg.net/ctdl/terms/geoURI)
- [globalJurisdiction](http://credreg.net/ctdl/terms/globalJurisdiction)
- [jobsObtained](http://credreg.net/ctdl/terms/jobsObtained)
- [jurisdiction](http://credreg.net/ctdl/terms/jurisdiction)
- [jurisdictionException](http://credreg.net/ctdl/terms/jurisdictionException)
- [latitude](http://credreg.net/ctdl/terms/latitude)
- [longitude](http://credreg.net/ctdl/terms/longitude)
- [mainJurisdiction](http://credreg.net/ctdl/terms/mainJurisdiction)
- [offeredIn](http://credreg.net/ctdl/terms/offeredIn)
- [postalCode](http://credreg.net/ctdl/terms/postalCode)
- [postOfficeBoxNumber](http://credreg.net/ctdl/terms/postOfficeBoxNumber)
- [recognizedIn](http://credreg.net/ctdl/terms/recognizedIn)
- [regulatedIn](http://credreg.net/ctdl/terms/regulatedIn)
- [renewedIn](http://credreg.net/ctdl/terms/renewedIn)
- [residencyType](http://credreg.net/ctdl/terms/residencyType)
- [residentOf](http://credreg.net/ctdl/terms/residentOf)
- [revokedIn](http://credreg.net/ctdl/terms/revokedIn)
- [spatialCoverage](http://credreg.net/ctdl/terms/spatialCoverage)
- [streetAddress](http://credreg.net/ctdl/terms/streetAddress)

Concept Schemes / Concepts:
- [Audience](http://credreg.net/ctdl/terms/Audience)
  - [Citizen](http://credreg.net/ctdl/vocabs/audience/Citizen)
  - [NonCitizen](http://credreg.net/ctdl/vocabs/audience/NonCitizen)
  - [NonResident](http://credreg.net/ctdl/vocabs/audience/NonResident)
  - [Resident](http://credreg.net/ctdl/vocabs/audience/Resident)
- [Residency](http://credreg.net/ctdl/terms/Residency)
  - [InState](http://credreg.net/ctdl/vocabs/residency/InState)
  - [International](http://credreg.net/ctdl/vocabs/residency/International)
  - [Local](http://credreg.net/ctdl/vocabs/residency/Local)
  - [OutOfState](http://credreg.net/ctdl/vocabs/residency/OutOfState)
  - [Regional](http://credreg.net/ctdl/vocabs/residency/Regional)

Notes:
- Some of these relate to the groups of properties that define relationships (e.g., ___By, ___In, ___s, ___Service) - perhaps these groups should be reviewed for optimization as well
- The ContactPoint class's other properties may be tangentially related
- This will likely also influence a proposal discussed internally to enable issuing a CTID to a campus/address (effectively either a mini-organization or an expansion of PostalAddress) so it can be referenced
  - This may also influence the use of subOrganization, department, and parentOrganization, since those would currently be the "right" way to handle campus locations
- According to the definition of [spatialCoverage](http://credreg.net/ctdl/terms/spatialCoverage), many of these properties should also be subproperties of spatialCoverage

Summary:
@stuartasutton is quite right - these could do with a lot of cleaning up. Geospatial terms seem to mostly fall into one of two buckets: Terms to indicate an area (e.g., JurisdictionProfile) and terms to indicate a specific place (e.g., PostalAddress).  However, this is complicated by the interplay of an area and things that happen in that area (e.g. the relationship properties) as well as cases where address and other information have a many-to-many relationship (e.g., socialMedia, telephone, etc., applying to 0-n locations vs being organization-wide).

We will have to be very mindful of the ripple effects of any changes we make here.

**Comment by siuc-nate** [comment]
One proposal that @cwd-mparsons and I discussed would be to create a new class (something like ceterms:Place) that would essentially combine the properties of both PostalAddress and GeoCoordinates (and possibly ContactPoint).  This would grant the added utility of being able to directly associate a latitude and longitude with an address in addition to simplifying the location-related information tied to contact point, on top of solving the "campus" issue mentioned in the post above.

**Comment by siuc-nate** [comment]
Proposal:
1. Create a new class and merge ceterms:GeoCoordinates and ceterms:PostalAddress into it:

**URI:** ceterms:Place
**Label:** Place
**Definition:** A location or area.
**Properties:**
- ceterms:name
- ceterms:description
- ceterms:latitude
- ceterms:longitude
- ceterms:streetAddress
- ceterms:addressLocality
- ceterms:addressRegion
- ceterms:postalCode
- ceterms:postOfficeBoxNumber
- ceterms:targetContactPoint

2. Update the range of all properties that currently point to either ceterms:GeoCoordinates or ceterms:PostalAddress to instead point to ceterms:Place

3. Deprecate (or just destabilize) ceterms:GeoCoordinates and ceterms:PostalAddress

5. Remove ceterms:CredentialOrganization and ceterms:QACredentialOrganization from the domain of ceterms:targetContactPoint

**Comment by stuartasutton** [comment]
While accepting the changes noted above in terms of the creation of a new `ceterms:Place` class and the consolidation of terms from `ceterms:GeoCoordinates` and `PostalAddress` for both general use and as *controlling in the Registry*, I think we should not follow through with note no. 3 (i.e., deprecating). Instead, while adding `ceterms:Location`, pare down the acceptable properties of GeoCoordinates and PostalAddress in the CTDL thus:

### GeoCoordinates
`ceterms:geoURI`
`ceterms:latitude`
`ceterms:longitude`
`ceterms:name`

### PostalAddress
`ceterms:addressCountry`
`ceterms:addressLocality`
`ceterms:addressRegion`
`ceterms:name`
`ceterms:postalCode`
`ceterms:postOfficeBoxNumber`
`ceterms:streetAddress`

That would entail the properties having two domains, but that is not a problem in either RDF or schema.org.

**Comment by siuc-nate** [comment]
The proposal to do something about GeoCoordinates and PostalAddress is partly in hopes of making CTDL easier to understand for newer developers - having those in addition to a Location class may actually make things worse. I do see the potential usefulness of them (or at least, of address) at some point, so maybe deprecating is too harsh.  Would it suffice to remove them from the range of any properties that currently point to them (Item 2 in my post above) so as to disconnect them from real interaction with other parts of CTDL?

**Comment by stuartasutton** [comment]
Yes, removal from range would have that affect.

**Comment by stuartasutton** [comment]
Where do we stand on this issue around our locational classes. We are in agreement with your [comment above](https://github.com/CredentialEngine/vocabularies/issues/460#issuecomment-331547950), Nate, to consolidate properties from `GeoCoordinates` and `PostalAddress`. But what have we decided about my [comment above](https://github.com/CredentialEngine/vocabularies/issues/460#issuecomment-331627509) about **not** deprecating `GeoCoordinates` and `PostalAddress` but paring down the properties to make each very precise?

**Comment by siuc-nate** [comment]
Actions to be taken:

**Create**
**URI:** ceterms:Place
**Label:** Place
**Definition:** Entity describing a physical location or geospatial area.
**Properties:**
- ceterms:name
- ceterms:description
- ceterms:geoURI
- ceterms:latitude
- ceterms:longitude
- ceterms:streetAddress
- ceterms:addressLocality
- ceterms:addressRegion
- ceterms:addressCountry
- ceterms:postalCode
- ceterms:postOfficeBoxNumber
- ceterms:targetContactPoint

Remove **ceterms:GeoCoordinates** from the **rdfs:domainIncludes** of these properties:
- ceterms:availableAt
- ceterms:jurisdictionException
- ceterms:mainJurisdiction
- ceterms:region
- ceterms:address

Remove **ceterms:PostalAddress** from the **rdfs:domainIncludes** of these properties:
- ceterms:address
- ceterms:availableAt

Add **ceterms:Place** to the **rdfs:domainIncludes** of these properties (all of the properties that no longer point to GeoCoordinates or PostalAddress):
- ceterms:address
- ceterms:availableAt
- ceterms:jurisdictionException
- ceterms:mainJurisdiction
- ceterms:region

Remove the following from the **rdfs:domainIncludes** of **ceterms:targetContactPoint** (its only domain will be **ceterms:Place** and **ceterms:CredentialPerson**):
- ceterms:CredentialOrganization
- ceterms:QACredentialOrganization
- ceterms:PostalAddress

The end result of these changes should be:
- The creation of ceterms:Place as described above
- ceterms:GeoCoordinates and ceterms:PostalAddress having the properties described in https://github.com/CredentialEngine/vocabularies/issues/460#issuecomment-331627509
- No properties having an rdfs:rangeIncludes of GeoCoordinates or PostalAddress
- All properties that used to point to GeoCoordinates or PostalAddress now point to Place
- Significantly more sanity in our handling of geospatial data

**Comment by siuc-nate** [comment]
These changes have been made in the schema and marked in the history tracking.
