### ISSUE TITLE
Review resultingAward for the logic

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#461]
The [`ceterms:resultingAward`](http://credreg.net/ctdl/terms/resultingAward) property has a number of classes in its range that don't make sense to me in the context of CTDL when applied to nearly every possible action of a QA/credentialing organization. The range of property is the class of awarded credentials ([`ceterms:CredentialAssertion`](http://credreg.net/ctdl/terms/CredentialAssertion)) that result from certain actions (the domain).  Thus, logically, the property supports assertions such as: "Action A results in Credential Award B". That makes sense with actions like [`ceterms:AccreditAction`](http://credreg.net/ctdl/terms/AccreditAction) and less sense with an action like [`cdterms:RevokeAction`](http://credreg.net/ctdl/terms/RevokeAction) or [`ceterms:AdvancedStandingAction`](http://credreg.net/ctdl/terms/AdvancedStandingAction). There will be many who balk at the logic that a decision to revoke a certification results in the award of a "credential of revocation of your cerification".

But note that this is in the context of a specific property: [`ceterms:resultingAward`](http://credreg.net/ctdl/terms/resultingAward). The intention of the property should be to provide the means of saying that an action **actually puts a credential in the hands of some holder**. That would limit the range of applicable actions **for this property**, I would think.

**Comment by stuartasutton** [comment]
Correction: I meant it has a number of classes in its domain, not range.

**Comment by siuc-nate** [comment]
Per our 9/26/2017 call:
The following classes should be removed from the domain of ceterms:resultingAward:

- ceterms:AdvancedStandingAction
- ceterms:ApproveAction
- ceterms:CredentialingAction
- ceterms:OfferAction
- ceterms:RecognizeAction
- ceterms:RegulateAction
- ceterms:RevokeAction
- ceterms:RightsAction

**Comment by stuartasutton** [comment]
I agree with the removals.

**Comment by siuc-nate** [comment]
These changes have been made and marked in history tracking.
