### ISSUE TITLE
Is there value in adding a property to describe or summarize what has changed in a document being published

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#462]
A few partners have asked how they would know what has changed for, say a credential, when viewing or retrieving the content. We have an existing issue #441 , regarding adding dateCreated, and dateModified. 
An optional property, say UpdateSummary, could be added to allow the publisher to provide a short description of any significant changes in the current update. Anyone with a specific interest in the credential, could use this summary to determine whether to "consume" this updated document.

**Comment by stuartasutton** [comment]
I'm concerned that no one would provide anything of real utility.

**Comment by siuc-nate** [comment]
Per our 9/26/2017 meeting:
It is too likely that people will not use this property in a worthwhile manner.  So for now, we won't include it.
