### ISSUE TITLE
Extend the domain of ceterms:versionIdentifier to include Learning Opportunities

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#463]
Currently, http://credreg.net/ctdl/terms/versionIdentifier can only be used with Credentials and Assessments.

In order to enable publishers to identify learning opportunities in the registry using their own identifiers, the domain of versionIdentifier should be extended to include ceterms:LearningOpportunityProfile

Proposal:

**Add:**
> **Subject:** ceterms:versionIdentifier
> **Predicate:** rdfs:domainIncludes
> **Object:** ceterms:LearningOpportunityProfile

**Comment by stuartasutton** [comment]
My assumption is that this was decided in the affirmative on our call today.

**Comment by siuc-nate** [comment]
This change has been made and noted in history tracking.
