### ISSUE TITLE
The property longitude is mispelled

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#464]
We have [longititude](http://credreg.net/ctdl/terms#longititude) instead of longitude.

**Comment by siuc-nate** [comment]
Wow, how did that one slip by? 

Are we looking at a simple direct correction or do we need to deprecate/create new property, put in history tracking, etc.?

**Comment by siuc-nate** [comment]
Per our 9/26/2017 call,
We will make this change directly.

**Comment by siuc-nate** [comment]
This change has been made.
