### ISSUE TITLE
Possible deprecating of credentialAlignment

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#465]
The [ceterms:credentialAlignment](http://purl.org/ctdl/terms/credentialAlignment) property was defined very early the CTDL history and was intended to serve as a property that serves the same purpose in the CTDL as the [educationalAlignment](http://schema.org/educationalAlignment) in  schema.org. The original intention for the property here was for it to serve as a super property (thus it has no domain) with the full array of those subproperties defining relationships between entities and the [ceterms:CredentialAlignmentObject](http://purl.org/ctdl/terms/CredentialAlignmentObject).

Since I doubt (hope) that such a property would not be the approach chosen with the schema.org Credential addition as it was for the LRMI addition, I'd like to put it on the chopping block for deprecation (after running it past Phil).

**Comment by siuc-nate** [comment]
Fine by me.

**Comment by siuc-nate** [comment]
Action to be taken:

**Remove:**
> **Subject:** ceterms:credentialAlignment
> **Predicate:** vs:status
> **Object:** vs:stable

**Add:**
> **Subject:** ceterms:credentialAlignment
> **Predicate:** vs:status
> **Object:** vs:deprecated

**Comment by siuc-nate** [comment]
This change has been made and noted in history tracking.
