### ISSUE TITLE
Range of alignment properties

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#467]
The "___alignment" properties (below) all have a range of both Credential and ConditionProfile. Is ConditionProfile necessary for these? Would a credential align conditionally (ie based on location or experience or anything else in ConditionProfile)?

- ceterms:broadAlignment
- ceterms:exactAlignment
- ceterms:majorAlignment
- ceterms:minorAlignment
- ceterms:narrowAlignment

**Comment by stuartasutton** [comment]
No they should not have a ConditionProfile in range.

**Comment by siuc-nate** [comment]
Proposal:

Remove **ceterms:ConditionProfile** from the **rdfs:rangeIncludes** of:
- ceterms:broadAlignment
- ceterms:exactAlignment
- ceterms:majorAlignment
- ceterms:minorAlignment
- ceterms:narrowAlignment

**Comment by siuc-nate** [comment]
These changes have been made and noted in history tracking.
