### ISSUE TITLE
ceterms:CareerPathway

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#47]
As part of it, define a ctdl:Pathway class...

**Comment by stuartasutton** [comment]
See: 
> **targetPathway:** (http://www.credreg.net/page/propertiesviewer#targetPathway)
> **CareerPathway:** (http://www.credreg.net/page/propertiesviewer#CareerPathway)

Per the issue title, I have defined targetPathway as having a domain of ConditionProfile...but am a bit uncertain why. It seems to me that the career pathways to which a credential might be applicable are simply descriptive and might just as well have a domain of Credential.  The path to ConditionProfile is through the properties requires, recommends etc. and I am struggling to see the applicability of these properties (or at least their applicability in the absence of Credential being in the domain list.

**Comment by stuartasutton** [comment]
I am closing this issue...**BUT** note my question of why the targetPathway is not a property of credential.

**Comment by siuc-nate** [comment]
The original intent was that the requirements themselves had a relationship to a pathway (e.g., a fast track program, defined via ConditionProfile, could point to a fast track program pathway object) - however, I can see what you mean.  Any of our first-class citizen objects (other than organization) could conceivably be a _part of_ a pathway.

We have not defined anything about a pathway object and should probably discuss it more thoroughly before we determine exactly how it fits into the rest of the schema.

**Comment by siuc-nate** [comment]
We need to define the CareerPathway class. Below is where we started. We need input from @bobgsheets 
![pathwaystart](https://cloud.githubusercontent.com/assets/21346519/19317984/792504a0-906c-11e6-8bcb-d314aa6e499c.PNG)

**Comment by jkitchensSIUC** [comment]
Updated Class data:
https://docs.google.com/document/d/1mxux1JZYs4sl-qI8N7pFUwK2rXMOQVK1n9nKtChqna8/edit

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate is the unresolved part of this issue only related to the Pathways class that we're going to work on with a small group of experts or is there still something in here that's unresolved and not a Pathways issue?

**Comment by siuc-nate** [comment]
We have discussed pathway profile, and planned it out somewhat; however, it has not yet been added to our schema - @stuartasutton do we still need to keep this issue open until we've discussed pathways with an experts group and added it to the schema?

**Comment by bobgsheets** [comment]
I thought we decided to say it is not stable and establish an experts
group.  But we need to communicate we will be working on it.

**Comment by siuc-nate** [comment]
Refer to http://credreg.net/ctdl#CareerPathway

**Comment by ottonomy** [comment]
@siuc-nate Thanks for the good talk today. We'd love to collaborate if you choose to open this back up again. There is some potential to take advantage of a bunch of companies who have been thinking about this if you're open to it. Or a lot of risk of incompatible approaches if we can't figure out how to work together. 

One of the key innovations over the last couple reflected in the Pathway models we are using in our cluster of partners is that the pathway is not made up of credentials themselves, but that there are relationships between credentials and the structural element of the pathway. Would love to show you how it works sometime after our demo next week. You can get a sneak preview in the morning, 9am PST https://acrl.webex.com/acrl/onstage/g.php?MTID=e3309eef3549e8b8df9a07eaab203b933 ;)

**Comment by stuartasutton** [comment]
@ottonomy, an interesting coincidence that at about the same time you were meeting, I was thinking about using some or all of the TAC's March call to have an open, wide-ranging discussion around the approach to be taken with pathways. So, while this github issue was closed, the focus on the topic within CTDL is just beginning.

**Comment by siuc-nate** [comment]
Thanks @ottonomy 
Unfortunately I will be in a meeting around that time, but if it ends early or something, I will try to check it out.

As for the issue, it was only closed because there is no current action to be taken and this issue is more of a pending/documentation issue at this time. We will reopen it once we're ready to really get into the Pathway class.
