### ISSUE TITLE
Consider removing 'subject' from the ceasn profile

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#472]
We should consider removing the [`ceasn:subject`](http://credreg.net/ctdlasn/terms/subject#subject) property borrowed from ASN because of its narrow "learning area/discipline" focus which is very likely to be confused with the topicality of a competency covered by the [`ceasn:conceptTerm`](http://credreg.net/ctdlasn/terms/conceptTerm#conceptTerm) and [`ceasn:conceptKeyword`](http://credreg.net/ctdlasn/terms/conceptKeyword#conceptKeyword) properties. 

While the [`ceasn:subject`](http://credreg.net/ctdlasn/terms/subject#subject) could be used (e.g., consider `asn:careerEducation` in the BCSP competenies), that utility seems very small in light of the poor quality of data we will likely receive given the narrow definition of the term.

**Comment by siuc-nate** [comment]
How does this gel with our use of [subject](http://credreg.net/ctdl/terms/subject) in CTDL? I would think we would want to be consistent.

**Comment by stuartasutton** [comment]
I think we should not violate ASN where it has very specific meaning. The `conceptTerm` and the `conceptKeyword` handle the job of subject. We should probably declare both of them as subtype of `dct:subject` and equivalent to `schema.org/about`.

**Comment by siuc-nate** [comment]
Should we also declare equivalency between `ceasn:conceptTerm` and `ceterms:subject`, and also between `ceasn:conceptKeyword` and `ceterms:keyword`? 

As for "removing" `ceasn:subject`, would that be deprecation or just emptying its domain?

**Comment by stuartasutton** [comment]
Since we are treating these changes as pre-first release for the ctdlasn, just remove `ctdlasn:subject`. Declaring an equivalence between `ceasn:conceptTerm` and `ceterms:subject`, and also between `ceasn:conceptKeyword` and `ceterms:keyword` is fine.

**Comment by siuc-nate** [comment]
This has been taken care of.
