### ISSUE TITLE
Adding ctid to competency framework and competency?

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#475]
If there is an anticipation of using the `ceterms:ctid`, it needs to be added to the `ceasn` schema. I think the property used should be from the `ceterms` namespace--i.e., we should **not** create a new property (`ceasn:ctid`).

**Comment by siuc-nate** [comment]
The management system wasn't designed to do cross-schema stuff like that. It may work, partially, but I will need to carefully test all the features.

**Comment by stuartasutton** [comment]
I am ABSOLUTELY NOT suggesting that we add ctid if it is not deemed absolutely necessary.

**Comment by siuc-nate** [comment]
I think I have cross-schema stuff functioning now - but it hasn't been tested very thoroughly, so I am concerned about possible issues: http://credreg.net/ctdlasn/terms/ctid
