### ISSUE TITLE
Handling initial updates to CTDL ASN schema

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#476]
@stuartasutton Given the large number of significant changes to be dealt with and the relative newness of the CTDLASN schema, do we need to treat it in its current state as a proper release and log all the changes and bother with all the history tracking and so on? Or should we just make the changes now and get them out of the way before anyone has time to really do anything with the schema?

**Comment by stuartasutton** [comment]
No, I don't think we need to treat these changes as a regular release on the ctdlasn.

**Comment by siuc-nate** [comment]
Thanks. Will do.
