### ISSUE TITLE
Revise occupationType usage note to include ISCO-08

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#485]
We need to add to the usage note for [ceterms:occupationType](http://purl.org/ctdl/terms/occupationType) references to [ISCO-08](http://www.ilo.org/public/english/bureau/stat/isco/isco08/) and  [SOC 2010](https://www.ons.gov.uk/methodology/classificationsandstandards/standardoccupationalclassificationsoc/soc2010).

**Comment by siuc-nate** [comment]
Something like:

For U.S. credentials, best practice is to identify an occupation using a framework such as the O*Net. Other credentials may use any framework of the class ceterms:OccupationClassification such as the EU's ESCO, ISCO-08 and SOC 2010.

**Comment by siuc-nate** [comment]
This change has been made and noted in history tracking.
