### ISSUE TITLE
Distinguish between ceterms:contactType and ceterms:contactOption

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#486]
The original definitions/comments/etc. for these two properties:
https://github.com/CredentialEngine/vocabularies/issues/287 (contactType)
https://github.com/CredentialEngine/vocabularies/issues/305 (contactOption)

are quite different from what they are now:
http://credreg.net/ctdl/terms/contactType#contactType
http://credreg.net/ctdl/terms/contactOption#contactOption

And now, I would be hard-pressed to explain a sufficient difference between:
"Option for a toll-free number or support for hearing-impaired callers."
and
"Text identifying the type of service provided by an organizational contact. A person or organization may have different contact points for different services. The contact type property provides for adding text to identity the service; e.g., "toll-free number" or "support for hearing-impaired callers"."

The fact that both reference the same example (support for hearing-impaired callers) doesn't help much.  I suspect that these two properties may have been mixed up at some point.  I think they should be revised to more closely reflect their original definitions.  Something like:

**contactType:** "A brief, descriptive name of the type of Contact Point. Examples may include "Registration", "Transcripts", "Verifications", and "Financial Assistance"."
**contactOption:** "A brief, descriptive name of an aspect of the Contact Point. Examples may include "Toll-free" and "TTY".

Alternatively, since: 
1. contactOption's values _could_ arguably be merged into contactTypes (e.g., "toll-free helpdesk" or "registration (TTY)"), and 
2. you would need one ContactPoint for each combination anyway ("registration" and "registration (TTY)" would be two separate ContactPoints regardless), and
3. contactOption seems to only be relevant to phone numbers (I could be convinced otherwise):

It may be better to **deprecate** contactOption and revise the definition of contactType to something like:

**contactType:** "A brief, descriptive name of the type of Contact Point. Examples may include "Registrations", "Transcripts", "Toll-Free Helpdesk", and "Financial Assistance (TTY)".

Thoughts?

**Comment by stuartasutton** [comment]
I agree, that contactOption is best deprecated. It's use is confusing even in schema.org.

**Comment by siuc-nate** [comment]
Actions to be taken:
- Deprecate ceterms:contactOption
- Remove the domain and range from ceterms:contactOption
- Add meta:supersededBy to ceterms:contactOption pointing to ceterms:contactType

**Comment by siuc-nate** [comment]
This has been taken care of in the schema management system and noted in the history tracking.
