### ISSUE TITLE
Add Comment to learnMethod:Gaming

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#487]
Currently, [learnMethod:Gaming](http://purl.org/ctdl/vocabs/learnMethod/Gaming) has the following definition:

>"Provides interactive educational experiences which demonstrate concepts in a way that promotes critical thinking, overcoming challenges within prescribed rule sets, problem solving, and in some cases, teamwork and/or competition."

Consider adding the following Comment:

> "Individual or group games that have cognitive, social, behavioral, and/or emotional dimensions which are related to educational objectives." 

(Adapted from the *ERIC Thesaurus* definition of "Educational Games" https://eric.ed.gov/?qt=game&ts=on&ti=Educational+Games)

**Comment by stuartasutton** [comment]
Note that additional learning methods for the [learnMethod](http://www.credreg.net/ctdl/terms#LearningMethod) vocabulary might be gleaned from the *MedBiquitous* standardized instructional and assessment methods at https://medbiq.org/curriculum/vocabularies.pdf.

**Comment by siuc-nate** [comment]
Action to be taken:

**Add:**
> **Subject:** learnMethod:Gaming
> **Predicate:** dct:description
> **Object:** Individual or group games that have cognitive, social, behavioral, and/or emotional dimensions which are related to educational objectives.

**Comment by siuc-nate** [comment]
This change has been made and noted in history tracking.

**Comment by cameronstewart13** [comment]
Check out the <a href="https://dariusreviews.com/best-graphics-cards-2022/">best graphics cards 2022</a>
