### ISSUE TITLE
Removing CredentialOrganization and QACredentialOrganization from ceasn tables

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#488]
Nate, a CompetencyFramework references CredentialOrganizations and QACredentialOrganizations; but, there is no need to include definitions of them in the tables for the CE profile of the ASN when all that happens in instance data for competencies is that they reference instances of CredentialOrganization and QACredentialOrganization entities defined in the /ctdl/terms/ namespace. So that simply show up in competency framework data as objects of properties and should not be redefined here.

**Comment by siuc-nate** [comment]
That's actually what's happening here - the data itself is being pulled from the CTDL (ceterms) namespace.  

Come to think of it, do we need something similar within CTDL where we currently have placeholder classes for Competency and CompetencyFramework?

**Comment by siuc-nate** [comment]
If we need to not show them as though they are a part of the schema (i.e. only have them show up in the range of a few properties), that is doable - I'll just need to tweak some things in the validation to make sure everything still works (we would also need to determine whether or not to permit a "pointer" class to be used in these cases).

Let me know.

**Comment by stuartasutton** [comment]
I understand, Nate, but the tables give the impression that these org classes are being defined here.

As for the Competency and CompetencyFramework in  /ctdl/terms/, let me think about it...What we don't want to do is anything that triggers a lot of updates in /ctdl/terms/.

**Comment by siuc-nate** [comment]
All right. I will make the changes.

**Comment by siuc-nate** [comment]
I have made the changes - note that this shouldn't affect anything semantic in the schema; the properties which point to those classes still do. It's just that those classes are no longer being "imported" into the schema.  I have also updated the registry profile to compensate for the classes not being there.
