### ISSUE TITLE
Handling of address/email/ContactPoint in the context of organization

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#489]
When we added ceterms:Place and moved ContactPoint into it via targetContactPoint, one thing we didn't address was the fact that organizations have email at the organization level - meaning emails at the organization level cannot have any type association (e.g., no "contactType").  

Is it correct to leave contextless email addresses at the organization level while also enabling contextual email addresses within ContactPoint?

i.e., do we want:

CredentialOrganization -> email -> "email@email.com"
and
CredentialOrganization -> address -> Place -> targetContactPoint -> ContactPoint -> email -> "email@email.com"

@stuartasutton I remember that we discussed the matter of removing targetContactPoint from the organization, and that we agreed to do so - however, we do not appear to have documented _why_ we did so. Do you recall?

**Comment by stuartasutton** [comment]
Well, other heads should look at this, but, my sense is that an email address directly off an org is OK and shouldn't need a 'contextual email'. If it's a targeted email (contextual) then ContactPoint should be used.

**Comment by cwd-mparsons** [comment]
@stuartasutton @siuc-nate 
Nate also mentioned ContactPoint. There used to be targetContactPoint under organization.  The editor was set up to allow entering a context with email and phone numbers. These are all to be published as ContactPoints, as below:
![image](https://user-images.githubusercontent.com/26332112/32397938-2df0357a-c0ba-11e7-9531-56844ebdb628.png)

The example still uses targetContactPoint. It seems to make sense to be able to add contactPoints directly under an organization. Should targetContactPoint be added back to organization, or do all contactPoints need to be added under Place?

**Comment by siuc-nate** [comment]
Per our 11/71/2017 call:
We will not make any changes to this unless/until we encounter a use case that gives us a strong reason to do so.

**Comment by siuc-nate** [comment]
One thing that just came to my attention (thanks @cwd-mparsons ): 
The Organization class requires one of:
- address
- email
- targetContactPoint

As of the October release, targetContactPoint is no longer an option.  However, it can still be accessed via Place (which in turn is accessed via address), so it should be fine.
