### ISSUE TITLE
Reuse of CTDL properties and concept schemes in CE-ASN data

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#495]
OK, we have pushed the redeclaration of terms in other namespaces TOO FAR when we redeclare terms in OUR OWN namespaces! Currently, in the CE-ASN data, we have declared the property [`ceasn:educationLevelType`](http://purl.org/ctdlasn/terms/educationLevelType) as equivalent to [`ceterms:educationLevelType`](http://purl.org/ctdl/terms/audienceLevelType). We should be using the CTDL properties in the CE-ASN data where they are applicable and not redeclaring them in a separate namespace! 

At least we don't re-declare the [`AudienceLevel`](http://purl.org/ctdl/terms/AudienceLevel) concept scheme in both places ...which is good!

So:

1. Deprecate [`ceasn:educationLevelType`](http://purl.org/ctdlasn/terms/educationLevelType); and 
2. Use [`ceterms:educationLevelType`](http://purl.org/ctdl/terms/audienceLevelType) instead in the CE-ASN data.

**Comment by stuartasutton** [comment]
On a slightly similar note, we have functionally declared the nearly identical  publication status vocabulary in both the the CTDL and CEASN namespaces. The same namespace could have been used for both had we avoided our penchant to make properties that would serve in any publication context so precise as to render them useless across contexts. Even though "probationary" would be unlikely to show up in a competency context, nothing precludes  enumerating those terms from the vocabulary that are applicable by using a useValuesFrom constrain in the Competency Framework context and identifying the acceptable concepts.

**Comment by stuartasutton** [comment]
We need to add `ceterms:weight` and `ceasn:weight` to this issue's list of duplications within our own namespaces. I suggest that we:

### DROP

> `ceasn:weight`

### INSTEAD INCLUDE

> `ceterms:weight` (as revised per #509) to the CE ASN profile

**Comment by siuc-nate** [comment]
Per our 4-10-2018 call, we will cancel this issue.
