### ISSUE TITLE
Create new publisherName property to distinguish between literal and URIref

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#496]
Currently, the ASN represents a publisher by literal; there is no means of referencing an RDF description of the publisher. I am suggesting a new publisherName for the literal and publisher for URIref. I've done this in the mapping spreadsheet at [1].

Stuart 

[1] https://docs.google.com/spreadsheets/d/1E1dXPxLGqNJ5Gr_wxk9sGS6CwuvavhjbaFCXhZmBCf8/edit#gid=1476845803

**Comment by stuartasutton** [comment]
## Change `ceasn:publisher` to:

>**URI:** ceasn:publisher
**Label:** Publisher
**Definition:** "An entity responsible for making this entity available."
**Comment:** "Also referred to as the promulgating agency of the entity."
**Equivalent To:** dct:publisher
**Domain Includes:** ceasn:CompetencyFramework, ceasn:ConceptScheme
**Range Includes:**  ceterms:CredentialOrganization, ceterms:QACredentialOrganization

## Add `ceasn:publisherName`:

>**URI:** ceasn:publisherName
**Label:** Publisher Name
**Definition:** "Name of an entity responsible for making this entity available."
**Comment:** "Also referred to as the promulgating agency of the entity."
**Equivalent To:** dc:publisher
**Domain Includes:** ceasn:CompetencyFramework, ceasn:ConceptScheme
**Range Includes:**  rdf:langString

**Comment by siuc-nate** [comment]
These changes have been made.

Leaving this open pending resolution to the question in https://github.com/CredentialEngine/vocabularies/issues/494#issuecomment-356438565
