### ISSUE TITLE
Create a FinancialAssistanceProfile?

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#499]
This issue is to start a discussion of a specific proposal for a `FinancialAssistanceProfile` and stems from issue #466 and more specifically:

1. https://github.com/CredentialEngine/vocabularies/issues/466#issuecomment-334106812

2. https://github.com/CredentialEngine/vocabularies/issues/466#issuecomment-334110703

**Comment by stuartasutton** [comment]
Creation of a FinancialAssistanceProfile would entail deprecating [FinancialAlignmentObject](http://purl.org/ctdl/terms/FinancialAlignmentObject) and changing the range of the [financialAssistance](http://purl.org/ctdl/terms/financialAssistance) property to FinancialAssistanceProfile.

**Comment by siuc-nate** [comment]
Copied from my comment on the other issue:

For the record, the reason we had used AlignmentObject for this was so that we wouldn't need to schematize the various ways in which financial assistance can be structured - we just wanted to _point_ to it.  This saves a lot of complexity, and ensures we don't miss something important since none of us are experts in this field.  

I really don't think we want to get into trying to define a schema for financial assistance (as a standalone entity), much less take the extra step of creating a manifest for it.

Descriptions of financial assistance can take whole websites - let those do their job, let us just reference them. **Let's not reinvent the wheel.**

**Comment by philbarker** [comment]
Please excuse me if I am missing some background knowledge here, but that does not sound like a good reason for using an AlignmentObject. If you want just to point to an existing description of what financial financial support is available, then the best way would be 1: decide what type of object such a description is about (from schema.org I would say CreativeWork is a good match, but Offer and Product are also possible). 2: decide whether this is a specific enough to identify the type of object you expect, if not define a subtype. 3: use the @id or schema:url property of that object (possibly with schema:name and schema:description)  to identify and locate the information.

**Comment by stuartasutton** [comment]
@siuc-nate, I think you have your history of this issue a bit wrong. The ceterms:financialAssistance property has been around a long time and it points to a ceterms:FinancialAlignmentObject because it's original intent was to point to a node in a financial assistant type vocabulary. I've raised that that the ceterms:FinancialAlignmentObject should be deprecated and ceterms:CredentialAlignmentObject. But, you wanted to use it in a "llose" manner...i.e., no defined framework...instigating my much-repeated objection to using ceterms:CredentialAlignmentObject just because it works for something as a kind of data structure. 

So, let's pause and go back to why you raised the issue in the first place which was because even the use of ceterms:CredentialAlignmentObject wasn't working for what you were encountering. Please pull together some real world examples that present the original problem you were encountering for review before we consider any changes.

**Comment by siuc-nate** [comment]
@philbarker @stuartasutton for better or worse, this conversation has picked up again over in the related thread, starting around here: https://github.com/CredentialEngine/vocabularies/issues/466#issuecomment-367096530

We should probably settle on one thread or the other.

**Comment by siuc-nate** [comment]
See #466 for details.
