### ISSUE TITLE
rdfs:rangeIncludes & rdfs:domainIncludes should be schema:rangeIncludes & schema:domainIncludes

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#500]
Somewhere along the line, the encodings have switched rdfs:rangeIncludes & rdfs:domainIncludes for schema:rangeIncludes & schema:domainIncludes. No such properties in rdfs.

**Comment by siuc-nate** [comment]
I found where this was still happening - the system had been fixed going forward, but existing history records still had the rdfs versions of those "includes" properties.

I have updated the database. This problem should now be fixed.
