### ISSUE TITLE
Should the description for AlternateName should be updated to include reference to Organizatioins

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#502]
AlternateName is defined for credentials and organizations, yet the description is specific to credentials.

![image](https://user-images.githubusercontent.com/26332112/34077060-8e807410-e2be-11e7-9ddc-01efa6384d33.png)

**Comment by stuartasutton** [comment]
I suggest that the definition be changed to:

>"Alias for the entity including acronyms, alpha-numeric notations, and other forms of name abbreviations in common use such as PhD, MA, and BA."

**Comment by stuartasutton** [comment]
Sorry, closed in error. My question before changing the description to include orgs is whether the original intention was not for it to be limited to credentials and the error. Of course, limiting it to just credentials at this point might break downstream systems. If the omission in the description was an error, expanding the domain would break nothing; e.g., 

>"Alias for the entity including acronyms, alpha-numeric notations, and other forms of name abbreviations in common use."

**Comment by jkitchensSIUC** [comment]
Update the definition as follows:

Alias for an entity including acronyms, alpha-numeric notations, and other forms of name abbreviations such as acronyms in common use.

There are no other changes needed. This property is already available to:
Credentialing Organizations
QA Organizations
and...all of the Credential classes.

**Comment by siuc-nate** [comment]
This change has been completed and noted in history tracking.
