### ISSUE TITLE
Fix top-level entity URIs 

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#503]
@siuc-nate, @jkitchensSIUC, @cwd-mparsons, it appears that **all** top-level entities (credentials, learning opportunities, orgs, assessments) no longer have functional URI's in their jsonld output. Instead of `@id` like this:

>`"@id": "https://credentialengineregistry.org/resources/ce-ab3e1dd1-3c65-40f8-b0a7-54c228bdd6e8"`

we have this:

>`"@id": "ce-ab3e1dd1-3c65-40f8-b0a7-54c228bdd6e8"`

For example:

```
{
  "@context": "http://credreg.net/ctdl/schema/context/json",
  "@id": "ce-ab3e1dd1-3c65-40f8-b0a7-54c228bdd6e8",
  "@type": "ceterms:AssessmentProfile"
  ...
```
The result when translated into RDF turtle is this:

>`<file:///base/data/home/apps/s%7Erdf-translator/1.380697414950152317/ce-ab3e1dd1-3c65-40f8-b0a7-54c228bdd6e8> a ceterms:AssessmentProfile ;`

It doesn't matter which record you pick in the editor, they all appear to be broken!

**Comment by stuartasutton** [comment]
Apparently, it is not **all** top-level entities that have bad URIs...just a lot.

**Comment by cwd-mparsons** [comment]
@stuartasutton I actually noticed this on the weekend. A configuration variable holds the proper URL to be used with a CTID to form the @id. This variable had been renamed and did not have a value. 
I will republish the records. I am currently having an issue with publishing where the keys don't match. I have been trying to track this latter issue - first noticed on 17-12-16

**Comment by siuc-nate** [comment]
Per @cwd-mparsons  this was fixed.
