### ISSUE TITLE
Thing vs. string validation error

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#504]
Below is a snippet of json from the certification at https://credentialengine.org/publisher/credential/129. The snippet is below first in json followed by the same snippet after translation to RDF turtle. The issue is with the ` "ceterms:framework` property which apparently passed validation in the CER with a literal value even though it is declared otherwise in the `@context`:

```
"ceterms:framework": {
      "@type": "@id"
    },
```
### Compare (json)
```
"ceterms:credentialStatusType": {
    "@type": "ceterms:CredentialAlignmentObject",
    "ceterms:framework": "CredentialStatus",
    "ceterms:targetNode": "credentialStat:Active",
    "ceterms:targetNodeName": "Active"
  },
```
### With (turtle):
```
ceterms:credentialStatusType [ a ceterms:CredentialAlignmentObject ;
      ceterms:framework <file:///base/data/home/apps/s%7Erdftranslator/1.380697414950152317/CredentialStatus> ;
      ceterms:targetNode credentialStat:Active ;
      ceterms:targetNodeName "Active" ] ;
```
So, this literal ("CredentialStatus") passed validation (how?) even though it was declared as a resource (`@id`) in the `@context`. The error is not apparent until the translator tries to treat it as a URL and gets garbage in rdf turtle.

**Comment by siuc-nate** [comment]
To fix this, we need to:
- Update the publishing mechanism to output the name of the framework in the `ceterms:frameworkName` property instead of the `ceterms:framework` property
- Republish all of the records

**Comment by siuc-nate** [comment]
@cwd-mparsons we will need to coordinate on this since it will impact:
- The JSON validation schema
- The publisher
- The finder
- Probably documentation

**Comment by stuartasutton** [comment]
@siuc-nate & @cwd-mparsons, I think that this problem was entered by me when I discovered what later became #508.  I'm going to close it for now since it's reference will show up there.
