### ISSUE TITLE
Review LearningOpportunity definition for inclusiveness and other issues

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#507]
The [ceterms:LearningOpportunityProfile](http://purl.org/ctdl/terms/LearningOpportunityProfile) definition should be reviewed because: (1) it is self-referential (should have been caught in definitions review); and (2) it's comment leans toward formal education while the intention was broader. Definition and comment currently read:

>**Definition:** Entity describing a learning opportunity.
**Comment:** Examples of learning opportunities include education and training programs and classes, courses of study, apprenticeship or work experience programs, or other structured experiences intended to serve as educational or training events.

Note that the [ceterms:LearningOpportunity](http://purl.org/ctdl/terms/LearningOpportunity) comes closer to the original intention for [ceterms:LearningOpportunityProfile](http://purl.org/ctdl/terms/LearningOpportunityProfile):

>**Definition:** Structured and unstructured learning and development opportunities based in direct experience, formal and informal study, observation, and involvement in discourse and practice.
**Comment:** Examples of learning opportunities include education and training programs and classes, courses of study, apprenticeship or work experience programs, or other structured experiences intended to serve as educational or training events.

**Comment by stuartasutton** [comment]
## Change Proposal for `ceterms:LearningOpportunityProfile`

### Delete

> **Definition:** Entity describing a learning opportunity.
**Comment:**  Educational opportunities include required and optional programs, courses of study, and other structured experiences intended to serve as educational or training events.

### Add

> **Definition:** Entity describing an educational or training opportunity
**Comment:** Opportunities include formal and informal educational training programs and classes, apprenticeship or work experience programs, or other structured or unstructured experiences that serve as educational or training activities.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
