### ISSUE TITLE
Change the range of ceterms:weight and ceasn:weight to xsd:string

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#509]
There is more value in being able to express more than the numeric portion of weight in the value itself than there is in enabling computations on the value, so, per @stuartasutton , we should change the range of weight in both CTDL and CTDLASN to string as opposed to float.

**Comment by stuartasutton** [comment]
Currently, [ceterms:weight](http://purl.org/ctdl/terms/weight) and [ceasn:weight](http://purl.org/ctdlasn/terms/weight) have the exact same definition and comment: 

> **Definition:** Measurement of the weight, degree, percent, or strength of a recommendation, requirement, or comparison.
**Comment:** Best practice is to assigned a decimal value weight between 0 and 1 that indicates the strength of the assertion, with 0 being weakest and 1 being strongest.
**Range Includes:** xsd:float

Change comment to:

> **Definition:** Measurement of the weight, degree, percent, or strength of a recommendation, requirement, or comparison; e.g., e.g., "15%", ".5", "Strong".
**Range Includes:** xsd:string

Delete comment.

**Comment by siuc-nate** [comment]
@cwd-mparsons This will impact:
- JSON schema
- Publisher
- Finder

**Comment by stuartasutton** [comment]
No, I see no need for a new property.

**Comment by siuc-nate** [comment]
Per our 4-10-2018 call:
- We changed our minds on this and will keep the range as xsd:float.
