### ISSUE TITLE
Provide usage note for targetNode limiting use to individual entities

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#510]
We need to add a usage note to [ceterms:targetNode](http://purl.org/ctdl/terms/targetNode) that constrains the value to a single URI-identified node describing, for example, a **single** competency or a **single** concept etc. It should not be used to reference documents (e.g., a pdf) that contain the single node of interest as well as all other nodes in the framework. 

For example, a `CredentialAlignmentObject` instance describing the competency "Teamwork and workplace behavior to solve problems" should not have a value that points to a document in which this competency is embedded, such as http://www.msscusa.org/wp-content/uploads/2015/11/CLT-Key-Activities.pdf. 

An example of proper use of [ceterms:targetNode](http://purl.org/ctdl/terms/targetNode) would be the following competency with a `targetNode` value of http://www.corestandards.org/ELA-Literacy/RST/11-12/3/ 

>Follow precisely a complex multistep procedure when carrying out experiments, taking measurements, or performing technical tasks; analyze the specific results based on explanations in the text. 

The targetNode contains the competency of interest and no others. If there is no such entity available, the [ceterms:targetNode](http://purl.org/ctdl/terms/targetNode) property should not be used.

### Proposed Usage Note

> The target node should reference an entity that returns the exact competency or concept and no other competency or concept.  References to data or a document that returns all of the competencies or concepts in the framework to which the target belongs should use the [ceterms:framework](http://purl.org/ctdl/terms/framework) property.

**Comment by stuartasutton** [comment]
Proposal to add a comment to [ceterms:targetNode](http://purl.org/ctdl/terms/targetNode) to clarify that a target node returns the value of a single concept or competency from a framework.

### ADD

>**Short Hand URI:** [ceterms:targetNode](http://purl.org/ctdl/terms/targetNode)
**Comment:** The target node returned must be the exact competency or concept being described and no other competency or concept.  References to data or a document that returns all of the competencies or concepts in the framework to which the target node belongs should use the [ceterms:framework](http://purl.org/ctdl/terms/framework) property.

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
