### ISSUE TITLE
Enable condition profile to point to target occupation

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#512]
From @jkitchensSIUC:
Use Cases for Third-Party Recomendations or Requirements for 

Advanced standing to earn a credential
Preparation to earn a credential
Advanced standing for (Learning Opp) course or progam equivalence (don't have to take the course)
Advanced standing for (Assessment) assessment equivalence (don't have to take the assessment)
Prep 

The school (e.g., Vincennes accepts the third party recommentations and indicates what they accept as advanced standing or prep for based on X recommendations:

1. Military Occupation System Ratings
2. Other credentials.
3. Other assessments

The above use case for Vincennes is not necessarily dependent on a third party recommendation or requirement, Vincennes could determine this without a 3rd party.

Example 1: X program (e.g. learning opp or assessment) or credential, accepts x occupations (military or civilian), and/or X credentials, and/or assessments as advanced standing.  We did this on our own or we did this at the recommendation of X organizations.

See https://www.cool.navy.mil/usn/ 

http://purl.org/ctdl/terms/advancedStandingFrom

The user needs to be able to find all credentials, learning opps or assessments that my military occupations (MOS/RATING) is advanced standing for.  A MOS rating is a title and a code specific to branches.

Simple - the advance standing is referenced broadly to a credential, learning opp profile or assessment profile, not every single course 

Here's an example in the Publisher  https://credentialengine.org/publisher/detail/credential/1417

**Comment by siuc-nate** [comment]
Could this be as simple as adding [occupationType](http://credreg.net/ctdl/terms/occupationType) to ConditionProfile? Then you could do:

```
Credential -> advancedStandingFrom -> ConditionProfile (contains "3 credit hours") -> occupationType -> [URI for military E5]
```

**Comment by jkitchensSIUC** [comment]
I documented these use cases for the upcoming meeting with Indiana and SOLID.

1. An organization can, or will, accept, work experience (e.g., military occupations/ratings or could be other occupations), and/or other credentials, and/or other learning opportunities, and/or other assessments as 

•	advanced standing for http://credreg.net/ctdl/terms/financialAssistance#isAdvancedStandingFor) 
•	or as preparation for (http://credreg.net/ctdl/terms/financialAssistance#isPreparationFor) 
•	or as recommended for (http://credreg.net/ctdl/terms/financialAssistance#isRecommendedFor) 
•	or as required for (http://credreg.net/ctdl/terms/financialAssistance#isRequiredFor) 

A Credential, Learning Opportunity or Assessment.  For the Vincennes examples, they’re the org accepting the work experience (i.e. Military Ratings).  Are they accepting it as advanced standing? If so, entries belong under Connections.  However, we need to add properties to enable the references to work experience, e.g., military occupation title, Military occupation code, in addition to the connections already enabled.

This is documented here https://github.com/CredentialEngine/vocabularies/issues/512.  We’ll work on it now and set a date for an update. 

2.  A third-party (e.g., ACE or Indiana Board of Higher Education) makes recommendations for or requirements for credentials, learning opportunities or assessments to accept work experience (e.g., military occupations/ratings or could be other occupations), and/or other credentials, and/or other learning opportunities, and/or other assessments as 

•	advanced standing for http://credreg.net/ctdl/terms/financialAssistance#isAdvancedStandingFor) 
•	or as preparation for (http://credreg.net/ctdl/terms/financialAssistance#isPreparationFor) 
•	or as recommended for (http://credreg.net/ctdl/terms/financialAssistance#isRecommendedFor) 
•	or as required for (http://credreg.net/ctdl/terms/financialAssistance#isRequiredFor) 

If the third party issues credentials that may have learning opps and/or assessments they offer for advanced standing for, prep for, recommended for, or required for, they can self-identify these connections in the registry.

If the third party only serves the role as a recommender or requirer, the only role for this is a Quality Assurance Org, at this time, they would publish their information as a QA org and describe their services. 

3.  We’re also looking at third-party mapping that will provide the means to relate the assertions by the first and third parties.   See the details and modeling here  https://github.com/CredentialEngine/vocabularies/issues/498 

Thanks so much, Jeanne

**Comment by jkitchensSIUC** [comment]
Clarification – I’m saying that if Vincennes accepts military occupations/ratings as advanced standing, the entry should be via the connections (in the publisher) by the credentialing organization but we need to add a property or two to handle this.  If attribution is necessary, we need to be able to support, or example..

“Vincennes (as the credentialing org) accepts x military occupations/ratings as advanced standing for X credential as recommended by X and X and X.”

“Vincennes (as the credentialing org) accepts x military occupations/ratings as advanced standing for X learning opportunity as recommended by X and X and X.”

“Vincennes (as the credentialing org) accepts x military occupations/ratings as advanced standing for X assessment as recommended by X and X and X.”

If third-parties like ACE or Indiana need to publish information to the registry to describe their recommendations, the only context we have to do that is via QA Orgs.   Indiana Higher Ed is definitely a QA org.  

I’m not sure if Ace is a QA org… They do leadership and advocacy.  Informally, they could be QA but they don’t seem to endorse or recommend any specific programs.  They appear to provide recommendations for advanced standing for military…and other students as well.  If the Credential Engine needs to expand to another type of organization (e.g., Transfer Recommendation Orgs), we would need to know and add it as a GitHub issue and it would go on the list of potential new classes with new properties for the purpose of writing descriptions about their recommendations or requirements for what work or life experience, and/or credentials, learning opps or assessments should be accepted for advanced standing, prep for etc..

The third use case is modeling how the third party e.g., Ace or Indiana and the 1st part e.g., Vincennes can make direct references to each other.

**Comment by jkitchensSIUC** [comment]
Use cases:

•	“Vincennes (as the credentialing org) accepts x military occupations/ratings as advanced standing for X credential as recommended by X and X and X.  The military occupation, and or X, and or X, may equate up to X credit hour value for x credit hour type or x credit unit value for x credit unit type.”

•	“Vincennes (as the credentialing org) accepts x military occupations/ratings as advanced standing for X learning opportunity as recommended by X and X and X.  The military occupation, and or X, and or X, may equate up to X credit hour value for x credit hour type or x credit unit value for x credit unit type.”

•	“Vincennes (as the credentialing org) accepts x military occupations/ratings as advanced standing for X assessment as recommended by X and X and X.  The military occupation, and or X, and or X, may equate up to X credit hour value for x credit hour type or x credit unit value for x credit unit type.”

**Comment by stuartasutton** [comment]
I'll be looking at this more this afternoon, I don't think a full solution is as simple as adding an [`occupationType`](http://credreg.net/ctdl/terms/occupationType) to ConditionProfile because when we say "x military occupations/ratings", it is the confluence of two data points: 

1. designation of occupation (called different things in different branches); and
2. rank (pay grade) (e.g., E6).

In a mapping the designation of occupation **could** have different credits allowed for the same occupation at different ranks.

Still digging...

See "occupation Codes" by branch:

>http://www.military1.com/navy-enlistment/318808-navy-ratings/
http://www.military1.com/air-force-enlistment/318824-air-force-specialty-codes/
http://www.military1.com/all/article/318809-marine-corps-mos-codes/
https://www.military1.com/army-enlistment/318806-army-mos-codes/

**Comment by siuc-nate** [comment]
I think you could cover those data points via a concept scheme (or set of schemes) that reflects them. Since the property already exists and is intended to point at concept schemes (or frameworks, depending on who you ask) of career designations like SOC and ESCO, it seems like a good fit.

Regarding the codes you listed, I think we don't want to confuse MOS codes (the job you do) with ranks or with pay grades. Having said that, you could probably point to all three of those using the occupationType property. 

For example:

```
{
  "@type": "ceterms:Credential",
  "ceterms:advancedStandingFrom": [
    {
      "@type": "ceterms:ConditionProfile",
      "cterms:creditHourValue": 3,
      "ceterms:occupationType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:frameworkNodeName": "MOS Codes",
          "ceterms:framework": "http://....",
          "ceterms:targetNodeName": "Infantryman",
          "ceterms:codedNotation": "11B"
          "ceterms:targetNode": "http://...."
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:frameworkNodeName": "US Army Rank",
          "ceterms:framework": "http://....",
          "ceterms:targetNodeName": "Private First Class",
          "ceterms:codedNotation": "PFC"
          "ceterms:targetNode": "http://...."
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:frameworkNodeName": "US Uniformed Services Pay Grades",
          "ceterms:framework": "http://....",
          "ceterms:targetNodeName": "E-3",
          "ceterms:codedNotation": "E-3"
          "ceterms:targetNode": "http://...."
        },
      ]
    }
  ]
}

```

**Comment by stuartasutton** [comment]
OK, but all I was intending to say is that it's not a single node in an occupation vocabulary, but a confluence...here you have 3.

**Comment by siuc-nate** [comment]
Correct, but perhaps I misread your previous comment as meaning that we would need more _properties_ as opposed to more _concepts/schemes_.

**Comment by stuartasutton** [comment]
Nate, I may be missing something, but the array of 3 values of the occupationType property in your example are related (Infantryman, Private First Class, E-3).  What if I have an occupationType array made of 2 or more sets of such related concepts?

**Comment by siuc-nate** [comment]
The simplest way to handle that would be to add another condition profile - you would need to do so anyway if, for example, the number of credit hours was different between two sets of concepts.

For example (leaving out the URI properties in the alignment objects for brevity):
```
{
  "@type": "ceterms:Credential",
  "ceterms:ownedBy": [
    "http://uri-for-vincennes-university"
  ]
  "ceterms:advancedStandingFrom": [
    {
      "@type": "ceterms:ConditionProfile",
      "cterms:creditHourValue": 3,
      "ceterms:occupationType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:frameworkNodeName": "MOS Codes",
          "ceterms:targetNodeName": "Infantryman",
          "ceterms:codedNotation": "11B"
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:frameworkNodeName": "US Army Rank",
          "ceterms:targetNodeName": "Private First Class",
          "ceterms:codedNotation": "PFC"
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:frameworkNodeName": "US Uniformed Services Pay Grades",
          "ceterms:targetNodeName": "E-3",
          "ceterms:codedNotation": "E-3"
        },
      ],
      "ceterms:assertedBy": [
        "http://uri-for-asserting-organization"
      ]
    },
    {
      "@type": "ceterms:ConditionProfile",
      "cterms:creditHourValue": 4,
      "ceterms:occupationType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:frameworkNodeName": "MOS Codes",
          "ceterms:targetNodeName": "Combat Engineer",
          "ceterms:codedNotation": "21B"
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:frameworkNodeName": "US Army Rank",
          "ceterms:targetNodeName": "Corporal",
          "ceterms:codedNotation": "CPL"
        },
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:frameworkNodeName": "US Uniformed Services Pay Grades",
          "ceterms:targetNodeName": "E-4",
          "ceterms:codedNotation": "E-4"
        },
      ],
      "ceterms:assertedBy": [
        "http://uri-for-asserting-organization"
      ]
    }
  ]
}
```

**Comment by stuartasutton** [comment]
Thank you!

**Comment by siuc-nate** [comment]
I'm not quite sure what I did that was worthy of being thanked, but, you're welcome, I suppose.

**Comment by siuc-nate** [comment]
To revise an earlier example:
```
{
  "@type": "ceterms:Credential",
  "ceterms:ownedBy": [
    "http://uri-for-vincennes-university"
  ]
  "ceterms:advancedStandingFrom": [
    {
      "@type": "ceterms:ConditionProfile",
      "cterms:creditHourValue": 3,
      "ceterms:occupationType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:frameworkNodeName": "US Uniformed Services Roles",
          "ceterms:targetNodeName": "E-3 US Army PFC Infantryman",
          "ceterms:codedNotation": "E-3/ARMY/PFC/11B",
          "ceterms:targetNode": "http://uniformedservicesvocabulary.source/E-3/ARMY/PFC/11B"
        }
      ],
      "ceterms:assertedBy": [
        "http://uri-for-asserting-organization"
      ]
    },
    {
      "@type": "ceterms:ConditionProfile",
      "cterms:creditHourValue": 4,
      "ceterms:occupationType": [
        {
          "@type": "ceterms:CredentialAlignmentObject",
          "ceterms:frameworkNodeName": "US Uniformed Services Roles",
          "ceterms:targetNodeName": "E-4 US Army CPL Combat Engineer",
          "ceterms:codedNotation": "E-4/ARMY/CPL/21B",
          "ceterms:targetNode": "http://uniformedservicesvocabulary.source/E-4/ARMY/CPL/21B"
        }
      ],
      "ceterms:assertedBy": [
        "http://uri-for-asserting-organization"
      ]
    }
  ]
}
```
I could see an encoding scheme with semantically-interpretable URIs with the format of:
[Pay Grade]/[Branch]/[Rank]/[Job]
Since pay grades are, from what I can tell, universal across the uniformed services (and used as a means of determining seniority between members of different branches), they come first. Then the branch, as it seems like the next logical grouping, then rank, then role.  I suppose it isn't really important since this is just an example and those URIs could just as easily contain GUIDs instead, **but the point is** that I do believe it's possible to encode that combination of 4 factors into a single (if quite large - but then so is NAICS, SOC, etc.) concept scheme.

@stuartasutton would something like that solve the problem?

**Comment by stuartasutton** [comment]
Nate, the AlignmentMap is designed to do this sort of mapping. Such mapping data is not something that you'd embed in the credential description itself. We can think of these maps as overlays on the credentials. Machine actionable schemas for MOS codes, ranks, service pay grades (or a faceted aggregation thereof) is not something that 'we' should do. But a mapping statement could include such data as either literals or as things (should the armed forces get around to formally defining them as concept schemes).

**Comment by siuc-nate** [comment]
Creation of these alignment maps requires a tool. CASS has a tool that seems to fit the bill - we need to investigate whether this can be adapted for our needs.
