### ISSUE TITLE
Consider using @language instead of language maps

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#514]
In discussing the use of the inLanguage property with the team internally today, we reviewed the various ways to indicate the language of an entity and the language of the JSON-LD document that describes it. 

Since we haven't yet implemented language maps, and since it seems like a very rare use case that a particular record would have more than one language, I think it might be wise to use the `@language` property of JSON-LD to indicate the language for a JSON-LD document and simply require a publisher to publish a document for each language if and when such a use case arises.

The alternative, implementing language maps, increases the complexity of entering and processing records. Most records will likely be in one language, and I believe the burden of asking _every_ publisher to publish and consume with language maps is much heavier than asking only the publishers who are interested in publishing in multiple languages to publish multiple records (one for each language) for a given resource. 

We should discuss this as a team.

**Comment by siuc-nate** [comment]
Per our 3/9/2018 call:
We should move forward with leaving language maps out of our implementation and instead using `@language` in the `@context`.  To publish metadata in multiple languages, use multiple documents (each with their own CTID).

**Comment by siuc-nate** [comment]
For reference, here are the relevant uses of language in different contexts:
![image](https://user-images.githubusercontent.com/21346519/37224851-4518f2b2-239a-11e8-9bd5-10d8c025e3f0.png)

**Comment by rrobson** [comment]
This originally posted issue seems to imply that it is rare to have more than one language in a record. That is counter to experience in descriptive metadata, where it is common to have the same object described in multiple languages and is sometimes _required_, as is the case in Canada, Switzerland, Belgium, etc.

Note that some properties (IDs, for example) take numeric and other values that rarely are multi-lingual, whereas others (titles, for example) may be required to be multi-lingual.  Thus it would seem to be a requirement that language be assignable on a property-by-property basis and that certain elements admit higher multiplicities than 1 with different languages for each instance.

The illustration Nate posted prior to this does handle this as required. I am simply pointing out that doing so is a requirement.

**Comment by siuc-nate** [comment]
@rrobson thanks, it's nice to get some additional perspective. We've been trying to determine whether we should implement language maps across our systems for publishing/consuming/validating data in the registry so that languages can be handled on a per-property basis, or whether they should be handled on a per-document basis. 

We will handle the use case of having multiple languages for the same metadata regardless, it's just a matter of whether it involves complex objects for every language-dependent string property, or multiple documents (one for each language for a given "thing").  Since this data will be reliant on the customers to be able to publish and consume, we want to make it as easy as possible.  

Language maps are powerful, but not very intuitive (you expect the value for a string property to be a string, not an object) and would be overkill for all use cases that _don't_ involve needing more than one language per metadata record.

It's a question of whether it's easier for developers to publish/consume:
```
{
  "@context": {
    "@language": "en"
  },
  "ceterms:name": "Name in English",
  "ceterms:description": "Description in English"
  "ceterms:keyword": [
    "Keyword One",
    "Keyword Two",
    "Keyword Three"
  ]
},
{
  "@context": {
    "@language": "ru"
  },
  "ceterms:name": "имя на русском",
  "ceterms:description": "описание на русском",
  "ceterms:keyword": [
    "ключевое слово one",
    "ключевое слово два",
    "ключевое слово три"
  ]
}
```
vs
```
{
  "ceterms:name": {
    "en": "Name in English",
    "ru": "описание на русском"
  },
  "ceterms:description": {
    "en": "Description in English",
    "ru": "описание на русском"
  },
  "ceterms:keyword": [
    { 
      "en": "Keyword One",
      "ru": "ключевое слово one"
    },
    {
      "en": "Keyword Two",
      "ru": "ключевое слово два"
    },
    {
      "en": "Keyword Three",
      "ru": "ключевое слово три"
    }
  ]
}
```
I think it's way more intuitive to pick the document with the `@language` you want and go from there, treating strings as strings, than it is to pick through every single (language) string, handling it as an object (and other details, like dealing with a system that expects "en-US" as keys, while the data only contains "en" as keys).

Additionally, since I think a very large number of our publishers/consumers will only be interested in one language, the use of the language map structure just adds unnecessary complexity to publishing, consuming, and documenting data that only contains one language anyway.

I've written code to serialize and deserialize our own schema encodings, which use language maps, and it's a real slog to have that layer of indirection/complexity every single time I want to touch almost any string, especially during deserialization - and this is with the benefit of _knowing_ exactly what data will be present when I go looking for it. It would be much harder if I had to hope (i.e. null-check) that the language maps contained my language (or something close to it - i.e., check for "en" and "en-US" and "en-GB", any of which I _could_ use, then keep track of it somehow) in them somewhere as a consumer.  Having the `@language` property up front in the context tells you that without any further investigation.

Additionally, figuring out how to handle multiple top-level documents will be useful for solving issue #521, so I think it's worth doing.

I could be wrong though - this is just my two cents.

**Comment by siuc-nate** [comment]
This relates to #508 in the sense that it requires having a Registry payload structure that: 
- contains a `@graph`:
- allows multiple top-level objects, so long as their CTIDs match

![image](https://user-images.githubusercontent.com/21346519/37361587-4766dbae-26c1-11e8-989e-6abb18674b15.png)

This image shows different JSON-LD descriptions in their various languages describing real-world credentials that have their own languages. The language of the description is independent of the language of the thing being described.

The JSON-LD for the above would look something like this:
```
{
  "envelopeID": "ABC",
  "ceterms:ctid": "123",
  "decoded_payload": {
    "@context": { },
    "@graph": [
      {
        "@context": {
          "@language": "en"
        },
        "ceterms:inLanguage": "en",
        "ceterms:ctid": "123"
      },
      {
        "@context": {
          "@language": "fr"
        },
        "ceterms:inLanguage": "en",
        "ceterms:ctid": "123"
      },
      {
        "@context": {
          "@language": "de"
        },
        "ceterms:inLanguage": "en",
        "ceterms:ctid": "123"
      }
    ]
  }
}
```
```
{
  "envelopeID": "DEF",
  "ceterms:ctid": "456",
  "decoded_payload": {
    "@context": { },
    "@graph": [
      {
        "@context": {
          "@language": "de"
        },
        "ceterms:inLanguage": "fr",
        "ceterms:ctid": "456"
      },
      {
        "@context": {
          "@language": "es"
        },
        "ceterms:inLanguage": "fr",
        "ceterms:ctid": "456"
      }
    ]
  }
}
```

**Comment by siuc-nate** [comment]
Per #521 we will use language maps as originally planned.
