### ISSUE TITLE
Determine the best structure for hierarchical data in the Registry

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#522]
Related to #521 

Competency Frameworks and Competencies, and soon Concept Schemes and Concepts, are to be stored in the Registry.  The question is, what is the best way to store them, and what implications does that have for the rest of the system?

The examples below reference competency frameworks/competencies, but the same would apply to concept schemes/concepts.

Some options I can think of:

Handle them all in one `@graph`
---
Pending the outcome of #521 in regards to the structure of documents in the Registry, it may be feasible to store the competency framework and its competencies in a single graph.
![image](https://user-images.githubusercontent.com/21346519/37362984-c70ccfdc-26c4-11e8-91a8-34ca4fe69483.png)
Pros:
- Easier to publish and consume data
- Faster to publish and consume data, since it is all present in the `@graph` and does not need to be looked up or traversed (useful for searching and retrieval of the entire framework)
- Matches up to the CE notion of "approval" at the framework level

Cons:
- Requires special handling(?) to retrieve individual competencies, since they do not have their own envelopes (maybe this is unneeded)
- Does not permit history tracking for individual competencies; history can only be tracked at the framework level (maybe this is good enough?)
- Violates the rule of 1:1 correlation between envelope ID and CTID (though maybe using the framework's CTID is good enough)
- Violates the validation referenced in https://github.com/CredentialEngine/vocabularies/issues/514#issuecomment-372769710, specifically "allows multiple top-level objects, so long as their CTIDs match" (their CTIDs would not match)

Handle them exactly the same way all other top-level things are handled
---
This is technically the current plan, though it may not make sense given the other changes.
![image](https://user-images.githubusercontent.com/21346519/37363203-4fd5b716-26c5-11e8-9dec-8c1643cb7e80.png)
Pros:
- Works with existing systems, URIs/URLs, validation, search, etc.
- Keeps 1:1 correlation between envelope ID and CTID
- Allows tracking history for each competency

Cons:
- Greatly complicates (and slows down) publishing and consuming when operations concern the whole framework, since the data would all need to be traversed and retrieved, updated, etc.
- Is probably overkill for most use cases

Tagging @stuartasutton @science @lomilar to get their thoughts.

**Comment by brandonopened** [comment]
Hi, I don't see an instance where a CASE framework would contain more than one language. the CfDoc item is language; however each CfItem does have a language field as well and that can be different. 

If I'm reading what you're saying correctly, should CASE enforce one language for consistency in future iterations?

**Comment by Lomilar** [comment]
@brandonopened Frameworks in east Canada (and most educational material) tend to need to exist (by law? Not sure) in English and French, for instance.

As for the representation of frameworks in CE: Most external systems won't give much of a hoot about the envelopes except as a way of validating that the data is accurate or digging into the history of the data. They will care that `@id`s resolve, that links aren't broken, and that the data is as friendly as possible.

According to (somewhat aged) conversations with @stuartasutton and my understanding of the two object model, changing a competency necessarily changes the framework, so publishing them all at once is the more prudent choice for the way this data is represented. A framework of competencies in CTDL+ASN is considered to be a single interconnected @graph that may have some external links. The `@id`s are there to allow objects elsewhere to link deeply into the framework, to a particular competency.

So, choice 1 makes sense from that perspective. It will certainly make finding an envelope for a competency more difficult, and it also has the cons you mentioned.

**Comment by siuc-nate** [comment]
Regarding choice 1 above:
In effect, competencies would not have envelopes. 

The way the above would work (pending the results of #521 anyway) is that the various language versions of each competency would all be stored in the same envelope.  I don't have time at the moment to create an example, but you could imagine that, in the first picture in the post above, "Competency 1" is english and "Competency 2" is the french version of the same competency as Competency 1. Competency 3 (and presumably 4) might follow a similar pattern.  In those cases, 1 and 2 would have the same CTID, and 3 and 4 would have the same CTID. 

Alternatively, Competency 1 might have language maps internally for both english and french, as would Competency 2, and so on (in which case no 2 competency documents would share a CTID).

All of the details haven't been worked out 100% yet; unfortunately this is interconnected with issues discussed in #521. We want to have one cohesive approach to solving the problems of `@language`, `@graph`, blank nodes, etc., that can be used with CTDL, CTDL-ASN, and any concept scheme related information.

**Comment by stuartasutton** [comment]
@Lomilar, the major difference between the 2-entity and 3-entity competency framework model is in how the models handle the relationship glue. In both models frameworks and competencies are first class citizens of their respective models and of the Web in the 2-entity (RDF) model. This has **absolutely nothing** to do with how change is handled. How change is handled is a function of policy (and perhaps logic, depending on how you look at the entities).   I've asserted that a change in a competency node sufficient to trigger a new URI is a change on the framework. That's not a 2/3 entity issue. My perception of change is as follow. While a competency framework is an entity unto itself, it is nevertheless the description of its member competencies as embodied. Just like we might describe a book with 7 chapters as separate things with 8 URI, I can't logically swap out a chapter of that book and assert that the book entity itself is unchanged even though I may not have touched a single character in the book entity description.

**Comment by Lomilar** [comment]
Sorry, yes, I conflated 2-entity frameworks with ASN (which has that policy)

**Comment by siuc-nate** [comment]
This has been determined - we will include the data for a framework and competencies (and concept schemes/concepts) in the same graph.

As for the language problem in the last few posts, this can be handled through language maps (preferred) or, if the publisher wants, by publishing the documents separately with separate CTIDs.
