### ISSUE TITLE
Determine if MOCs, or some MOCs, are Credentials

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#524]
Layout what would need to be concretely defined to layout a pathway for determining if MOCs, or some MOCs are or aren't credentials.

**Comment by ottonomy** [comment]
Does MOC mean "Maintenance of Credential"?

**Comment by siuc-nate** [comment]
I'm pretty sure she's referring to these: https://www.onetonline.org/crosswalk/MOC/
Also known as MOS codes
https://www.military1.com/all/article/318929-what-are-mos-codes/

**Comment by stuartasutton** [comment]
Of course!

**Comment by stuartasutton** [comment]
Of course! @ottonomy, we have a discussions with the folks at COOL going regarding whether MOC code aligned with competencies actually defines a credential...as opposed to merely representing a kind of occupation code. 

That's likely a lousy explanation :-(

**Comment by stuartasutton** [comment]
It's absolutely clear (see issue #533) that CTDL needs a URI-identified resource to capture those aspects of a military MOS/MOC ("Military Occupation Speciality" or "Military Occupation Code") needed to map them using editors and mapping tools to learning opportunities (courses), other credentials, and, potentially, to other forms of relevant experience. 

While discussions of whether these military occupation system ratings might be considered credentials of sorts have been around for a bit, the better path for CTDL is to follow ONet's lead and consider them occupations (search ONet's [occupation/MOC crosswalk](https://www.onetonline.org/crosswalk/MOC/)). Also, a number of websites for these ratings refer to them casually as 'occupations'. 

Currently, schema.org has an Occupation entity in pending and perhaps scheduled for it's next release (see https://github.com/schemaorg/schemaorg/issues/1698). While it has some definitions carried over from schema.org/JobPosting that are [circular ](https://en.wikipedia.org/wiki/Circular_definition) and thus ill-defined, that's a problem that we can handle in the CTDL schema.

**Comment by siuc-nate** [comment]
I thought we had discussed creating a credential associated with each MOS code and using that as the "thing" to connect to.  Then there is no need for any change to CTDL and it would be compatible with future applications that could treat military credentials (and their associated job codes) the same way they treat any other credential and its associated job code (i.e. nursing).

**Comment by stuartasutton** [comment]
Yes, I understand.  An alternative is use of Occupation.

**Comment by siuc-nate** [comment]
Per out 7/17/2018 conversation:
We have two solutions:
1. Classify the MOS/Rating/codes etc. as Credentials
2. Classify the MOS/Rating/codes etc. as https://pending.schema.org/Occupation

Ultimately all we **_really_** need is to have URIs assigned (preferably by the military) to each MOS/Rating/code/etc. so that they can be pointed to.  Their actual classification is far less relevant, but we have no good political solution.

**Comment by siuc-nate** [comment]
Per our 4-30-2019 conversation:
We will need to reassess and revisit this.
