### ISSUE TITLE
Revise definition of ceasn:derivedFrom

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#528]
The [`ceasn:derivedFrom`](http://purl.org/ctdlasn/terms/derivedFrom) property definition is unclear in scope (covers both frameworks and competencies) and is circular.

## Delete
**Property:** ceasn:derivedFrom
**Definition:** The URI of a competency from which this competency has been derived.
**Comment:** The derivedFrom property is used by 3rd parties only in derived competencies.

## Add
**Property:** ceasn:derivedFrom
**Definition:** A third party version of the entity being reference that has been modified in meaning through editing, extension or refinement.

**NOTE:** Update the [Best Practice](https://docs.google.com/spreadsheets/d/1vslhEc6csE3LtDg0rzmdYDi0B5AwUVKxBUAiEVy9j7M/edit#gid=1005400000) spreadsheet accordingly (row 14)

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL-ASN and noted in the history tracking.
