### ISSUE TITLE
Clarify documentation of ceasn:listID

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#529]
## Delete
**Property:** ceasn:listID
**Definition:** An alphanumeric string indicating this competency's position in a list of competencies at the same level in some arbitrary hierarchy.
**Comment:** Competencies with lower alphanumeric values for this property come before competencies with higher values.
**Usage Note:** Values may be repeated within a competency framework if the values apply to competencies at different levels of some arbitrary hierarchy. If two or more competencies at the same level of some arbitrary hierarchy have the same listID value, their order (relative to each other) is unspecified.

## Add
**Property:** ceasn:listID
**Definition:** An alphanumeric string found in the source framework indicating the relative position of a competency in an ordered list of competencies such as "A", "B", or "a", "b", or "I", "II", or "1", "2".
**Usage Note:** Punctuation accompanying alphanumeric strings should not be included. 

**NOTE:** Update the [Best Practice] https://docs.google.com/spreadsheets/d/1vslhEc6csE3LtDg0rzmdYDi0B5AwUVKxBUAiEVy9j7M/edit#gid=1005400000) spreadsheet accordingly (row 20)

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL-ASN and noted in the history tracking.
