### ISSUE TITLE
Determine if Additional Concepts Should be Included with ceterms:OrganizationType 

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#531]
This potential to add: quasi government and/or state compact as concepts to ceterms:OrganizationType originated from NEBHE www.nebhe.org/about-nebhe/overview/.  According to their website, NEBHE was approved by New England's six state legislatures and authorized by the U.S. Congress.

Jeanne asked Emilie to do some research and provide a proposal with potential definitions to this issue to potentially include additional concepts with http://credreg.net/ctdl/terms#OrganizationType

Proposed concepts include: quasi government and/or state compact.

**Comment by lfaulkner0328** [comment]
From staff discussion today - "Intermediary" may be a good term to consider that would encompass a range of different partners (quasi-gov or nonprofit workforce organizations, sector partnerships that do not identify as associations, regional collaboratives, national organizations with multi-site/multi-state sites). I would need to do some more research on whether intermediary is used outside of the U.S. 

Examples of how term is used by government/policymakers, think tanks, workforce thought leaders etc: 
https://blog.dol.gov/2016/09/21/new-intermediaries-will-help-scale-us-apprenticeships
https://wfguide.urban.org/strategy/workforce-intermediaries
http://www.jff.org/sites/default/files/publications/FunderCollab.pdf

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton can we show a final proposal?  Didn't this come from Scott and Emilie?  We need to show a final proposal and have them approve it.

**Comment by erafal10** [comment]
Those Organization Type's seem fine but still don't quite fit NEBHE's use case. They proposed "Coordinating Body" defined as "An organization that organizes multiple stakeholders around a common goal." It's similar to collaborative, but not a group of entities.

**Comment by siuc-nate** [comment]
Proposed addition:
>**Preferred Label:** Coordinating Body
>**Description:** An organization that organizes multiple stakeholders around a common goal.

**Comment by stuartasutton** [comment]
Consider also:

>**URI:** orgType:Consortium
>**Preferred Label:** Consortium
>**Description:** "A membership Organization of two or more individuals or organizations of any type, who collaborate with the objective of participating in a common activity or pooling their resources for achieving a common goal."

**Comment by siuc-nate** [comment]
Collaborative and Coordinating Body have been implemented in the schema management system and noted in the history tracking.

This can be closed **unless** we're also going to implement Consortium.

**Comment by stuartasutton** [comment]
Go ahead now...we can look at "Consortium" later.

**Comment by siuc-nate** [comment]
Thanks.
