### ISSUE TITLE
Adapt LEI Code for CTDL

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#532]
Following internal discussions, this proposal is to adapt [`schema:leiCode`](http://schema.org/leiCode) for CTDL.  Per @stuartasutton:

**URI:** ceterms:leiCode
**Definition:** A 20-digit, alpha-numeric code, based on the ISO 17442 standard, for identifying legal entities participating in financial transactions.
**Equivalent To:** [`schema:leiCode`](http://schema.org/leiCode)
**Domain:** ceterms:CredentialOrganization, ceterms:QACredentialOrganization

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton didn't this come from Scott or Emilie?  Who do we need to show this to so we can push this out with the June milestone?

**Comment by siuc-nate** [comment]
Stuart and I already agreed that it's ready to implement.  Do we need anyone else's approval?

**Comment by stuartasutton** [comment]
I think we can go with it.

**Comment by siuc-nate** [comment]
This has been taken care of in the schema management system and noted in the history tracking.
