### ISSUE TITLE
W3C Links on CTDL terms page are broken 

### ISSUE THREAD

**Issue by lfaulkner0328** [CredentialEngine/vocabularies#541]
When you click on "stable" or "unstable" in the CTDL terms page, it takes you to one of these two pages that seem to no longer exist:
https://www.w3.org/2003/06/sw-vocab-status/nsunstable
https://www.w3.org/2003/06/sw-vocab-status/nsstable

Just a heads up!

**Comment by siuc-nate** [comment]
@stuartasutton The prefix ends in "ns" rather than a / or a # as the others do - is this the correct namespace?

**Comment by stuartasutton** [comment]
http://www.w3.org/2003/06/sw-vocab-status/ns#

**Comment by siuc-nate** [comment]
Thanks. I have made the update.
