### ISSUE TITLE
Condition Items

### ISSUE THREAD

**Issue by lfaulkner0328** [CredentialEngine/vocabularies#542]
I was noting in the bulk upload properties, "condition item" is a property that falls under "condition profile." I don't see a matching definition in the CTDL terms for "condition item" or "item". Just curious if this was something to flag/clarify.

**Comment by siuc-nate** [comment]
The Condition Item in the bulk upload interface links to http://credreg.net/ctdl/terms/condition, which is the correct term.  I believe we called it "condition item" there to clarify its purpose as a list item that is part of a Condition Profile (just calling it "condition" may have been confusing).

**Comment by lfaulkner0328** [comment]
Got it!
