### ISSUE TITLE
Pathway Proposal

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#546]
This is a proposal to support career pathways in CTDL.

![2018-11-26 pathway trial](https://user-images.githubusercontent.com/2939046/49047214-9194db00-f18b-11e8-9230-33716bd27e6c.png)

---
**Classes**
---
> **URI:** ceterms:Agent
> **Label:** Agent
> **Description:** Organization or person that acts or has the power to act.
> **Comment:** Broad type that includes both organizations and people who play roles in the lifecycle of a resource.

> **URI:** ceterms:AssessmentComponent
> **Label:** Assessment Component
> **Description:** Resource that identifies a direct, indirect, formative, and summative evaluation or estimation of the nature, ability, or quality of a resource, performance, or outcome of an action.
> **Subclass Of** ceterms:PathwayComponent

> **URI:** ceterms:BasicComponent
> **Label:** Basic Component
> **Description:** Resource that identifies a resource not otherwise covered by the enumerated PathwayComponent subclasses.
> **Subclass Of** ceterms:PathwayComponent

> **URI:** ceterms:CocurricularComponent
> **Label:** Cocurricular Component
> **Description:** Resource that identifies an activity, program, or informal learning experience such as a civic or service activity that supplements and complements the curriculum.
> **Subclass Of** ceterms:PathwayComponent

> **URI:** ceterms:CompetencyComponent
> **Label:** Competency Component
> **Description:** Resource that identifies a measurable or observable knowledge, skill, or ability necessary to successful performance of a person in a given context.
> **Comment:** Competency is broadly defined to include assertions of academic, professional, occupational, vocational and life goals, outcomes, and standards, however labeled.
> **Subclass Of** ceterms:PathwayComponent

> **URI:** ceterms:ComponentCondition
> **Label:** Component Condition
> **Description:** Resource that describes what must be done to complete a PathwayComponent, or part thereof, as determined by the issuer of the Pathway. 
> **Comment:** A ComponentCondition references a single RuleSet defining appropriate values fulfilling the condition.

> **URI:** ceterms:CourseComponent
> **Label:** Course Component
> **Description:** Resource that identifies a structured sequence of one or more learning activities that aims to develop a prescribed set of knowledge, skill, or ability of learners.
> **Subclass Of** ceterms:PathwayComponent

> **URI:** ceterms:CredentialComponent 
> **Label:** Credential Component
> **Description:** Resource that identifies another resource that describes qualification, achievement, personal or organizational quality, or aspect of an identity typically used to indicate suitability.
> **Comment:** The ceterms:Credential class is broadly defined to encompass credentials used across domains and communities of practice. Subclasses of ceterms:Credential as defined by Credential Engine (or other communities) should be referenced.
> **Subclass Of** ceterms:PathwayComponent

> **URI:** ceterms:ExtracurricularComponent
> **Label:** Extracurricular Component
> **Description:** Resource that identifies an activity, program, or informal learning experience that may be offered or provided by a school, college, or other organization that is not connected to a curriculum.
> **Subclass Of** ceterms:PathwayComponent

> **URI:** ceterms:JobComponent
> **Label:** Job Component
> **Description:** Resource that identifies a work position, employment, or occupation.
> **Subclass Of** ceterms:PathwayComponent

> **URI:** ceterms:Pathway
> **Label:** Pathway
> **Description:** Resource composed of a structured set of PathwayComponents defining points along a route to fulfillment of a goal or objective. 

> **URI:** ceterms:PathwayComponent
> **Label:** Pathway Component
> **Description:** Resource that serves as a defined point along the route of a Pathway which describes an objective and its completion requirements through reference to one or more instances of ComponentCondition.
> **Comment:** An instance of PathwayComponent may serve as the goal or destination node of a Pathway.
> **Subclasses:** ceterms:AssessmentComponent, ceterms:BasicComponent, ceterms:CocurricularComponent, ceterms:CompetencyComponent, ceterms:CourseComponent, ceterms:CredentialComponent, ceterms:ExtracurricularComponent, ceterms:JobComponent, ceterms:WorkExperienceComponent

> **URI:** ceterms:RuleSet
> **Label:** Rule Set
> **Description:** Resource that identifies the rules or methods by which one or more PathwayComponent instances satisfy the requirements of a ComponentCondition.
> **Comment:** In the future, there will likely be multiple formally recognized RuleSets.
> **Usage Note:** Encode the rules using Description Logic.

> **URI:** ceterms:RuleSetProfile
> **Label:** Rule Set Profile
> **Description:** Resource defining the application of a RuleSet to a particular ComponentCondition. 

> **URI:** ceterms:WorkExperienceComponent
> **Label:** Work Experience Component
> **Description:** Resource describing an activity or training through which a person gains job experience.
> **Subclass Of** ceterms:PathwayComponent

---
**Properties**
---

> **URI:** ceasn:codedNotation
> **Label:** Coded Notation
> **Description:** An alphanumeric notation or ID code as defined by the promulgating body to identify this resource.
> **Comment:** This property should be used only for codes created by the promulgating body.
> **Domain:** subclasses of ceterms:PathwayComponent
> **Range:** xsd:string

> **URI:** ceterms:componentCategory
> **Label:** Component Category
> **Description:** Identifies the type of PathwayComponent subclass not explicitly covered in the current array of PathwayComponent subclasses.
> **Domain:** ceterms:BasicComponent, ceterms:CocurricularComponent, ceterms:ExtracurricularComponent
> **Range:** rdf:langString

> **URI:** ceterms:credentialType
> **Label:** Credential Type
> **Description:** Type of credential such as badge, certification, bachelor degree.
> **Domain:**  ceterms:CredentialComponent
> **Range:** subclass of ceterms:Credential

> **URI:** ceterms:description
> **Label:** Description
> **Description:** Statement, characterization or account of the resource.
> **Domain:** ceterms:Pathway, ceterms:ComponentCondition, ceterms:RuleSetProfile, subclasses of ceterms:PathwayComponent
> **Range:** rdf:langString

> **URI:** ceterms:ruleType
> **Label:** Rule Type
> **Description:** Resource identifying the method of applying the rule specified by the ruleSetUsed property. 
> **Comment** Best practice is a URI from a defined ceterms:RuleSet such as https://example.org/All or https://example.org/RequiredNumber. 
> **Domain:** ceterms:RuleSetProfile
> **Range:** xsd:anyURI

> **URI:** ceasn:hasChild
> **Label:** Has Child
> **Description:** The referenced resource is lower in some arbitrary hierarchy than the resource being described.
> **Comment:** This property identifies a child node in the downward path in the chain of resources in a taxon path.
> **Domain:** subclasses of ceterms:PathwayComponent, ceterms:Pathway
> **Range:** subclasses of ceterms:PathwayComponent

> **URI:** ceterms:hasCondition
> **Label:** Has Condition
> **Description:** Resource referenced defines the conditions by which a rule set is satisfied.
> **Domain:** subclasses of ceterms:PathwayComponent
> **Range:** ceterms:ComponentCondition

> **URI:** ceterms:hasDestinationComponent
> **Label:** Has Destination Component
> **Description:** Goal or destination node of the pathway.
> **Domain:** ceterms:Pathway
> **Range:** subclasses of ceterms:PathwayComponent

> **URI:** ceterms:hasRuleSet
> **Label:** Has Rule Set
> **Description:** Identifies the resource describing the values necessary to apply the rules defined in the rule set.
> **Domain:** ceterms:ComponentCondition
> **Range:** ceterms:RuleSetProfile

> **URI:** ceasn:isChildOf
> **Label:** Is Child Of
> **Description:** The referenced resource is higher in some arbitrary hierarchy than this resource.
> **Domain:** subclasses of PathwayComponent
> **Range:** subclasses of PathwayComponent

> **URI:** ceterms:isDestinationComponentOf
> **Label:** Is Destination Component Of
> **Description:** Pathway for which this resource is the goal or destination.
> **Domain:** subclasses of PathwayComponent
> **Range:** ceterms:Pathway

> **URI:** ceterms:name
> **Label:** Name
> **Description:** Name or title of the resource.
> **Domain:** ceterms:Pathway, ceterms:ComponentCondition, ceterms:RuleSetProfile, subclasses of ceterms:PathwayComponent
> **Range:** rdf:langString

> **URI:** ceterms:offeredBy
> **Label:** Offered By
> **Description:** Agent that offers the resource.
> **Domain:** ceterms:Pathway
> **Range:** ceterms:Agent

> **URI:** ceterms:offers
> **Label:** Offers
> **Description:** Resource offered or conferred by the organization or person.
> **Domain:** ceterms:Agent
> **Range:** ceterms:Pathway

> **URI:** ceterms:ownedBy
> **Label:** Owned By
> **Description:** Organization or person with an enforceable claim or legal title to the resource.
> **Domain:** ceterms:Pathway
> **Range:** ceterms:Agent

> **URI:** ceterms:owns
> **Label:** Owns
> **Description:** Resource over which the organization or person claims legal title.
> **Comment:** Generally, the value of the property should be one of the subclasses of ceterms:Credential or ceterms:Pathway.
> **Domain:** ceterms:Agent
> **Range:** ceterms:Pathway

> **URI:** ceterms:pointValue
> **Label:** Point Value
> **Description:** Points associated with this resource, or points possible.
> **Domain:** subclasses of ceterms:PathwayComponent
> **Range:** xsd:float

> **URI:** ceterms:precedes
> **Label:** Precedes
> **Description:** Resource that logically comes after this resource.
> **Comment:** The ceterms:precedes property indicates a simple or suggested ordering of resources; if a required ordering is intended, use ceterms:prerequisite instead.
> **Domain:** subclasses of ceterms:PathwayComponent
> **Range:** subclasses of ceterms:PathwayComponent

> **URI:** ceterms:prerequisite
> **Label:** Prerequisite
> **Description:** Resource that is required as a prior condition to this resource.
> **Domain:** subclasses of ceterms:PathwayComponent
> **Range:** subclasses of ceterms:PathwayComponent

> **URI:** ceterms:programTerm
> **Label:** Program Term
> **Description:** Categorization of a term sequence based on the normative time between entry into a program of study and its completion such as "1st quarter", "2nd quarter"..."5th quarter".
> **Domain:** ceterms:CourseComponent
> **Range:** rdf:langString

> **URI:** ceterms:ruleSetUsed
> **Label:** Rule Set Used
> **Description:** Resource defining the applicable method or algorithm used for fulfilling the requirements of the ComponentCondition.
> **Domain:** ceterms:RuleSetProfile
> **Range:** xsd:anyURI

> **URI:** ceterms:sourceData
> **Label:** Source Data
> **Description:** Structured data representing the resource.
> **Comment:** The preferred data serialization is JSON-LD or some other serialization of RDF.
> **Domain:** subclasses of ceterms:PathwayComponent
> **Range:** xsd:anyURI

> **URI:** ceterms:subjectWebpage
> **Label:** Subject Webpage
> **Description:** The webpage that describes this entity.
> **Domain:** subclasses of Pathway Component
> **Range:** xsd:anyURI

> **URI:** ceterms:targetComponent
> **Label:** Target Component
> **Description:** Candidate PathwayComponent for the ComponentCondition as determined by applying the RuleSet.
> **Domain:** ceterms:ComponentCondition
> **Range:** subclasses of ceterms:PathwayComponent

**Comment by siuc-nate** [comment]
Changes implemented in pending:

ceterms:Agent (modified class)
Comment (old): Broad type that includes both organizations and people who play roles in the lifecycle of a credential.
Comment (new): Broad type that includes both organizations and people who play roles in the lifecycle of a resource.

New classes (see above for attributes):
ceterms:Pathway
ceterms:PathwayComponent
ceterms:AssessmentComponent
ceterms:BasicComponent
ceterms:CocurricularComponent
ceterms:CompetencyComponent
ceterms:ComponentCondition
ceterms:CourseComponent
ceterms:CredentialComponent
ceterms:ExtracurricularComponent
ceterms:JobComponent
ceterms:RuleSet
ceterms:RuleSetProfile
ceterms:WorkExperienceComponent

I'll start adding the properties now and will update this post when they're done.

**Comment by siuc-nate** [comment]
Proposal per our 2-8-2019 meeting:
- add ceterms:CredentialComponent to the domain of ceterms:targetCredential
- add ceterms:AssessmentComponent to the domain of ceterms:targetAssessment
- add ceterms:CompetencyComponent to the domain of ceterms:targetCompetency
- add ceterms:CourseComponent to the domain of ceterms:targetLearningOpportunity

**Comment by siuc-nate** [comment]
@stuartasutton We discussed last week adding several of the above classes to the domain of `ceterms:description`, but it seems we didn't explicitly list them out. Would it be correct to apply it to all of the classes that we added to the domain of `ceterms:name`?

**Comment by stuartasutton** [comment]
Yes, that would be appropriate...name and description as standard fare.

**Comment by siuc-nate** [comment]
I've updated pending CTDL and the posts above.

**Comment by siuc-nate** [comment]
These changes have been noted in the history tracking.

**Comment by siuc-nate** [comment]
per @stuartasutton:

The following will become "vs:unstable" when this release of the schema goes live:
- ceterms:alternativeRuleSet
- ceterms:RuleSetProfile
- ceterms:RuleSet
