### ISSUE TITLE
Revision or version identifier for CDTL

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#547]
A question was raised about the use of some property to indicate the version of CTDL used in the current document. We have history information for CTDL. Does it make sense to have a property that would be included for the main document to indicate the version identifier or version date that to which the contents would conform?
This might be useful for major changes. I don’t know how it would be implemented with minor changes. 

**Reply from Stuart**:
Michael, I don't think that's meaningful for inclusion in the main document since, as you note, we purposely don't version CTDL because there should never be backward compatibility issues in terms of the CTDL itself. That's not so say that there cannot be backwards compatibility issues with how it's handled in the CER profile. But doing anything there would mean versioning the json schema used to validate, not the CTDL.

This is really a good question for us to weave into the CTDL 'history' through a github issue.

**Comment by siuc-nate** [comment]
Per our 4-9-2019 meeting:
Closing this.
