### ISSUE TITLE
Policy regarding content of ceterms:owns when publishing an Organization

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#548]
@stuartasutton @siuc-nate @jkitchensSIUC 
I wanted to move this discussion started in the Registry assistant repository, as it is not API specific:
https://github.com/CredentialEngine/Registry_Assistant/issues/1

Following is the pertinent content from the latter issue
From Stuart

> @cwd-mparsons, @jkitchensSIUC, @siuc-nate, I reopened this issue because I want to make sure I understand. Are you saying that a CredentialOrganization identifies it's credentials with something like "owns": "http://......." as opposed to "owns: {"@id": "http://......."}? I don't know how I would have missed that. If so, it basically means that we've added a means for an org to signal what it owns; but we know that the data is useless as linked data in the wild.
> 
> I recall the original rationale was (under my objection) not to add any reference from an organization record to that it owns because it would mean updating/resigning the org record every time a new credential was added. Seems now that it is OK to add a mention (but not a linkable reference). What is the rationale now?

Response from Nate:

> @stuartasutton There are two related things at play here:
> 
> First, the change to the structure was part of the updates to the context file a long while back. ceterms:owns (and ceterms:offers, and a number of other properties that point to URIs or instances of CTDL classes) is defined as { "@type": "@id" } in the context, so there is no need to use an object with an @id property anymore. "ceterms:owns": [ "http://..." ] would still be linked data with that context.
> 
> The second part is providing the information in the organization record. This is something that @jkitchensSIUC has recently raised while discussing the minimum data policy (specifically, to make owns and offers required fields on ceterms:CredentialOrganization records and required if available fields on ceterms:QACredentialOrganization records). I can see some utility in this, but I also share your concerns, as this means:
> 
> A. The organization record needs to be updated every time something new is offered (or ceases being offered), and every time something new is created
> B. There is the potential for inconsistent data (e.g. newly-published credential says it's offered by organization A, but organization A's record hasn't been updated to reflect this in its "owns" property. A system consumes both records. What conclusion does it draw?)
> B1. This is potentially magnified in cases where an organization offers credentials owned by another organization (e.g. A newly-published credential says it's owned by Organization A and offered by Organization B; but Organization A can't force an update to Organization B's record to reflect the inverse. A system consumes all three records. What conclusion does it draw?)
> B2. The same applies in reverse (e.g. Organization A's record says that it offers a credential it does not own, and therefore cannot force an update to the credential record to say that it is offered by that organization. A system consumes both records. What conclusion does it draw?)
> C. It is redundant anyway if the relationship is reliably provided in the credential record, since it means that this can be determined by querying inverse properties (e.g. find out everything an organization owns or offers by querying the registry for all records where ownedBy or offeredBy contains the organization's URI).
> C1. This would not solve point B2 above, however.
> D. This kind of thing may be better solved by an on-demand service provided by the registry (e.g. When an organization's record is retrieved and some relevant parameter is provided, append something arbitrary to the resultant data (perhaps in the @graph? or maybe the envelope?) that provides URIs to records that indicate they are owned/offered by that organization)

**Comment by cwd-mparsons** [comment]
@stuartasutton @siuc-nate @jkitchensSIUC 
We certainly do not have to use or recommend the use of `ceterms:owns`. This is especially true/unnecessary for the simple case where all pertinent credentials will be published to the registry separately. 
Would there be a case where an organization will not be publishing full credentials to the registry (or the wild), and only wants to publish a list of credentials using references in `ceterms:owns`?

Our guidance could be that an owning organization doesn't have to include all of their credentials (or assessments and learning opportunities) in the `ceterms:owns` property, especially when publishing the artifacts separately. We have an edit in the publisher to now allow a non-QA organization to be published to the registry unless it owns or offers at least one credential. We don't have to include the `ceterms:owns` when publishing the organization.

DECISION REQUEST: 
Publisher - Should we stop including `ceterms:owns` and `ceterms:offers` when publishing a credentialing organization, where the target artifacts are full fledged entities, i.e. not references?

Would this policy also relate to `ceterms:recognizes`, `ceterms:regulates`,`ceterms:revokes`, `ceterms:renews`? That is where the assertion was made in the context of a credential, should the assertion also be published with the organization?

**Comment by stuartasutton** [comment]
STOP! No, CTID is no substitute for linked data. So, we are actually including URI now with these properties...see:

```
"ceterms:name": "CompTIA",
  "ceterms:offers": [
    {
      "@id": "https://credentialengineregistry.org/resources/ce-3877CDEC-09B6-45DF-814F-EDE85C023858"
    },
    {
         "@id": "https://credentialengineregistry.org/resources/ce-1984488f-7ac2-4f95-b1f6-cc845441876b"
    },
    {
         "@id": "https://credentialengineregistry.org/resources/ce-652f6f2c-4fff-45d0-9b2f-44a5bb61f826"
    },
    {
         "@id": "https://credentialengineregistry.org/resources/ce-9698BFD8-4887-4BF7-BB52-7F74661629A2"
    },
    {
         "@id": "https://credentialengineregistry.org/resources/ce-195F53A7-0635-46F6-9706-E3DDF881683F"
    },
    {
         "@id": "https://credentialengineregistry.org/resources/ce-31034ed7-2bbb-4dd8-8d00-2be69690eb7b"
    },
    {
         "@id": "https://credentialengineregistry.org/resources/ce-1422B7B0-C803-4D05-8728-0C8B1134A174"
    },
    {
         "@id": "https://credentialengineregistry.org/resources/ce-C57948C2-6636-4ED3-9B51-BC5A9EC56D88"
    },
    {
         "@id": "https://credentialengineregistry.org/resources/ce-F89C44B1-B408-4805-8653-8C92DA175E31"
    }
  ],
```
So, no, we should NOT stop including these properties. While they may not add anything in the "Finder", they are critical in the wild. Coming across a JSON-LD description of Comptia with absolutely no reference to what it owns/offers etc. is far from useful. None of the "out of sync" arguments justify producing nearly useless data (in the wild). If we are so concerned about the issue of keeping in sync, then the registry should implement a check system that alerts parties when things get out of sync.

**Comment by cwd-mparsons** [comment]
@stuartasutton @siuc-nate  I want to make clear we are not proposing to use just CTID. This is unrelated to the originating Github issue, which was the reason for creating a new/separate issue.
As Nate noted, the full URI of the object is presented in a list of strings. I don't have the background for this change, I just implemented it. Part of the rational was for the handling of blank nodes. 
Your CompTIA example would be formatted as follows, with an additional element for a blank node:
```
{
"@graph": [
{
-----
 "ceterms:name": "CompTIA",
  "ceterms:offers": [
    "https://credentialengineregistry.org/resources/ce-3877CDEC-09B6-45DF-814F-EDE85C023858",
    "https://credentialengineregistry.org/resources/ce-1984488f-7ac2-4f95-b1f6-cc845441876b",
    "https://credentialengineregistry.org/resources/ce-652f6f2c-4fff-45d0-9b2f-44a5bb61f826",
    "https://credentialengineregistry.org/resources/ce-9698BFD8-4887-4BF7-BB52-7F74661629A2",
    "https://credentialengineregistry.org/resources/ce-195F53A7-0635-46F6-9706-E3DDF881683F",
    "https://credentialengineregistry.org/resources/ce-31034ed7-2bbb-4dd8-8d00-2be69690eb7b",
   "https://credentialengineregistry.org/resources/ce-1422B7B0-C803-4D05-8728-0C8B1134A174",
    "https://credentialengineregistry.org/resources/ce-C57948C2-6636-4ED3-9B51-BC5A9EC56D88",
    "https://credentialengineregistry.org/resources/ce-F89C44B1-B408-4805-8653-8C92DA175E31",
    "_:b2a65745-bd4c-462f-8914-0971e3f89cc4"
  ],
------
] ,
  {
    "@id": "_:b2a65745-bd4c-462f-8914-0971e3f89cc4",
    "@type": "ceterms:certification",
    "ceterms:name": "A certification offered by CompTIA",
    "ceterms:subjectWebpage": "https://www.example.com"
  }
}
```
By (the new) definition, the string value is to be interpreted as an @id. The previous method of representing a credential reference as an object, would have resulted in blank nodes being inline in the list of objects. 

It appears the issue to resolve has been muddied.
a) You seem to be suggesting that it is OK to publish URIs for what an organization owns and offers, even if not in sync with all published artifacts. 
True?
b) Also, we want to make clear that organizations are not required to keep the **owns** property in sync with actual published credentials. The latter would be left up to each individual organization. 
True?
c) I am not sure if you are stating that we should **not** use a list strings to represent URIs for owns, offers, approves, etc., but should be still using a list of objects, with a minimum of @id. 
True: use list of objects?
False: continue to use a list of strings?

**Comment by stuartasutton** [comment]
Just to be clear, in RDF and linked data, URIs identify objects (always). Unfortunately, it is possible to serialize URIs in such a way that the they are treated as literals. If they are treated here as “things” not “strings”, then all is well.

Being in “sync” in the terms of this issue is obviously good. But it is not disastrous if they are not...not disastrous. And, I repeat, to the extent there are synchronization issues, the solution is to automate notification, not to not make the assertions.

**Comment by stuartasutton** [comment]
@siuc-nate, if I understand you correctly, no. My sole concern here is with the data outside the registry where there is no "registry software" to handle anything. My position is exactly where it has always been. If an org owns something it should say so by URIref and the thing owned should say it is owned by the org by URIref. If declared as actual inverse properties (e.g., owns/ownedBy)(ours aren't), a database handling RDF data would infer and store the inverse through the very existence of the inverse property (i.e., no sync issue).

**Comment by siuc-nate** [comment]
Then it probably comes down to determining which properties should really be inverse properties.  This is complicated by the ability for an organization to do something with a credential that it does not own.  

For instance, if a credential says it is offered by another organization, but that organization does not really offer it, it would be bad to automatically infer, inject, or provide data in the organization's record that says that it offers that credential. Even if the properties "offeredBy" and "offers" are theoretically inverse of one another, that may not always be the case in practical terms.

This is probably more important when it comes to QA.  Someone could publish a credential that claims to be accredited by another organization, but we would not want to give the impression that that assertion flows both ways unless it truly does (unless that QA org also says it accredits that credential).

Am I way off base here?

**Comment by siuc-nate** [comment]
Inverse property assertions can be **automatically** generated if both of the records involved are owned by the same organization (in other words, the organization _could_ change both records). This includes these properties:
- ceterms:owns / ceterms:ownedBy
- ceterms:offers / ceterms:offeredBy (if owned by the same organization)

Inverse property assertions **cannot** be automatically generated if both of the records involved _are not_ owned by the same organization. This includes these properties:
- ceterms:offers / ceterms:offeredBy (if not owned by the same organization)
- ceterms:regulates / ceterms:regulatedBy
- ceterms:accredits / ceterms:accreditedBy
- ceterms:recognizes / ceterms:recognizedBy
- ceterms:approves / ceterms:approvedBy

This is a registry service issue.

**Comment by siuc-nate** [comment]
Per our 4-9-2019 meeting:
This is handled by graph search features.
