### ISSUE TITLE
Update the definition of ceterms:inLanguage

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#549]
The current definition of [`ceterms:inLanguage`](http://credreg.net/ctdl/terms/inLanguage) reads:
>This is the primary language the entity, even if the it makes use of other languages. For example, a course that teaches Spanish to English-speaking students may primarily be in English, because that is the language used to convey the material.

There are a few typos to correct here, namely:
>This is the primary language **of** the entity, even if ~~the~~ it makes use of other languages. For example, a course that teaches Spanish to English-speaking students may primarily be in English, because that is the language used to convey the material.

The wording may also need revision.  A suggestion from an advisory group member reads:
>This is the primary language in which the credential is offered.  The credential may make use of other languages (for example, a course that teaches Spanish to English-speaking students will also use Spanish) but inLanguage is the primary language used to convey the material.

However, we shouldn't constrain the definition to just credentials, since `ceterms:inLanguage` is used assessments and learning opportunities as well.

I think something like this may be more streamlined:
>The primary language of the entity, even if it makes use of other languages. For example, a course offered in English to teach Spanish would have an inLanguage of English.

It may be worth moving the example portion of the definition to a comment, but I'm not sure how that gels with other definitions after the last major round of definition updates that @stuartasutton came up with.

**Comment by erafal10** [comment]
Your suggestion makes sense to me.

**Comment by stuartasutton** [comment]
Yes, we softened when examples can be part of the definition where it helps the clarity of the definition. Doing so is a tradeoff since it is inherently problematic since properties end up needing to be used in places not originally imagined and sometimes the example text becomes limiting. This does not feel like such a case.

**Comment by siuc-nate** [comment]
Change to be made:
**Remove:**
>**Subject:** ceterms:inLanguage
>**Predicate:** rdfs:comment
>**Object:** This is the primary language the entity, even if the it makes use of other languages. For example, a course that teaches Spanish to English-speaking students may primarily be in English, because that is the language used to convey the material.

**Add:**
>**Subject:** ceterms:inLanguage
>**Predicate:** rdfs:comment
>**Object:** The primary language of the entity, even if it makes use of other languages. For example, a course offered in English to teach Spanish would have an inLanguage of English.

@jkitchensSIUC @stuartasutton Please sign off on this.

**Comment by stuartasutton** [comment]
@stuartsutton signs off

**Comment by stuartasutton** [comment]
We have to key off whether this is "a language" of the resource or "the primary language" of the resource. Both make sense and are useful; however, as you note, "primary" points to a single, predominant language. I say we go with it as the definition suggests--single language with the possibility down the road of adding something like "secondaryLangauge" in the future should uses so dictate.

**Comment by siuc-nate** [comment]
I think it would be possible to have more than one primary language, albeit rare.  Rather than worry about a second property, I think it's more practical to use a multi-value field and tweak the definition.  Something like:

**Remove:**
>**Subject:** ceterms:inLanguage
>**Predicate:** rdfs:comment
>**Object:** This is the primary language the entity, even if the it makes use of other languages. For example, a course that teaches Spanish to English-speaking students may primarily be in English, because that is the language used to convey the material.

**Add:**
>**Subject:** ceterms:inLanguage
>**Predicate:** rdfs:comment
>**Object:** The primary language or languages of the entity, even if it makes use of other languages; e.g., a course offered in English to teach Spanish would have an inLanguage of English.

Perhaps we could add a comment or usage note to clarify further? That may be overkill.

**Comment by stuartasutton** [comment]
What about:

> Object: The primary language or languages of the entity, even if it makes use of other languages; e.g., a course offered in English to teach Spanish would have an inLanguage of English while a credential in Quebec could have an inLanguage of both French and English.

**Comment by siuc-nate** [comment]
I like it.

**Remove:**
>**Subject:** ceterms:inLanguage
>**Predicate:** rdfs:comment
>**Object:** This is the primary language the entity, even if the it makes use of other languages. For example, a course that teaches Spanish to English-speaking students may primarily be in English, because that is the language used to convey the material.

**Add:**
>**Subject:** ceterms:inLanguage
>**Predicate:** rdfs:comment
>**Object:** The primary language or languages of the entity, even if it makes use of other languages; e.g., a course offered in English to teach Spanish would have an inLanguage of English, while a credential in Quebec could have an inLanguage of both French and English.

**Comment by siuc-nate** [comment]
Actually, I think we got our wires crossed somewhere - the text we've been discussing is currently the **comment** (as in, dct:description) for inLanguage, **not** the definition (as in, rdfs:comment).

The actual **definition** for [inLanguage](http://localhost:40799/ctdl/terms/inLanguage) is:
>Primary language of the credential, learning opportunity or assessment.

The **comment** is:
>This is the primary language the entity, even if the it makes use of other languages. For example, a course that teaches Spanish to English-speaking students may primarily be in English, because that is the language used to convey the material.

Should we make the changes above to the comment (dct:description) instead of the definition (rdfs:comment) instead?  Or should we replace the definition completely and remove the comment?

In other words, which of the two is correct:

**Remove:**
>**Subject:** ceterms:inLanguage
>**Predicate:** dct:description
>**Object:** This is the primary language the entity, even if the it makes use of other languages. For example, a course that teaches Spanish to English-speaking students may primarily be in English, because that is the language used to convey the material.

**Add:**
>**Subject:** ceterms:inLanguage
>**Predicate:** dct:description
>**Object:** The primary language or languages of the entity, even if it makes use of other languages; e.g., a course offered in English to teach Spanish would have an inLanguage of English, while a credential in Quebec could have an inLanguage of both French and English.

or:

**Remove:**
>**Subject:** ceterms:inLanguage
>**Predicate:** rdfs:comment
>**Object:** Primary language of the credential, learning opportunity or assessment.

>**Subject:** ceterms:inLanguage
>**Predicate:** dct:description
>**Object:** This is the primary language the entity, even if the it makes use of other languages. For example, a course that teaches Spanish to English-speaking students may primarily be in English, because that is the language used to convey the material.

**Add:**
>**Subject:** ceterms:inLanguage
>**Predicate:** rdfs:comment
>**Object:** The primary language or languages of the entity, even if it makes use of other languages; e.g., a course offered in English to teach Spanish would have an inLanguage of English, while a credential in Quebec could have an inLanguage of both French and English.

@stuartasutton

**Comment by stuartasutton** [comment]
We should change the definition and drop the comment.

**Comment by siuc-nate** [comment]
Per our 4-9-2019 meeting:
This was already completed.
