### ISSUE TITLE
Representing pathway 'Agents'

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#551]
@jkitchensSIUC, @jeff-grann & @siuc-nate, the work so far on pathways has included the `ctdl:Agent` class as the entity that offers/owns/recommends/recognizes a pathway. As such, I did not see any properties that are not already accommodated. However, we currently have only two subclasses of `ctdl:Agent`: `ctdl:CredentialOrganization` and `ctdl:QACredentialOrganization`. While `ctdl:Person` is also a subclass of `ctdl:Agent`, individuals are out of scope for CE Pathways. I'm curious how the team sees the use of `ctdl:CredentialOrganization` for the owner/offeror/recommendor/recognizer of a `ctdl:Pathway`?

**Comment by siuc-nate** [comment]
Per our 4-9-2019 meeting:

**Add:**
> **Subject:** ceterms:offers
> **Predicate:** schema:rangeIncludes
> **Domain:** ceterms:Pathway

**Comment by siuc-nate** [comment]
It seems this was already done as part of the previous release 
https://credreg.net/ctdl/release?releaseID=20190301
