### ISSUE TITLE
Change the range of ceasn:dateValidFrom and ceasn:dateValidUntil from xsd:date to xsd:dateTime

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#552]
See https://github.com/cassproject/cass-editor/issues/217

Actions to be taken:
**Remove**
> **URI:** ceasn:dateValidFrom
> **Predicate:** schema:rangeIncludes
> **Object:** xsd:date

> **URI:** ceasn:dateValidUntil
> **Predicate:** schema:rangeIncludes
> **Object:** xsd:date

**Add**
> **URI:** ceasn:dateValidFrom
> **Predicate:** schema:rangeIncludes
> **Object:** xsd:dateTime

> **URI:** ceasn:dateValidUntil
> **Predicate:** schema:rangeIncludes
> **Object:** xsd:dateTime

**Comment by Lomilar** [comment]
Please notify @Lomilar so he can modify the translation schema in CaSS when this is complete.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL-ASN and noted in the history tracking.

@Lomilar these changes go live tomorrow.
