### ISSUE TITLE
Add targetPathway to credential, assessment and learning opportunity

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#555]
Currently, [`ceterms:targetPathway`](http://purl.org/ctdl/terms/targetPathway) has a domain of only `ceterms:ConditionProfile`--a rationale that escapes me since the pathway relationship is simple and seldom likely to be conditioned. As the pathways work has played out, `PathwayComponents` (prescribed milestones) can represent credentials, assessments, or learning opportunities--as well as other resources. Thus, `ceterms:targetPathway` should be added to the domains of `ceterms:Credential`, `ceterms:AssessmentProfile`, and `ceterms:LearningOpportunityProfile` so references can be made to pathways in which they are represented as components.

**Comment by siuc-nate** [comment]
I think it's far better from a data integrity standpoint if the pathway references the credential - this will be much more reliable. Otherwise, it will be up to publishers of credentials to update their credentials any time anyone else's pathway is created/modified to reference that credential, leading to incorrect/outdated/misleading information as part of the credential's record itself.

If the data remained solely on the pathway instead, it would be a simple query to get all of the pathways for a credential (simply query for all pathways that reference that credential).

**Comment by siuc-nate** [comment]
Is the following correct?

**Remove:**
>**Subject:** ceterms:targetPathway
>**Predicate:** schema:domainIncludes
>**Object:** ceterms:ConditionProfile

**Add:**
>**Subject:** ceterms:targetPathway
>**Predicate:** schema:domainIncludes
>**Object:** ceterms:Credential (and subclasses)

**Add:**
>**Subject:** ceterms:targetPathway
>**Predicate:** schema:domainIncludes
>**Object:** ceterms:AssessmentProfile

**Add:**
>**Subject:** ceterms:targetPathway
>**Predicate:** schema:domainIncludes
>**Object:** ceterms:LearningOpportunityProfile

**Comment by stuartasutton** [comment]
In working through this addition of targetPathway to credential, assessment, learning opportunity, consider whether the range is actually the Pathway or is it to an aligned PathwayComponent or is it both (targetPathway & targetPathwayComponent). I.e., an instance of AssessmentProfile might have a targetPathwayComponent aligning it to a AssessmentComponent in a Pathway.

**Comment by siuc-nate** [comment]
Per our 4-9-2019 meeting:

**Remove:**
>**Subject:** ceterms:targetPathway
>**Predicate:** schema:domainIncludes
>**Object:** ceterms:ConditionProfile

**Add:**
>**Subject:** ceterms:targetPathway
>**Predicate:** schema:domainIncludes
>**Object:** ceterms:Credential (and subclasses)

**Add:**
>**Subject:** ceterms:targetPathway
>**Predicate:** schema:domainIncludes
>**Object:** ceterms:AssessmentProfile

**Add:**
>**Subject:** ceterms:targetPathway
>**Predicate:** schema:domainIncludes
>**Object:** ceterms:LearningOpportunityProfile

**Remove:**
>**Subject:** ceterms:targetPathway
>**Predicate:** rdfs:label
>**Object:** "Career Pathway"

**Add:**
>**Subject:** ceterms:targetPathway
>**Predicate:** rdfs:label
>**Object:** "Target Pathway"

**Remove:**
>**Subject:** ceterms:targetPathway
>**Predicate:** rdfs:comment
>**Object:** "Career pathway in which the credential is a potential component."

**Add:**
>**Subject:** ceterms:targetPathway
>**Predicate:** rdfs:comment
>**Object:** "Pathway in which this resource is a potential component."

**Comment by siuc-nate** [comment]
I have made the changes in pending CTDL.  **Not noted in history tracking yet.**

There are two additional issues:
- ceterms:targetPathway has no range. Presumably the range should be ceterms:Pathway. Correct?
- ceterms:targetPathway is still vs:unstable. Do we want to keep it that way for now?
@stuartasutton

**Comment by siuc-nate** [comment]
I see #582 indicates that we should indeed update the range to be ceterms:Pathway.

However, what about the status?

**Comment by siuc-nate** [comment]
Per our 4-10-2019 meeting:
Per Jeanne, this property should indeed be made vs:stable.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
