### ISSUE TITLE
Add ceterms:industryType and ceterms:occupationType to ceasn:CompetencyFramework

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#557]
These properties would be very useful to have at the Competency Framework level, as they would enable a framework to indicate its relevant industries and occupations.

We would need to retain the range of ceterms:CredentialAlignmentObject in order to continue enabling references/descriptions of industries and occupations that don't exist in some external framework.

**Comment by stuartasutton** [comment]
Nate, I agree that we should consider the addition of these properties. BIG PUSH BACK...no alignment object.

**Comment by siuc-nate** [comment]
The reasoning behind the use of alignment object here would be to allow for the (apparently somewhat frequent) cases where there is no framework to align to, and the industry/occupation is simply included by name (potentially with some web page URL to point to).  This allows us to accommodate whatever data the publishing system has available while also normalizing the structure of the data for the sake of consuming systems.

**Comment by philbarker** [comment]
@siuc-nate using the AlignmentObject in that case seems wrong to me too. Am I understanding correctly that you want the domain to be a CompetencyFramework and the range to be an AlignmentObject, so the AlignmentObject points from the educational framework to an Occupation or Industry Type? That's not the direction AlignmentObjects usually work. Why not just point to a blank node with a label and url property? e.g (ignoring namespaces)
```
{"name": "my framework",
 "occupationType" : {
  "@type": "Occupation"
   "name": "dragon wrangling",
   "url": "http://hogwarts.sch.uk/carreers/dragonwrangling"
  }
}
```

[BTW, I don't much like the names industryType and occupationType as they have more obvious meanings when categorising Industries and Occupations; I'd suggest something like relevantOccupation & relevantIndustry]

**Comment by stuartasutton** [comment]
Nate, if there is no framework, then use of alignment object is wrong.

**Comment by siuc-nate** [comment]
Sometimes there is a framework.

If it would be preferable to override the ranges of these properties in the profile to be xsd:anyURI as opposed to ceterms:CredentialAlignmentObject then that is fine, provided we can ensure that blank nodes will have some sort of reliable structure (As always, the _structure_ of CredentialAlignmentObject is what gives it value for my purposes; the "alignment" aspect could just as well be done away with most of the time).

**Comment by siuc-nate** [comment]
@stuartasutton Then how would cases where there is no framework be handled?  I ask because we are currently using industryType and occupationType (and I _believe_ instructionalProgramType - @cwd-mparsons correct me if I'm wrong) to handle both framework and non-framework (i.e. plain text) alignments, per @jkitchensSIUC.

**Comment by stuartasutton** [comment]
(Sigh) Non-framework-based industry, occupation and instructional program types are, quite simply, literals...no need for the alignment object.

**Comment by siuc-nate** [comment]
So then what should the range of industryType and occupationType be? They need to handle both framework and non-framework cases (which is currently achieved through the structure provided by CredentialAlignmentObject).

**Comment by siuc-nate** [comment]
Alternative properties make sense, then.

@cwd-mparsons how is CIP code (instructionalProgramType) being handled? Is this implemented the same way (a combination of select existing/add your own)?

**Comment by siuc-nate** [comment]
Per our 1/15/2019 meeting:
- We will add industryType and occupationType to Competency Framework
- We will create new properties:
  - alternativeIndustryType
  - alternativeOccupationType 
- The above properties will be added to all domains that currently use industryType and occupationType, including Competency Framework

Note: The new properties will need proper definitions before this can move forward.

**Comment by stuartasutton** [comment]
Domain of the following properties as the same as `industryType`, `occupationType` and `instructionalProgramType`.

--------

#### alternativeIndustryType
**Term:** `alternativeIndustryType`
**Label:** Alternative Industry Type
**Definition:** Word or phrase denoting an industry where an appropriate term is not available in enumerations such as the SIC, NAICS, and ISIC classifications. 
**Comment:**  Where an appropriate term is available in enumerations such as the SIC, NAICS, and ISIC classifications, use the `industryType` property so the source of the term can be appropriately identified.
**RangeIncludes:** rdf:langString

--------

#### alternativeOccupationType
**Term:** `alternativeOccupationType`
**Label:** Alternative Occupation Type
**Definition:** Word or phrase denoting an occupation where an appropriate term is not available in enumerations such as the EU's ESCO, O*NET, ISCO-08, and SOC 2010. 
**Comment:**  Where an appropriate term is available in enumerations such as the EU's ESCO, O*NET, ISCO-08, and SOC 2010, use the `occupationType` property so the source of the term can be appropriately identified.
**RangeIncludes:** rdf:langString

--------

#### alternativeInstructionalProgramType
**Term:** `alternativeInstructional Program Type`
**Label:** Alternative Instructional Program Type
**Definition:** Word or phrase denoting an instructional program type where an appropriate term is not available in an enumeration such as CIP (Classification of Instructional Programs). 
**Comment:**  Where an appropriate term is available in an enumeration such as CIP (Classification of Instructional Programs), use the `instructionalProgramType` property so the source of the term can be appropriately identified.
**RangeIncludes:** rdf:langString

**Comment by stuartasutton** [comment]
Yes, they have a range of rdf:langString. So, I assume that means language maps.

**Comment by cwd-mparsons** [comment]
@stuartasutton
We have Naics as a convenience property to enter just a list of Naics codes. Should we also add similar properties for a list of O*Net and CIP codes?

**Comment by stuartasutton** [comment]
I don't understand, by "add similar properties" for NAICS codes.

**Comment by siuc-nate** [comment]
Changes made in pending CTDL (**not yet in history tracking**):
- Added ceterms:industryType to ceasn:CompetencyFramework
- Added ceterms:occupationType to ceasn:CompetencyFramework
- Created ceterms:alternativeIndustryType as outlined above (domains: CredentialOrganization, QACredentialOrganization, Credential + subclasses, AssessmentProfile, LearningOpportunityProfile, CompetencyFramework)
- Created ceterms:alternativeOccupationType as outlined above (domains: Credential + subclasses, AssessmentProfile, LearningOpportunityProfile, CompetencyFramework)
- Created ceterms:alternativeInstructionalProgramType as outlined above (domains: Credential + subclasses, AssessmentProfile, LearningOpportunityProfile)

Outstanding questions:
- Should ceterms:instructionalProgramType be added to ceasn:CompetencyFramework?
- Should ceterms:alternativeInstructionalProgramType be added to ceasn:CompetencyFramework?

**Comment by siuc-nate** [comment]
Per our 2-8-2019 Meeting:
We will not add instructionalProgramType/alternativeInstructionalProgramType to CompetencyFramework until some need for it is demonstrated.

**Comment by stuartasutton** [comment]
One lingering concern. Every time this thing/string need arises, we cannot/should not create "alternative"  properties. This has been solved (perhaps inelegantly) in several large German bibliographic services as well as elsewhere through declaring the property as requiring a thing and using bnodes to handle literals (without declaring any new properties).

### With URI

```
<http://id.meineInstitution.de/12345> 
    dct:creator <http://id.meineInstitution.de/Bergmann_Bertram>.
```

### Without URI

```
<http://id.meineInstitution.de/12345> 
    dct:creator [ rdfs:label "Bertram Bergmann" ].
```

![image](https://user-images.githubusercontent.com/2939046/52644780-4f2e9080-2e94-11e9-9b7e-d5243810c03b.png)

**Comment by siuc-nate** [comment]
That is more or less what we've been trying to accomplish with CredentialAlignmentObject (playing the role of the bnode) - the difference of course being that the CredentialAlignmentObject is _always_ present; I can see the benefit of using bnodes instead, especially if we make that a consistent solution in other places where the need to "point to something that may or may not exist" keeps coming up (such as pathway components).

**Comment by siuc-nate** [comment]
Per our 2-12-2019 meeting:

The three "alternative" properties will be removed from pending; instead the problem will be solved via the blank node solution @stuartasutton outlines above.

**Comment by siuc-nate** [comment]
Per our 2-12-2019 meeting:
Turtle example:
```
<http://123> a ceterms:Diploma
	ceterms:industryType <http://abc>, <_:ABC>.

<_:ABC> a ceterms:IndustryClassification
	rdfs:label "Cybersecurity"@en-us.
```

Equivalent JSON-LD graph:
```
"@graph":[
	{
		"@id": "http://123",
		"@type": "ceterms:Diploma",
		"ceterms:industryType": [
			"http://abc",
			"_:ABC"
		]
	},
	{
		"@id": "_:ABC",
		"@type": "ceterms:IndustryClassification",
		"rdfs:label": "Cybersecurity"
	}
]
```

**Comment by stuartasutton** [comment]
Nate, just a slight variation:

### TURTLE

```
@prefix ceterms: <http://purl.org/ctdl/terms/>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<http://123> a ceterms:Diploma;
	ceterms:industryType <http://1234.com/indust234>, [rdfs:label "Cybersecurity"@en-us].
```

### JSONLD
```
{
  "@context": {
    "ceterms": "http://purl.org/ctdl/terms/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@graph": [
    {
      "@id": "http://123",
      "@type": "ceterms:Diploma",
      "ceterms:industryType": [
        {
          "@id": "_:ub199bL4C52"
        },
        {
          "@id": "http://1234.com/indust234"
        }
      ]
    },
    {
      "@id": "_:ub199bL4C52",
      "rdfs:label": {
        "@language": "en-us",
        "@value": "Cybersecurity"
      }
    }
  ]
}
```

**Comment by siuc-nate** [comment]
No, we want to avoid unnecessary use of `@id` objects - that was one of the driving factors behind us switching to use `@graph` and blank nodes to begin with, otherwise we'd do this (which is the old way of doing things and resulted in **lots** of `@id` objects that were very irritating:
```
{
  "@context": {
    "ceterms": "http://purl.org/ctdl/terms/",
  },
  {
    "@id": "http://123",
    "@type": "ceterms:Diploma",
    "ceterms:industryType": [
      {
        "ceterms:name": {
        "en-us": "Cybersecurity"
        }
      },
      {
        "@id": "http://1234.com/indust234"
      }
    ]
  }
}
```

**Comment by siuc-nate** [comment]
Did any of your example get generated by a converter? I did notice the context didn't indicate that ceterms:industryType was an `@id` property (and the unnecessary expansion of the language map). I think this is closer to what you're looking for:
```
{
  "@context": {
    "ceterms": "http://purl.org/ctdl/terms/",
    "ceterms:industryType": {
      "@type": "@id"
    }
  },
  "@graph": [
    {
      "@id": "http://123",
      "@type": "ceterms:Diploma",
      "ceterms:industryType": [
        "_:ub199bL4C52",
        "http://1234.com/indust234"
      ]
    },
    {
      "@id": "_:ub199bL4C52",
      "ceterms:name": {
        "en-us": "Cybersecurity"
      }
    }
  ]
}
```

**Comment by siuc-nate** [comment]
I have removed alternativeIndustryType, alternativeOccupationType, and alternativeInstructionalProgramType from pending CTDL per the meeting referenced in the earlier post:
https://github.com/CredentialEngine/vocabularies/issues/557#issuecomment-462940239

**Comment by siuc-nate** [comment]
This has been noted in the history tracking. 

The ongoing discussion should continue in #574.
