### ISSUE TITLE
Add ceterms:industryType and ceterms:occupationType to ceterms:AssessmentProfile and ceterms:LearningOpportunityProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#559]
Per our 12/6/2018 meeting:

This would be done in order to make Credentials, Assessments, and Learning Opportunities have consistent properties.

**Comment by stuartasutton** [comment]
No objection.

**Comment by siuc-nate** [comment]
See also Issue #557

**Comment by stuartasutton** [comment]
This addition of `ceterms:industryType` and `ceterms:occupationType` to to the domains of `ceterms:AssessmentProfile` and `ceterms:LearningOpportunityProfile` seem OK to me.

**Comment by siuc-nate** [comment]
This has been done in pending CTDL.

Leaving this open for now, as it has not yet been done in the history tracking.

**Comment by cwd-mparsons** [comment]
@stuartasutton I was wondering about the Naics property. We have the latter for credentials, and organizations. Should it now also be added for assessments and learning opportunities?

**Comment by stuartasutton** [comment]
I don't think so. If present, it would be there on the related credential (and organization). I think it's unnecessary duplication of data about the organization across all primary resource related to it.

**Comment by siuc-nate** [comment]
This has been noted in the history tracking.
