### ISSUE TITLE
Error on a viewing a term's context

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#569]
When I try to look at the context for the term [`ceterms:endTime`](http://purl.org/ctdl/terms/endTime), I get the following error:

<img width="1420" alt="screen shot 2019-01-19 at 4 58 01 am" src="https://user-images.githubusercontent.com/2939046/51427019-32f64700-1ba7-11e9-85e7-298766c89258.png">

**Comment by siuc-nate** [comment]
I think they all use pretty much the same context data anyway, but, this has been fixed.
