### ISSUE TITLE
Review all alternative properties that should leverage blank nodes instead

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#575]
Such properties include:
- "alternative" properties
- properties that exist in one class but describe aspects of another class
- properties that point to concepts in a concept scheme

**Comment by jkitchensSIUC** [comment]
@siuc-nate please add a list of these properties.

**Comment by siuc-nate** [comment]
I'll pick through the schemas and come up with a list as soon as time allows.  As for why this is here, there may be implications for the schema - namely the range or status of some properties.

**Comment by siuc-nate** [comment]
Closing this as a duplicate of #574
