### ISSUE TITLE
Determine how to cluster pathway components together

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#576]
Per our 2-14-2019 meeting:
We need to determine a machine-readable way to "cluster" pathway components together to form sets of related components, often relating to a term (such as "1st term"/"2nd term" or "beginner"/"intermediate").

This may involve changing the domain/range of ceterms:programTerm - which has had its status set to unstable.

**Comment by stuartasutton** [comment]
Solution: Progression Models (via concept schemes)
