### ISSUE TITLE
Correcting the definition text for ceasn:prerequisiteAlignment

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#579]
This is an **immediate** correction under the Namespace Policy regarding errors. The text of the definition gives the opposite result from  what has always been intended (error goes all the way back into the ASN property).  

ceasn:prerequisiteAlignment currently reads:

>`rdfs:comment: "This competency is a prerequisite to the referenced competency."@en-US ;`

Instead, it should read:

>`rdfs:comment "The resource referenced is a prerequisite to this competency."@en-US ;`

Note: The use of "resource" in this particular instance is intended to make this property more portable (e.g., as used in the CRADA).

**Comment by siuc-nate** [comment]
I have updated the definition `rdfs:comment` to:
`The referenced resource is a prerequisite to this resource.`

**Comment by jkitchensSIUC** [comment]
@siuc-nate @stuartasutton can this be closed?

**Comment by siuc-nate** [comment]
Yes, it can now - I had left it open since I still needed to add it to the history tracking.  This has been done now.
