### ISSUE TITLE
hasChild and hasTopChild are not a @list of @id

### ISSUE THREAD

**Issue by Lomilar** [CredentialEngine/vocabularies#580]
Current:
```json
"ceasn:hasChild": {
"@id": "ceasn:hasChild",
"@container": "@list"
},
"ceasn:hasTopChild": {
"@type": "@id",
"@container": "@list"
},
```
Resulting in:
```json
    {
      "@id": "https://staging.credentialengineregistry.org/resources/ce-57e0360a-683f-4b56-bc1d-e0f57161b9e6",
      "@type": "ceasn:Competency",
      "ceterms:ctid": "ce-57e0360a-683f-4b56-bc1d-e0f57161b9e6",
...
      "ceasn:hasChild": [
        {
          "@id": "https://staging.credentialengineregistry.org/resources/ce-263c33b4-ce76-4baf-95ec-e0d3104ab168"
        },
        {
          "@id": "https://staging.credentialengineregistry.org/resources/ce-8971d49f-c687-4d0d-8323-ce8b6f0a1740"
        },
        {
          "@id": "https://staging.credentialengineregistry.org/resources/ce-1eeaf637-22f3-44f1-a5e4-0db1348df7d5"
        },
        {
          "@id": "https://staging.credentialengineregistry.org/resources/ce-01515ed0-e4ec-4710-a013-4b4cd3d759cf"
        },
        {
          "@id": "https://staging.credentialengineregistry.org/resources/ce-d6eda3c8-5848-45ae-9512-7233387a4c1c"
        }
      ],
...
    }
```

Desired:
```json
"ceasn:hasChild": {
"@id": "ceasn:hasChild",
"@container": "@list",
  "@type":"@id"
},
"ceasn:hasTopChild": {
"@type": "@id",
"@container": "@list",
  "@type":"@id"
},
```

**Comment by stuartasutton** [comment]
@Lomilar, OK, I see the difference, but the example doesn't show me how the results would be different.

**Comment by siuc-nate** [comment]
This was due to the way the system calculates which terms are `@type: @id`.  I have changed it.

FYI:
- Previously, **all** classes in the range of a term had to be considered top-level for the term to get flagged as `@type: @id`
- Now, if **any** class in the range of a term is considered top-level, the term will be flagged as `@type: @id`

**Comment by siuc-nate** [comment]
@stuartasutton I believe the difference would be:
```json
 {
      "@id": "https://staging.credentialengineregistry.org/resources/ce-57e0360a-683f-4b56-bc1d-e0f57161b9e6",
      "@type": "ceasn:Competency",
      "ceterms:ctid": "ce-57e0360a-683f-4b56-bc1d-e0f57161b9e6",
...
      "ceasn:hasChild": [
        "https://staging.credentialengineregistry.org/resources/ce-263c33b4-ce76-4baf-95ec-e0d3104ab168",
        "https://staging.credentialengineregistry.org/resources/ce-8971d49f-c687-4d0d-8323-ce8b6f0a1740",
        "https://staging.credentialengineregistry.org/resources/ce-1eeaf637-22f3-44f1-a5e4-0db1348df7d5",
        "https://staging.credentialengineregistry.org/resources/ce-01515ed0-e4ec-4710-a013-4b4cd3d759cf",
        "https://staging.credentialengineregistry.org/resources/ce-d6eda3c8-5848-45ae-9512-7233387a4c1c"
      ],
...
    }
```
Rather than each of those URIs getting wrapped in an `@id` object.

**Comment by Lomilar** [comment]
Correct.

**Comment by stuartasutton** [comment]
It would be good to cerify that this is fully accurate since it reverberates through a number of @context files

**Comment by siuc-nate** [comment]
http://credreg.net/ctdl/schema/context/json
http://credreg.net/ctdlasn/schema/context/json
Unless I'm mistaken, everything we use leverages one or both of the above context files.

**Comment by stuartasutton** [comment]
Yes, that is accurate. But there are additional projects.

**Comment by Lomilar** [comment]
Would reproduction steps for doing this in the JSON-LD playground suffice?

**Comment by stuartasutton** [comment]
Perhaps, @Lomilar, but I'd like to take the result on through to a RDF serialization (turtle, rdf/xml). Unfortunately, while all RDF graphs can be serialized using JSONLD, not all JSONLD produces good RDF graphs.

**Comment by Lomilar** [comment]
There are some tabs on the playground for emitting JSON-LD in Quads, but I believe that is where the support ends.

weird, this isn't reproducing on my end today.

1. https://json-ld.org/playground/
1. Remote Resource: https://cass.credentialengine.org/api/ceasn/ecd2a66f1248030413e240d9c287b165
1. Go to "Compact" tab
1. Set compaction context to read remotely from: http://credreg.net/ctdlasn/schema/context/json
1. Go look at the framework hasTopChild.

Again, not reproducing today on my end.

![image](https://user-images.githubusercontent.com/337692/54045288-14afcf00-4186-11e9-96ae-d5bb17c1af46.png)

**Comment by Lomilar** [comment]
Ah, the problem only appears with hasChild, not with hasTopChild.

1. https://json-ld.org/playground/
1. Remote Resource: https://cass.credentialengine.org/api/ceasn/e2501b0469739a6ab7c9638265d50a92
1. Go to "Compact" tab
1. Set compaction context to read remotely from: http://credreg.net/ctdlasn/schema/context/json
1. Go look at the competency hasChild.
Still not reproducing on my side.

Should this be closed?

**Comment by stuartasutton** [comment]
I can't get the resource to load in playground.

What's the conclusion?

**Comment by Lomilar** [comment]
I'm OK to close this. Re-open if necessary.
