### ISSUE TITLE
Determine whether to drop or modify ceterms:targetPathway

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#582]
The [targetPathway](https://credreg.net/ctdl/terms#targetPathway) property used to point at the now dropped (#581) CareerPathway class, and is currently `vs:unstable`. We could drop it, too, as we did with CareerPathway, or we could modify it to instead be used with the current Pathway class.

Thoughts?

**Comment by stuartasutton** [comment]
There is no question in my mind that we should update the range class to [ceterms:Pathway](http://purl.org/ctdl/terms/Pathway).

**Comment by jkitchensSIUC** [comment]
@siuc-nate let's update this issue to identify all related CTDL updates needed.

**Comment by siuc-nate** [comment]
See #555
