### ISSUE TITLE
Add a ceasn:abilityEmbodied property

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#583]
Currently, we have a [`ceasn:skillEmbodied`](http://purl.org/ctdlasn/terms/skillEmbodied) property with a domain of [`ceasn:Competency`](http://purl.org/ctdlasn/terms/Competency) that makes it possible for a specific competency to have a [`ceasn:competencyCategory`](http://purl.org/ctdlasn/terms/competencyCategory) of something like "Task" and then assert that that task has a `ceasn:skillEmbodied` of something like "Judgment and decision making." Current work on the Navy Task Classification indicates that we could benefit from a companion `ceasn:abilityEmbodied` property.

**Comment by stuartasutton** [comment]
For the ceasn:abilityEmbodied, I am proposing the following addition to cesan:

>**URI:** ceasn:abilityEmbodied
**Label:** Ability Embodied
**Comment:** Enduring attributes of the individual embodied either directly or indirectly in this competency that influence performance.
**Domain Includes:** ceasn:Competency
**RangeIncludes:** xsd:anyURI
**Usage Note**: The abilityEmbodied property may referenced a defined ability in an ontology such as O*NET or an existing competency defined in a competency framework.

Also, add the following Usage Note to ceasn:skillEmbodied:

>**Usage Note**: The skillEmbodied property may referenced a defined skill in an ontology such as O*NET or an existing competency defined in a competency framework.

**Comment by siuc-nate** [comment]
>Also, modify ceasn:skillEmbodied comment

I assume you mean the current definition?:
**From:** "Cognitive, affective, and psychomotor skills directly or indirectly embodied in this competency."
**To:** "Ability to apply knowledge and use know-how to complete tasks and solve problems including types or categories of developed proficiency or dexterity in mental operations and physical processes is embodied either directly or indirectly in this competency."

**Comment by stuartasutton** [comment]
Yes.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL-ASN and noted in the history tracking.
