### ISSUE TITLE
Guidelines for data quality, especially for length of credential description and others.

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#585]
We have a minimum data policy, for properties. 
We don’t have a specification or recommendations for content/data quality, especially for description. 
For example, I had noticed that one organization just used the credential name for the description. 
In other cases, I saw similar minimum effort for description. 
In the publisher we have added a edit to require a (very generous) minimum length of 25 characters. 
Should we have requirements where needed for properties like description, particularly for the major entities like credential, organization, assessment, and learning opportunity. 
This may be part of the work introduced in #584

**Comment by siuc-nate** [comment]
This was moved to trello.
