### ISSUE TITLE
Add ceterms:PathwayComponent usage note

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#586]
@siuc-nate, we need to add a usage note to [ceterms:PathwayComponent](http://purl.org/ctdl/terms/PathwayComponent) as follows:

>PathwayComponent is a super-type that represents a family of more precise sub-types.  In pathway descriptions, always use the sub-type of PathwayComponent appropriate to your circumstances, e.g., AssessmentComponent, CocurricularComponent, CompetencyComponent, CourseComponent, CredentialComponent, ExtracurricularComponent, JobComponent, and WorkExperienceComponent. Use BasicComponent for types of entities not covered by the current set of sub-types.

Ideally, this would be handled using a best practice on this class, but in the absence of full-fledged best practices, a usage note will do.

**Comment by siuc-nate** [comment]
Is it a good idea to list all of the existing subclasses? That will lead to needing to update that note any time we add or remove a class.

**Comment by stuartasutton** [comment]
Yes, it's necessary...it's not likely that there will be any kind of rush to add additional subclasses. Until we have a systematic, easy way for developers to quickly look up best practices (see https://github.com/CredentialEngine/vocabularies/issues/584), we're going to need to do some "building in".

**Comment by siuc-nate** [comment]
This change has been made in pending CTDL and noted in the history tracking.
