### ISSUE TITLE
Add skos terms to CTDL-ASN schema

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#588]
Use this document for reference:
https://docs.google.com/document/d/1VLlgPknH_vqhO-VAY39Q7_noJUT3vN_UT1PeTperUiE/edit?usp=sharing

- Add SKOS terms
- Generalize CTDL-ASN definitions to refer to "resource" instead of "competency"/"competency framework"
- Modify CTDL-ASN term domains/ranges as needed to incorporate concept schemes
- Apply required/recommended benchmark/optional status

Add SKOS classes:
---

>**URI:** skos:ConceptScheme
>**Label:** Concept Scheme
>**Description:** <needed>

>**URI:** skos:Concept
>**Label:** Concept
>**Description:** <needed>

Add SKOS properties:
---

>**URI:** skos:hasTopConcept
>**Label:** Has Top Concept
>**Description:** Concept of the scheme at the top of a hierarchy of narrower concepts.
>**Domain:** skos:ConceptScheme
>**Range:** skos:Concept
>**Importance:** Required

>**URI:** skos:inScheme
>**Label:** In Scheme
>**Description:** Concept scheme to which this concept belongs.
>**Domain:** skos:Concept
>**Range:** skos:ConceptScheme
>**Importance:** Required

>**URI:** skos:prefLabel
>**Label:** Preferred Label
>**Description:** Preferred language-tagged label representing this concept.
>**Domain:** skos:Concept
>**Range:** rdf:langString
>**Importance:** Required

>**URI:** skos:altLabel
>**Label:** Alternative Label
>**Description:** Non-preferred label for the concept used to relate a concept synonym to the preferred label.
>**Domain:** skos:Concept
>**Range:** rdf:langString
>**Importance:** Recommended Benchmark

>**URI:** skos:broadMatch
>**Label:** Broad Match
>**Description:** Assertion indicates that the referenced concept is broader in some way than this concept.
>**Domain:** skos:Concept
>**Range:** skos:Concept
>**Importance:** Recommended Benchmark

>**URI:** skos:broader
>**Label:** Broader
>**Description:** Concept that is broader in some way than this concept.
>**Domain:** skos:Concept
>**Range:** skos:Concept
>**Importance:** Recommended Benchmark

>**URI:** skos:changeNote
>**Label:** Change Note
>**Description:** Text describing a significant change to the concept.
>**Domain:** skos:Concept
>**Range:** rdf:langString
>**Importance:** Recommended Benchmark

>**URI:** skos:closeMatch
>**Label:** Close Match
>**Description:** Assertion indicates that two concepts are sufficiently similar that they can be used interchangeably.
>**Domain:** skos:Concept
>**Range:** skos:Concept
>**Importance:** Recommended Benchmark

>**URI:** skos:definition
>**Label:** Definition
>**Description:** Supplies a complete explanation of the intended meaning of a concept.
>**Domain:** skos:Concept
>**Range:** rdf:langString
>**Importance:** Recommended Benchmark

>**URI:** skos:exactMatch
>**Label:** Exact Match
>**Description:** Indicates semantic similarity denoting an even higher degree of closeness than skos:closeMatch.
>**Domain:** skos:Concept
>**Range:** skos:Concept
>**Importance:** Recommended Benchmark

>**URI:** skos:hiddenLabel
>**Label:** Hidden Label
>**Description:** Label not intended for public presentation but to assist applications in disambiguating searcher intent - e.g., hidden labels can be used for common misspelling or a colloquial expression.
>**Domain:** skos:Concept
>**Range:** rdf:langString
>**Importance:** Recommended Benchmark

>**URI:** skos:narrowMatch
>**Label:** Narrow Match
>**Description:** Assertion indicates that the referenced concept is narrower in some way than this concept.
>**Domain:** skos:Concept
>**Range:** skos:Concept
>**Importance:** Recommended Benchmark

>**URI:** skos:narrower
>**Label:** Narrower
>**Description:** Concept that is narrower in some way than this concept.
>**Domain:** skos:Concept
>**Range:** skos:Concept
>**Importance:** Recommended Benchmark

>**URI:** skos:notation
>**Label:** Notation
>**Description:** Alphanumeric notation or ID code as defined by the promulgating body to identify this resource.
>**Domain:** skos:Concept
>**Range:** xsd:string
>**Importance:** Recommended Benchmark

>**URI:** skos:note
>**Label:** Note
>**Description:** Annotations to the concept for purposes of general documentation.
>**Domain:** skos:Concept
>**Range:** rdf:langString
>**Importance:** Recommended Benchmark

>**URI:** skos:related
>**Label:** Related
>**Description:** Assertion indicating an associative, non-hierarchical relationship between the two concepts where neither is broader nor narrower than the other.
>**Domain:** skos:Concept
>**Range:** skos:Concept
>**Importance:** Recommended Benchmark

>**URI:** skos:topConceptOf
>**Label:** Top Concept Of
>**Description:** Concept scheme for which this concept is a top node in a hierarchy of concepts.
>**Domain:** skos:Concept
>**Range:** skos:ConceptScheme
>**Importance:** Recommended Benchmark

Modify CTDL-ASN terms:
---

>**URI:** ceasn:name
>**Description (remove):** The name or title of this competency framework.
>**Description (add):** The name or title of this resource.
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Required (addition)

>**URI:** ceasn:description
>**Description (remove):** A short description of this competency framework.
>**Description (add):** A short description of this resource.
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Required (addition)

>**URI:** ceasn:dateCreated
>**Description (remove):** Date of creation of this competency framework or competency.
>**Description (add):** Date of creation of this resource.
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Required (addition)

>**URI:** ceasn:inLanguage
>**Description (remove):** The primary language used in or by this competency framework or competency.
>**Description (add):** The primary language used in or by this resource.
>**Domain:** skos:ConceptScheme (addition), skos:Concept (addition)
>**Importance:** Required (addition)

>**URI:** ceasn:publicationStatusType
>**Description (remove):** The publication status of the of this competency framework.
>**Description (add):** The publication status of the of this resource.
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Required (addition)

>**URI:** ceasn:source
>**Description (remove):** The original competency framework which this competency framework is based on or derived from.
>**Description (add):** The original competency framework which this resource is based on or derived from.
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Required (addition)

>**URI:** ceasn:conceptKeyword
>**Description (remove):** A word or phrase used by the promulgating agency to refine and differentiate individual competencies contextually.
>**Description (add):** A word or phrase used by the promulgating agency to refine and differentiate individual resources contextually.
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Recommended Benchmark (addition)

>**URI:** ceasn:conceptTerm
>**Description (remove):** A term drawn from a controlled vocabulary used by the promulgating agency to refine and differentiate individual competencies contextually.
>**Description (add):** A term drawn from a controlled vocabulary used by the promulgating agency to refine and differentiate individual resources contextually.
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Recommended Benchmark (addition)

>**URI:** ceasn:creator
>**Description (remove):** An entity primarily responsible for making this competency framework or competency. 
>**Description (add):** An entity primarily responsible for making this resource. 
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Recommended Benchmark (addition)

>**URI:** ceasn:dateCopyrighted
>**Description (remove):** Date of a statement of copyright for this competency framework, such as ©2017.
>**Description (add):** Date of a statement of copyright for this resource, such as ©2017.
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Recommended Benchmark (addition)

>**URI:** ceasn:dateModified
>**Description (remove):** The date on which this framework or competency was most recently modified in some way. 
>**Description (add):** The date on which this resource was most recently modified in some way. 
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Recommended Benchmark (addition)

>**URI:** ceasn:license
>**Description (remove):** A legal document giving official permission to do something with this competency framework. 
>**Description (add):** A legal document giving official permission to do something with this resource. 
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Recommended Benchmark (addition)

>**URI:** ceasn:publisher
>**Description (remove):** An agent responsible for making this entity available.
>**Description (add):** An agent responsible for making this resource available.
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Recommended Benchmark (addition)

>**URI:** ceasn:publisherName
>**Description (remove):** Name of an agent responsible for making this entity available. 
>**Description (add):** Name of an agent responsible for making this resource available. 
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Recommended Benchmark (addition)

>**URI:** ceasn:rights
>**Description (remove):** Information about rights held in and over this competency framework.
>**Description (add):** Information about rights held in and over this resource.
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Recommended Benchmark (addition)

>**URI:** ceasn:rightsHolder
>**Description (remove):** An agent owning or managing rights over this competency framework.
>**Description (add):** An agent owning or managing rights over this resource.
>**Domain:** skos:ConceptScheme (addition)
>**Importance:** Recommended Benchmark (addition)

Modify CTDL terms:
---

>**URI:** ceterms:ctid
>**Description (remove):** Globally unique Credential Transparency Identifier (CTID) by which the creator, owner or provider of a credential, learning opportunity competency, or assessment recognizes the entity in transactions with the external environment (e.g., in verifiable claims involving a credential).
>**Description (add):** Globally unique Credential Transparency Identifier (CTID) by which the creator, owner or provider of a resource recognizes it in transactions with the external environment (e.g., in verifiable claims involving the resource).
>**Domain:** skos:ConceptScheme (addition), skos:Concept (addition)
>**Importance:** Required (addition)

**Comment by woodkri** [comment]
I have a couple of questions on these. Someone had brought this up yesterday, but in the spreadsheet we have skos:relatedMatch and the google doc/issue has skos:related. In the CaSS editor, we have Related Match, should this be changed to Related or kept as is?

I will need to add ceasn:source to the concept scheme profile of the editor. Which section should it go under (Context, Tagging, etc.)?

**Comment by Lomilar** [comment]
Right now we are using skos:relatedMatch. Leaving this open until we confirm one way or the other.

**Comment by stuartasutton** [comment]
There was a whole thread on skos:related and skos:relatedMatch filled with explanations.

**Comment by woodkri** [comment]
Really all I need to know for now is, which one does this statement pertain to? "Assertion indicating an associative, non-hierarchical relationship between the two concepts where neither is broader nor narrower than the other." We have this as the definition for relatedMatch, but above it is listed as related.

If both should be present in the editor, I would need the definition for the other one as well so that I can add it.

**Comment by Lomilar** [comment]
@stuartasutton Yeah, this was a placeholder comment, since we didn't know exactly where that thread was. Was going to link it in here and resolve it one way or the other momentarily.

**Comment by Lomilar** [comment]
https://github.com/cassproject/cass-editor/issues/531 has a comment on this.

**Comment by Lomilar** [comment]
It looks like skos:related and skos:relatedMatch are both relevant, however, skos:relatedMatch is a specialization (or stronger version) of skos:related.

From the spec:
`The property skos:related is used to assert an associative link between two SKOS concepts.`
`The property skos:relatedMatch is used to state an associative mapping link between two concepts.`

This leads me to believe that "Assertion indicating an associative...." definition refers to skos:related.

**Comment by stuartasutton** [comment]
The SKOS spec does not actually define these terms because they relied on long established practice in thesaurus construction and long standing ISO standards. The following text is mine from an email  on March 22 to Jeanne, Michael and Nate:

>Guys, sorry if this response is a bit pedantic, but skos has a property called ckos:related that in the world of thesauri construction is for pointing to a term that is semantically related but not in a broader/narrower sense. It has a super property of skos:semanticRelation. There is a property skos:relatedMatch that has super properties skos:mappingRelation AND skos:related. skos:relatedMatch is for pointing to a concept in some other concept scheme that is not just "related", but a close match in terms of identity. The skos:related is for general use for pointing to something that would be considered significantly "related"--e.g., "U.S. Civil War" might be skos:related "Abraham Lincoln" but would certainly not  be considered skos:relatedMatch (i.e., they certainly don't share an identity).
>
>Truth be told, our schema should have both. In fact, our context file for concept schemes should include ALL of the skos:properties even though our tool implementation might not (yet).

**Comment by siuc-nate** [comment]
@stuartasutton Are there official definitions for Concept Scheme and Concept? I wasn't able to find any obvious ones. If we need to come up with something, we will need to do so before I can put these into the system.

**Comment by siuc-nate** [comment]
I have added and modified the terms as described above in pending CTDL-ASN, using the following (placeholder?) definitions for Concept Scheme and Concept:

Concept Scheme: A controlled vocabulary.
Concept: Term in a controlled vocabulary.

These changes have not yet been added to history tracking.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL/CTDL-ASN and noted in the history tracking.
