### ISSUE TITLE
Use ACTE to Beta mapping as a mechanism to validate CASS mapping tool

### ISSUE THREAD

**Issue by Lomilar** [CredentialEngine/vocabularies#589]
In some areas, there exist competencies that are not specific, for instance, "Employs knowledge from diverse sources in a skill or in the completion of a task." or "Demonstrates basic cognitive and practical skills required to carry out tasks with stipulated rules."

These competencies are odd in that they do not refer to a specific task, and have been called "illustrative" or "descriptive" competencies. Another perspective could be that they are soft skills.

Describing the relationship between these competencies and more specific competencies (that they help illustrate) is somewhat ambiguous at this point. Does a 'requires' or 'prerequisite' relation suffice, or do we need a 'describedBy' type of relation?

**Comment by stuartasutton** [comment]
@Lomilar, full answer would need more contextual information. But, off the top of my head, nothing precludes handling the case of such refinements to a competency being declared as child nodes. The definition of ceasn:hasChild is deliberately defined to support such uses:

>The referenced resource is lower in some arbitrary hierarchy than this resource.

...key word being "arbitrary". So, you can have a parent node with a competency category (using your example framing) of "soft skill" and child nodes with competency categories of something like "task" or "benchmark" etc. 

Of course, that's assuming that these more refined competencies are being added by the creator of the framework...if you mean by others?...another kettle of fish.

**Comment by siuc-nate** [comment]
I would think that trying to establish a hierarchical relationship would lead to a problem like the following:

Say you have a competency, "Can tie shoes using only a fork and a spoon" - which of the two soft skills @Lomilar gives as examples would that fall under in a traditional hierarchy?  Both of them apply, and I don't think you'd want to repeat the competency under each of them. 

I think it'd be better to treat soft skills more like a conceptTerm vocabulary, or maybe even a concept scheme (if you could come up with suitable labels).  Failing that, one of the non-structural ____alignment properties seems like the best bet. I'm not sure which one would apply though.

**Comment by stuartasutton** [comment]
My concern here is that we are talking about what people developing competency frameworks should do when our concern is with capturing what they actually do. One thing that we (CE) do not do is add refinements to what you might call a  soft skill. 

In essence, I don't see what this issue is trying to solve.

**Comment by Lomilar** [comment]
Ah, I forgot to add some context: This is about relating across frameworks, not within a single framework, so hasChild does not apply.

**Comment by Lomilar** [comment]
So, within framework "A", there is a competency A.1 that states "Employs knowledge from diverse sources in a skill or in the completion of a task". This helps describe a competency in framework "B", say B.1 states "Fact-checking a news story." 

A.1 describes how B.1 is accomplished, so, does narrows apply here? Maybe requires? The issue is that A.1 is not specific enough to demonstrate without B.1's context, so a direct "requires" or "prerequisite" relationship doesn't seem to make sense. 

Statements of these types can also be found in some O*NET areas such as 3.C.2 Cross-functional Skills: "Complex Problem Solving Skills - Entry Requirement" stating "Entry requirement for developed capacities used to solve novel, ill-defined problems in complex, real-world settings"

which could also be useful when aligned to "Fact-checking a news story", but has difficulty standing alone.

**Comment by siuc-nate** [comment]
So in your example, A.1 is a broader version of B.1, but without the implication that there is any structural relationship between the two (essentially skos:broader without the hierarchical part), right? 

In CTDL-ASN, we have these: https://credreg.net/ctdlasn/handbook#strengthoffit

So something like broadAlignment might work:
```
B.1 -[broadAlignment]-> A.1
```
Assuming I don't have the arrow backwards, anyway.

**Comment by stuartasutton** [comment]
In many ways, SKOS and ASN are siblings (ASN was born a little earlier :-). While a best practice has not been formally defined in ASN (because the need has never arisen in practice), the ASN solution for the problem outlined in this issue would be to use the SKOS mechanism for incorporation by reference. [1]  It's a solution that does not require new properties of any sort, just substitute ceasn:isPartOf for skos:inScheme in the SKOS documentation.

As I've noted previously (ad nauseum), being able to do such incorporation by reference is somewhat dependent on whether the context of the referenced node does not render the mapping incongruous...context matters!

[1] https://www.w3.org/TR/2009/NOTE-skos-primer-20090818/#secextension

**Comment by siuc-nate** [comment]
So in effect:
```
"Fact-checking a news story." -[skos:inScheme]-> "Employs knowledge from diverse sources in a skill or in the completion of a task"
```
Or am I misinterpreting you?

**Comment by stuartasutton** [comment]
Here:
### Competency Framework A 
```
ex1:CompetencyFrameworkA a ceterms:CompetencyFramework;
   ceasn:name "Competency Framework A"@en.

ex1:1234 rdf:type ceasn:Competency;
   ceasn:competencyText "Employs knowledge from diverse sources in a skill or in the completion of a task"@en ;
   ceasn:hasChild ex2:5678 ;
   ceasn:isPartOf ex1:CompetencyFrameworkA.
```
### Competency Framework B

```
ex2:CompetencyFrameworkB a ceasn:CompetencyFramework;
   ceasn:name "Competency Framework B"@en. 

ex2:5678 a ceasn:Competency;
   ceasn:competencyText "Fact-checking a news story."@en;
   ceasn:isPartOf ex2:CompetencyFrameworkB .
```

**Comment by siuc-nate** [comment]
That creates a structural relationship (and a hierarchical one at that) between the two competencies, which is what we're trying to avoid.

**Comment by stuartasutton** [comment]
Why?

**Comment by siuc-nate** [comment]
Semantically, one competency isn't actually part of the other.  They come from different owners, different frameworks, created with different intents, etc.  The relationship is an alignment one, not a partitive one.

Practically, you'd end up having to do things like this:

**Some Framework**
- **Soft Skills**
  - "Employs knowledge from diverse sources in a skill or in the completion of a task"
    - "Fact-checking a news story."
  - "Demonstrates basic cognitive and practical skills required to carry out tasks with stipulated rules."
    - "Fact-checking a news story."

Plus all of the overhead of always having to look for, resolve, and render competencies that have partitive relationships but exist in different documents, and the implications that has for searching for competency frameworks based on the competencies in those frameworks, etc.

**Comment by stuartasutton** [comment]
I give up; but, I absolutely don't see you having solved anything you frame as "cons" by changing a property that nevertheless points to something in a different framework.

**Comment by Lomilar** [comment]
Narrows / Broadens may be the correct word, because narrows/broadens is intended for cross framework alignments, and indicates "is part of" from a conceptual perspective, less so from a structural perspective.

It seems a bit strange to consider narrows to apply to a non-specific (illustrative) competency that illustrates how the work is done, not what the work is -- but that could just be something I need to get over.

**Comment by siuc-nate** [comment]
Looking at it another way - if a case like this isn't where you would use the ___alignment properties (specifically broadAlignment in this case), then when _would_ you use those? It would be good for us to be on the same page about that regardless of this particular case.

**Comment by Lomilar** [comment]
I may have pinpointed what concerns me about illustrative competencies in a narrows or hasChild situation.

An illustrative or descriptive competency helps define the context, scope, or standard, in that it describes how the competency is applied. An example could just as easily be: "Performs skill to a professional standard".

1 Tightens a bolt.
1.1 Performs skill to a professional standard
1.2 Turns a wrench
1.3 Locks a wrench onto a bolt

The issue there is that how the competency is done (1.1) must propagate its implication to all of the children. The standard of performance isn't built into "tightens a bolt to a professional standard" -- its built into a child or a relation.

This means that the relationship "narrows" or "hasChild" may not be the right way to associate a competency to something that illustrates or describes the standard to which the competency is being held.

I am thinking this _is_ a descriptive problem. One that could be addressed through concept schemes as Nate pointed out, but it could also be addressed by a type of relation that describes context, scope, or standards that a competency must consider.

**Comment by Lomilar** [comment]
A critique I'd have, Nate, is that while your hierarchy there looks weird, it is exactly how context is established through the use of parents:

Fact checking a news story narrows both of those and both of those narrow Soft Skills. It's just that putting that into a hierarchy looks weird.

Maybe what I did is wrong, in that performing skills to a professional standard should be broader than tightening a bolt, so that the context can be properly established.

**Comment by siuc-nate** [comment]
Even so, my question about what something like broadAlignment is for (if not this) still stands.

**Comment by siuc-nate** [comment]
Per our 4-2-2019 meeting:

@stuartasutton will clean up the data in CASS prior to our walkthrough/mapping meeting.

**Comment by stuartasutton** [comment]
The ACT WorkKeys competency frameworks have been updated, approved and re-published and are ready for mapping to the Beta Connecting Credential levels via ACT’s mapping document. My understanding is that Jeanne will schedule a session for us to walk through the mapping process as we document both process and outcome.

**Comment by siuc-nate** [comment]
Per our 4-30-2019 meeting:

This has been taken care of.
