### ISSUE TITLE
Request for a new CostType of Fees

### ISSUE THREAD

**Issue by cwd-mparsons** [CredentialEngine/vocabularies#593]
@stuartasutton 
We have a request for a new cost type of Fees from Kansas. 
Related email (to Emilie): 

> We’d prefer a separate code for fees. We combine required fees and instructional fees in Kansas DegreeStats, and we plan to use that source for our cost profile. A course fee isn’t really a program fee, and a required fee such as health, technology, etc, isn’t a program fee at all. Thus, our request is to add a code for “FEES”. 
> Cynthia J Farrier
> Director of Data, Research and Planning
> Kansas Board of Regents

We already have several 'fee' cost types
![image](https://user-images.githubusercontent.com/26332112/55430319-6a905080-5553-11e9-85d3-d8239d0acc9c.png)

Fees would seem to general, other options:
- OtherRequiredFees (other would be too general as well)

Cynthia provided a sample of what they would like to publish:
![image](https://user-images.githubusercontent.com/26332112/55432747-4d5e8080-5559-11e9-923a-9ba05edb766b.png)

Definitions provided by Kansas
**Resident Tuition**: The typical (median) dollar amount charged as resident tuition to graduates from this degree program.
**Fees**: The typical (median) instructional and required fees charged by this degree program. Fees include course, lab, program, and special fees associated with this degree program of study. Also included are required fees charged to the majority of students, such as student health fees or technology fees.
**Room and Board**: The typical (median) room and board costs experienced by graduates in this degree program, living on- or off- campus. Charges may be estimates.
Books and Supplies: The estimated cost (median) of books and supplies experienced by graduates from this degree program.
**Total Annual Cost** (estimated): The sum of Tuition, Fees, Room and Board, Books and Supplies.

**Comment by siuc-nate** [comment]
Without knowing more about the "Fees" item, I can't speak with absolute certainty - but my best guess would be that this is accommodated by either [`costType:ProgramSpecificFee`](https://credreg.net/ctdl/vocabs/ProgramSpecificFee) or [`costType:OptionalCharges`](https://credreg.net/ctdl/vocabs/OptionalCharges) (or maybe [`costType:EnrollmentFee`](https://credreg.net/ctdl/vocabs/EnrollmentFee)).

It could create confusion to add another generic "Fees" term as it could lead to publishers not knowing if they should provide **both** the broken-out fee data **and** the sum of such data under "Fees" or if they should only provide one or the other.  If anything, I'd go with "OtherFees", but that is covered by the definitions for OptionalCharges and ProgramSpecificFee:

**OptionalCharges:** Cost for additional fees, other services, equipment, or facilities.
**ProgramSpecificFee:** Additional cost for participation with a specific program or course of study such as engineering, business, and nursing.

**Comment by siuc-nate** [comment]
Update the definition for OptionalCharges:
From: Cost for additional fees, other services, equipment, or facilities.
To: Cost for additional fees, other services, equipment, or facilities that are not required.

To cover the use case in question, we should also create a new cost type concept:
**URI:** costType:AggregateFees
**Label:** Aggregate Fees
**Definition:** Summarized fees for participation, materials, services, and other fees.

We may need an additional usage note or comment to indicate that publishers don't need to include data for this property if they provide data for the more specific/broken-out fee concepts (e.g., program-specific fee, enrollment fee, technology fee, etc).

**Comment by stuartasutton** [comment]
@siuc-nate, how is `AggregateFees` distinguishable from the existing [`costType:AggregateCost`](http://purl.org/ctdl/vocabs/costType/AggregateCost)?

**Comment by stuartasutton** [comment]
I agree with [Nate](https://github.com/CredentialEngine/vocabularies/issues/593#issuecomment-479182138) that adding "Fees" simply opens the door for people to dump everything into a big bucket. If there is such a big bucket, I'd also note that there should be a best practice documentation that says to use more detailed options if possible. 

Another instance of the need for a formal best practice infrastructure. Putting this into notations on the scheme will be seen by FEW.

**Comment by siuc-nate** [comment]
> @siuc-nate, how is `AggregateFees` distinguishable from the existing [`costType:AggregateCost`](http://purl.org/ctdl/vocabs/costType/AggregateCost)?

I think the simplest way to describe it would be to say that `costType:AggregateCost` covers **all** costs for a given thing (like a grand total), whereas `AggregateFees` covers _any_ costs/sets of costs (theoretically up to but not including "all" costs) - to cover cases like this where _some_ costs are described specifically but others are not.

**Comment by siuc-nate** [comment]
Per our 4-9-2019 meeting:

To support being able to publish a summary of costs:

Update the definition for OptionalCharges:
**From:** Cost for additional fees, other services, equipment, or facilities.
**To:** Cost for additional fees, other services, equipment, or facilities that are not required.

Create a new cost type concept:
**URI:** costType:MixedFees
**Label:** Mixed Fees
**Definition:** The sum of fees that are not identified individually.

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
