### ISSUE TITLE
Add ceasn:comprisedOf property

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#596]
When we developed the CTDL-ASN profile of ASN, we missed an important property: [comprisedOf](http://standards.asn.desire2learn.com/#comprisedOf). 

>**URI:** ceasn:encompasses
**Label:** Encompasses
**Description:** Resource being described includes, comprehends or encompass, in whole or in part, the meaning, nature or importance of the resource being referenced.
**Domain Includes:** ceasn:Competency,
**Range Includes:** ceasn:Competency, ceasn:Concept
**Equivalent Property:** asn:comprisedOf

**Comment by siuc-nate** [comment]
Per our 6-4-2019 meeting:
We already have https://credreg.net/ctdlasn/terms/comprisedOf, so this is unnecessary.
