### ISSUE TITLE
Consider adding schema:Course and/or schema:CourseInstance

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#597]
Related: https://docs.google.com/spreadsheets/d/1GpEuym2YQn0iJ2atdQmBtWZIj0Ii54D8wZN3vZkTJz4/edit#gid=0

We have properties that could be mapped to the following:
- Enrollment start
- Enrollment end
- Course start
- Course end

However, this point-in-time information is better suited to the domain of [schema:CourseInstance](https://schema.org/CourseInstance) (which already has startDate and endDate of its own), so we should consider:

A) adding ceterms:startDate and ceterms:endDate to ceterms:LearningOpportunityProfile
- This would lead to learning opportunity profile being used for the generic description of a course as well as instances of it
B) adding schema:CourseInstance (and possibly schema:Course?) to CTDL
- We could borrow one or both as-is from schema.org, perhaps only including the properties we need

Adding schema:CourseInstance would also cover the "Instructor" row/reference in the spreadsheet linked above.  Alternatively, we could add a property that references ceterms:Person to ceterms:LearningOpportunityProfile.

Use of schema:Course/schema:CourseInstance may also cover the "course description - short" row via schema:disambiguatingDescription.

**Comment by stuartasutton** [comment]
What's the rationale/use case(s) for doing so, Nate? 

P.S. We already have a ceterms:Course.

**Comment by siuc-nate** [comment]
Per our 4-30-2019 meeting:

We discussed this issue, and may revisit it in the future. For now, we're not going to include course instance terms in CTDL.
