### ISSUE TITLE
Add ceterms:audienceLevelType to ceterms:LearningOpportunityProfile and ceterms:AssessmentProfile

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#598]
ceterms:LearningOpportunityProfile and ceterms:AssessmentProfile do not have a way to indicate the audience level they are for.  We should add ceterms:LearningOpportunityProfile and ceterms:AssessmentProfile to the domain of ceterms:audienceLevelType.

**Comment by stuartasutton** [comment]
Sounds reasonable.

**Comment by siuc-nate** [comment]
Changes to be made:

**URI:** ceterms:audienceLevelType
**Domain:** add ceterms:LearningOpportunityProfile, add ceterms:AssessmentProfile

**Comment by siuc-nate** [comment]
This has been done in pending CTDL and noted in the history tracking.
