### ISSUE TITLE
NCES ID Property 

### ISSUE THREAD

**Issue by jkitchensSIUC** [CredentialEngine/vocabularies#601]
Currently, the CTDL includes some  properties used by U.S. federal agencies as unique identifiers including:

- PEDS ID https://credreg.net/ctdl/terms#ipedsID
- OPEID https://credreg.net/ctdl/terms/ipedsID#opeID

The NCES (National Center for Education Statistics) ID is for public schools, private schools, or colleges.  The NCES School ID is a 12 digit code, and the first 7 digits of this code are the NCES District ID.  NCES school ID codes have a variety of uses, including information for the Rural Educational Achievement Program (REAP), Safe Schools/Healthy Students, National Board of Professional Teaching Standards (NBPTS), and E-Rate applications.  

References:
https://nces.ed.gov/globallocator/  
https://nces.ed.gov/fastfacts/display.asp?id=47
https://nces.ed.gov/ccd/ccfaq.asp

**Comment by siuc-nate** [comment]
Per our 6-4-2019 meeting:
This seems okay, but we need a label, definition, etc.

**Comment by siuc-nate** [comment]
> **URI:** ceterms:ncesID
> **Label:** NCES ID
> **Definition:** National Center for Education Statistics (NCES) issued identifier for educational institutions comprised of a 12 digit code where the first 7 digits are the NCES District ID.
> **Domain:** ceterms:CredentialOrganization
> **Range:** xsd:string

**Comment by cwd-mparsons** [comment]
@stuartasutton @siuc-nate 
Can there be multiple of these identifiers, or only one per organization?

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.

Note: I am leaving this issue open pending an answer to @cwd-mparsons's question in the post above.

**Comment by cwd-mparsons** [comment]
@siuc-nate The question was answered by Jeanne - these are single values.
