### ISSUE TITLE
The comment for ceterms:sameAs is redundant with ceterms:socialMedia

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#606]
Currently, the comment for `ceterms:sameAs` reads:
"Entities that may indicate identity include, but are not limited to, descriptions of entities in open databases such as DBpedia and Wikidata or social media accounts such as FaceBook and LinkedIn."

We have previously created a `ceterms:socialMedia` property to unambiguously provide social media URLs:
"Social media access point for an agent or an agent's contact point."

We should remove the mention of social media from the comment for `ceterms:sameAs`.  Suggested replacement:
"Entities that may indicate identity include, but are not limited to, descriptions of entities in open databases such as DBpedia and Wikidata or other platforms."

**Comment by stuartasutton** [comment]
I don't think so. The `socialMedia` basically says this thing being described has some related social media account. The `sameAs` says that that thing over there that is socialMedia is the same as this things being described.

**Comment by siuc-nate** [comment]
Per our 7-16-2019 meeting:

Change the comment for ceterms:sameAs from
"Entities that may indicate identity include, but are not limited to, descriptions of entities in open databases such as DBpedia and Wikidata or social media accounts such as FaceBook and LinkedIn."
to:
"Entities that may indicate identity include, but are not limited to, descriptions of entities in open databases such as DBpedia and Wikidata or other platforms."

**Comment by siuc-nate** [comment]
This has been done in pending CTDL and noted in the history tracking.
