### ISSUE TITLE
Add skos:relatedMatch to CTDL-ASN

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#607]
This property was mentioned in #588 but was not explicitly indicated as a property to be included.  Our subsequent work indicates that we do need both properties.

Suggestion:
**URI**: skos:relatedMatch
**Label**: Related Match
**Definition**: Assertion indicating a closely associative, non-hierarchical relationship between the two concepts in different concept schemes where neither concept is broader nor narrower than the other.
**Comment**: This asserts a degree of equivalency between the two concepts.
**Domain:** skos:Concept
**Range:** skos:Concept

I'm not quite solid on the definition/comment, but I'm trying to differentiate it from something like skos:closeMatch

**Comment by stuartasutton** [comment]
Only so long as skos:relatedMatch is used to cross map between frameworks. It's one of the skos "mapping" properties.

**Comment by siuc-nate** [comment]
Per our 7-30-2019 meeting:
@stuartasutton has reasons for not including this - mainly that it tends to confuse people.  It should be removed from the spreadsheet that CASS is working with that originally spawned this issue.

**Comment by siuc-nate** [comment]
@jkitchensSIUC @Lomilar Can we close this?

**Comment by Lomilar** [comment]
Reopen if needed.
