### ISSUE TITLE
Edits to CTDL Concept Schemes

### ISSUE THREAD

**Issue by woodkri** [CredentialEngine/vocabularies#608]
Stuart brought up a couple of data issues in the CTDL Concept Schemes over at https://github.com/cassproject/cass-editor/issues/514. 

1. Missing broader/narrower. Both OrganizationType and AudienceLevel have concepts with broader/narrower relationships. The narrower nodes are missing.

2. The vocabulary for ClaimType is including its deprecated concept.

**Comment by siuc-nate** [comment]
These should be fixed now.
