### ISSUE TITLE
Registry policy recommends deprecated credit properties

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#613]
As @cwd-mparsons pointed out to me in an email:
The https://credreg.net/registry/policy page still refers to the deprecated credit properties:
![image](https://user-images.githubusercontent.com/21346519/60285858-12f44d80-98d4-11e9-9c7b-0ce12425be48.png)
These properties were effectively replaced by https://credreg.net/ctdl/terms/creditValue

The policy should be updated to reflect this. Does this need to go through any kind of formal process or should it be considered implicit in the fact that that property replaced the others?

**Comment by stuartasutton** [comment]
I think it is implicit. Many decisions need mopping up after and those actions are implied in the original decision.

**Comment by siuc-nate** [comment]
Changes to be made:
- Remove references to the deprecated properties
- Add reference to ceterms:creditValue as a recommended benchmark property

To do:
Determine the policy (required, benchmark) for schema:QuantitativeValue

**Comment by siuc-nate** [comment]
Changes to be made to the CTDL Policy:
- Remove references to:
  - ceterms:creditHourType
  - ceterms:creditHourValue
  - ceterms:creditUnitType
  - ceterms:creditUnitValue
- Add the following as Recommended Benchmark:
  - ceterms:creditValue
  - schema:description
  - schema:maxValue
  - schema:minValue
  - schema:unitText
  - schema:value

**Comment by siuc-nate** [comment]
These changes have been made in the CTDL policy.
