### ISSUE TITLE
Removing deprecated terms from general public view

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#615]
@siuc-nate & @jkitchensSIUC, we need to suppress the listing of deprecated terms from the TOC and definition tables of [/terms/](https://credreg.net/ctdl/terms) and [ctdlasn](https://credreg.net/ctdlasn/terms). If necessary, there could be a page like the schema.org "attic" page where they could be listed. Once deprecated, we don't want to offer even the slightest opportunity for these deprecated properties/classes to be used anew. They have to remain in the validation schema to support old uses of the terms, but make them dead to everyone else without significant searching to find them.

**Comment by siuc-nate** [comment]
They default to not being visible - you have to click the button at the bottom of the page.  Do we need to go farther?

**Comment by stuartasutton** [comment]
As far as I can tell, that filter does not affect the TOC for properties and classes, just access to their definition tables. If the default was to not see BOTH the TOC **and** the tables, we'd be OK. But the deprecated entries in the TOC of classes and properties aren't being defaulted to 'off'; they are always present.

**Comment by siuc-nate** [comment]
These terms have been hidden in the table of contents.
