### ISSUE TITLE
Add owl:equivalentProperty for CASE properties

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#619]
We need to add [owl:equivalentProperty](https://www.w3.org/TR/owl-ref/#equivalentProperty-def) assertions in the CTDL-ASN terms declarations for CASE properties to support presentation of data (in the Finder etc.) where a Credential in the CER references a node in a CASE competency framework located in the IMS CASE Registry (or any other CASE registry supporting content negotiation).

| CTDL-ASN | CASE owl:equivalentProperty|
|:-----------:|:-----------:|
| https://purl.org/ctdlasn/terms/educationLevelType | https://purl.imsglobal.org/spec/case/v1p0/vocab#educationLevel |
| https://purl.org/ctdlasn/terms/listID | https://purl.imsglobal.org/spec/case/v1p0/listEnumeration |
| https://purl.org/ctdlasn/terms/codedNotation | https://purl.imsglobal.org/spec/case/v1p0/humanCodingScheme |
| https://purl.org/ctdlasn/terms/competencyText | https://purl.imsglobal.org/spec/case/v1p0/fullStatement |
| https://purl.org/ctdlasn/terms/comment | https://purl.imsglobal.org/spec/case/v1p0/notes |
| https://purl.org/ctdlasn/terms/inLanguage | https://purl.imsglobal.org/spec/case/v1p0/language |
| https://purl.org/ctdlasn/terms/competencyCategory | https://purl.imsglobal.org/spec/case/v1p0/CFItemType |

### Examined CASE Example
```
{
   "uri": "http://frameworks-staging.act.org/uri/6ccbc779-d7cc-11e8-824f-0242ac160002",
   "identifier": "6ccbc779-d7cc-11e8-824f-0242ac160002",
   "lastChangeDateTime": "2019-03-05T19:05:21+00:00",
   "CFDocumentURI": {
      "title": "Arizona Mathematics Standards",
      "identifier": "9f947940-3f79-11e9-b3a0-d96f3f50d6f0",
      "uri": "http://frameworks-staging.act.org/uri/9f947940-3f79-11e9-b3a0-d96f3f50d6f0"
   },
   "CFItemType": "Standard",
   "CFItemTypeURI": {
      "title": "Standard",
      "identifier": "0b9e2c6e-99d4-11e7-a0fc-b4076dcb6241",
      "uri": "http://frameworks-staging.act.org/uri/0b9e2c6e-99d4-11e7-a0fc-b4076dcb6241"
   },
   "educationLevel": [
      "KG",
      "01",
      "02",
      "03",
      "04",
      "05",
      "06",
      "07",
      "08",
      "09",
      "10",
      "11",
      "12"
   ],
   "humanCodingScheme": "MP2",
   "listEnumeration": "2",
   "fullStatement": "Reason abstractly and quantitatively.",
   "notes": "Mathematically proficient students make sense of quantities and their relationships in problem situations. They bring two complementary abilities to bear on problems involving quantitative relationships: the ability to decontextualize\u2014to abstract a given situation and represent it symbolically and manipulate the representing symbols as if they have a life of their own, without necessarily attending to their referents\u2014and the ability to contextualize, to pause as needed during the manipulation process in order to probe into the referents for the symbols involved. Quantitative reasoning entails habits of creating a coherent representation of the problem at hand; considering the units involved; attending to the meaning of quantities, not just how to compute them; and knowing and flexibly using different properties of operations and objects.",
   "language": "en",
   "statusStartDate": "2019-03-05",
   "statusEndDate": "2019-03-05"
}
```
### Note

This is a result of a discussion on 2019-09-03 with me, Joshua Marks and Greg Nadeau in relation to upcoming Broward Country project to enter credentials in the CER that directly reference nodes in the IMS CASE competency framework registry. 

I spoke briefly about it with @siuc-nate on the weekly CTDL call on 2019-09-03. Additional discussions on credential entry are needed to determine the right level of granularity. Original discussions with @jeff-grann were around one credential per competency which Joshua, Greg and I thought "excessive".

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL-ASN and noted in the history tracking.
