### ISSUE TITLE
Add ceasn:competencyLabel to ceasn:Competency

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#627]
While most competencies do not have names (i.e. text distinct from their `competencyText` that literally "names" the competency), there are cases where that data _does_ exist, and we currently are not capturing it correctly.

For cases where a competency does have both a name and a semantically-important `competencyText` (what would otherwise be "description" in other contexts), what usually ends up happening is:

- The name of the competency ends up in the `competencyText` field
- The important text of the competency ends up in the non-normative `comment` field

I don't know offhand of cases where a competency has a name, text, _and_ a comment, but that is also a possibility.

I think we should consider adding ceasn:name to ceasn:Competency.  Or, more formally:

Proposal:
**Add**
> **Subject:** ceasn:name
> **Predicate:** schema:domainIncludes
> **Object:** ceasn:Competency

Alternatively, we could explore adding ceasn:description to ceasn:Competency, so that that kind of text at least ends up somewhere more semantically meaningful - but that would probably create more problems than it solves.

**Comment by siuc-nate** [comment]
We have the same problem (and potentially the same solution) in the realm of Task data.  For instance, there are a lot of cases where the current sample data for a Maintenance Task uses `taskText` to provide a short summary or name of the task, while the actual description of the task winds up in `comment`, e.g.:

**Task Text:** Inspect Oil Tank
**Comment:** Visually inspect oil tank assembly for leaks or deteriorated condition.

This should really be

**Name:** Inspect Oil tank
**Task Text:** Visually inspect oil tank assembly for leaks or deteriorated condition.

**Comment by stuartasutton** [comment]
Here's a counter proposal. 

Proposal:
**Add**
> **URI:** ceasn:competencyLabel
> **Definition:** Short identifying phrase or name applied to a competency by the creator of the competency framework.
> **Subproperty Of:** ceasn:name
> **Usage Note:** Where such a label is the sole expression of the competency, enter the text as competencyText as opposed to the competencyLabel.

This has to be a distinct property from name because it has specific usage requirements and is thus a narrowing (refinement) of ceasn:name.

**Comment by stuartasutton** [comment]
P.S. The "by the creator of the competency framework" language is there to stop 2nd party people from adding names because they find it useful.

**Comment by siuc-nate** [comment]
I don't like having an additional property just for this, but I can't deny your logic.  It also seems like "label" would be less likely to be confused for "the place to put the text of the competency" even if someone didn't read the usage note.  And it would fit with competencyText being a subproperty of description.  So it makes sense.

I would be curious to hear @Lomilar's input as well.

**Comment by siuc-nate** [comment]
Per our 10-15-2019 meeting:

**Add**
> **URI:** ceasn:competencyLabel
> **Definition:** Short identifying phrase or name applied to a competency by the creator of the competency framework.
> **Domain:** ceasn:Competency
> **Range:** rdf:langString
> **Subproperty Of:** ceasn:name
> **Usage Note:** Where such a label is the sole expression of the competency, enter the text as competencyText as opposed to competencyLabel.

**Comment by siuc-nate** [comment]
This has been added to pending CTDL-ASN and noted in the history tracking.
