### ISSUE TITLE
errors in schema definitions files

### ISSUE THREAD

**Issue by philbarker** [CredentialEngine/vocabularies#820]
I get the following error when trying to import CTLD TTL schema definitions into GraphDB

> ctdl-21032021.ttl ￼  RDF Parse Error: Expected '.', found 's' [line 536]		

Line 536 is 
`rdfs:subClassOf ceterms:LearningOpportunityProfile schema:EducationalOccupationalProgram ;`

but  should be
`rdfs:subClassOf ceterms:LearningOpportunityProfile, schema:EducationalOccupationalProgram ;`
[add a comma]

And in CTDL-ASN I get
> ctdlasn-21032021.ttl ￼  RDF Parse Error: Namespace prefix 'vann' used but not defined [line 103]

for which the obvious fix works

**Comment by siuc-nate** [comment]
I have fixed the missing vann declaration in the context. The turtle fix will take some changes to the code that I'll try to get to as soon as I can.

**Comment by siuc-nate** [comment]
@philbarker Is this still an issue?

**Comment by philbarker** [comment]
No longer an issue, TTL files are fixed now. Thanks @siuc-nate .
