### ISSUE TITLE
Add property for Carnegie research activity classification 

### ISSUE THREAD

**Issue by stuartasutton** [CredentialEngine/vocabularies#856]
The Carnegie research activity classification categorizes CredentialOrganizations according to the level of their research activity. Carnegie warns that the classification is not in itself an attestation of quality; however, it indicates a high probability of graduate student engagement in faculty research and a record over time of meaningful research. (See: https://carnegieclassifications.acenet.edu/classification_descriptions/basic.php (includes more than just the activity rating))

>**URI:** ceterms:researchActivityRating
**Label:** research activity rating
**Definition:** Year-specific Carnegie classification of institutional research activity.
**Comment:** The R1 and R2 categories include only institutions that awarded at least 20 research/scholarship doctoral degrees and had at least $5 million in total research expenditures (as reported through the National Science Foundation (NSF) Higher Education Research & Development Survey (HERD)).
**Domain:** ceterms:CredentialOrganization
**Range:** skos:Concept (Values: "R1: Doctoral Universities – Very high research activity", "R2: Doctoral Universities – High research activity"; "D/PU: Doctoral/Professional Universities")

For the latest R1/R2 listing, see: https://cehd.gmu.edu/assets/docs/faculty/tenurepromotion/institutions-research-categories.pdf.

**Comment by stuartasutton** [comment]
I'm not opposed to generalizing it if the definition has a "such as" that identifies Carnegie research activity. I've been around higher education in the US for over 1/2 a century and this attribute in the US is recognized through the Carnegie Classification. As for "best way to embody it", it is the only widely (very widely) recognized manner in the US.

**Comment by siuc-nate** [comment]
Archiving this, as it hasn't seen demand in a few years.
