### ISSUE TITLE
Intended purpose vocabulary: verify definitions

### ISSUE THREAD

**Issue by siuc-nate** [CredentialEngine/vocabularies#87]
We need to make sure the definitions are correct - currently they are marked in red.  Additionally, midCareer has a note of "experienced worker" that needs clarification.

https://docs.google.com/spreadsheets/d/1iRj0vYCV3ZYETmQMLPNB2plmrxx50eFHWCBeCERZx14/edit#gid=0
Rows #92-95

Edit: updated reference: http://credreg.net/ctdl/terms/IntendedPurpose

**Comment by stuartasutton** [comment]
I revised the "midCareer" definition to read "The purpose of the credential as identified by the relevant agent is for mid-career, ***experienced worker*** preparation and advancement of the holder."

I think that these definitions are in red simply because they were not turned black during the session when the team did a cursory review.

***I have not updated this vocabulary in GitHub.***

**Comment by jkitchensSIUC** [comment]
This was emailed to Bob on Nov 14, 2016 by Jeanne.

Below is the ctdl:IntendedPurpose vocabulary.  I’m thinking this one needs to be flagged as unstable. I put this in GitHub Issue 87 https://github.com/CredentialTransparencyInitiative/vocabularies/issues/87

We need your input ASAP on this one.  See below.  There’s not much to it but I don’t think we have received very good, usable input into this one and we should survey partners. 

ctdl:IntendedPurpose	purpose:GeneralEducation	General Education	The purpose of the credential as identified by the relevant agent is for the general education of the holder.
ctdl:IntendedPurpose	purpose:JobOrCareerPreparation	Job/Career Preparation	The purpose of the credential as identified by the relevant agent is for job or career preparation of the holder. 
ctdl:IntendedPurpose	purpose:MidCareer	Mid-Career Level	The purpose of the credential as identified by the relevant agent is for mid-career, experienced worker preparation and advancement of the holder.
ctdl:IntendedPurpose	purpose:PriorExperience	Prior Learning Experience	The purpose of the credential as identified by the relevant agent is for prior determining learning experience of the holder.

**Comment by siuc-nate** [comment]
We need to setup a google doc for this to determine next steps to either scrap or define this property.

**Comment by siuc-nate** [comment]
What are the next steps?

**Comment by siuc-nate** [comment]
We should review the required/minimum properties survey regarding this vocabulary.

**Comment by stuartasutton** [comment]
At a minimum, there is a disconnect between the definition of the `ceterms:intendedPurpose` property (framed as in terms of the intention of the "credential holder" and the concept definitions that are framed in terms of the intention of the credential creator.

**Comment by siuc-nate** [comment]
There is, but I think we're not too far off.

The terms in that vocabulary were invented way back in the early days of CTDL, and it kind of shows.

Anyway, from what I gather/remember, the purpose of that property and its vocabulary are to answer "why would you bother getting this credential?".  We provide the following terms:
- **GeneralEducation:** The purpose of the credential as identified by the relevant agent is for the general education of the holder.
- **JobOrCareerPreparation:** The purpose of the credential as identified by the relevant agent is for job or career preparation of the holder.
- **MidCareer:** The purpose of the credential as identified by the relevant agent is for mid-career, experienced worker preparation and advancement of the holder.
- **PriorExperience:** The purpose of the credential as identified by the relevant agent is for prior determining learning experience of the holder.

The first two make sense, but essentially boil down to a binary "do you get this credential for a job? yes/no" question that doesn't really provide any value to anyone looking for credentials, since any credential _could_ be for a job (and nearly all of the ones we care about - that is to say, the subclasses of ceterms:Credential - _would_ be).

I have reread the definitions for the second two, and I can't make heads or tails of either of them. 

As best I can recall, MidCareer was intended for moving upwards or sideways within a company, but it definitely needs to be rewritten.  PriorExperience sounds like something that would mean "this credential proves you already have experience in ____", but the definition doesn't say that at all (or if it does, I don't get that from reading it).

I also think it's overkill to have "job or career" preparation and not just one or the other.

Ultimately I don't see much real value in asking or answering this question, so **I would suggest dropping the vocabulary and the property that points to it altogether.**  They're all unstable anyway.

But _if we're going to keep it_, then we need to, at a minimum, rewrite the definitions of MidCareer and PriorExperience to make sense and be clear.

@jkitchensSIUC @stuartasutton @cwd-mparsons Thoughts?

**Comment by stuartasutton** [comment]
The "job or career" language signal different things:

http://www.diffen.com/difference/Career_vs_Job

**Comment by siuc-nate** [comment]
We need to review the survey comments for this vocabulary.

**Comment by siuc-nate** [comment]
Per our 4-10-2018 call:
- Stuart advises that we consider dropping this property and its vocabulary.

**Comment by jkitchensSIUC** [comment]
@stuartasutton @siuc-nate I agree that it should be deprecated.  I'm asking Scott to provide input.

**Comment by siuc-nate** [comment]
Per our 4-9-2019 meeting:
1. Drop (not deprecate) the Intended Purpose concept scheme and all of its concepts.
2. Explain that the decision is to not advance this to recommended status.
3. Ensure that the change history reflects the removal

**Comment by siuc-nate** [comment]
These changes have been made in pending CTDL and noted in the history tracking.
